<template><div class="page"><div class="page-header"><h2>供应商管理</h2></div><el-card shadow="never"><el-table :data="items" v-loading="loading" stripe size="small" highlight-current-row @row-click="open"><el-table-column prop="supp_cd" label="供应商编码" width="100"/><el-table-column prop="supp_nm" label="供应商名称" min-width="160" show-overflow-tooltip/><el-table-column label="分类" width="120"><template #default="{row}">{{ className(row.class_cd) }}</template></el-table-column><el-table-column prop="contactor" label="联系人" width="100"/><el-table-column prop="phoneno" label="电话" width="120"/></el-table><div style="margin-top:12px;text-align:right;color:#909399;font-size:13px">共 {{ items.length }} 条</div></el-card><el-dialog :title="'供应商 — '+(detail?.supp_nm||'')" v-model="drawer" width="550px"><template v-if="detail"><el-descriptions :column="2" border size="small"><el-descriptions-item label="编码">{{ detail.supp_cd }}</el-descriptions-item><el-descriptions-item label="名称">{{ detail.supp_nm }}</el-descriptions-item><el-descriptions-item label="分类">{{ className(detail.class_cd) }}</el-descriptions-item><el-descriptions-item label="联系人">{{ detail.contactor || '-' }}</el-descriptions-item><el-descriptions-item label="电话">{{ detail.phoneno || '-' }}</el-descriptions-item><el-descriptions-item label="地址" :span="2">{{ detail.address || '-' }}</el-descriptions-item></el-descriptions><h4 style="margin:16px 0 8px">供应商品</h4><el-table :data="detailItems" size="small" stripe v-loading="detailLoading"><el-table-column prop="itemcd" label="物料编码" width="100"/><el-table-column prop="item_nm" label="物料名称" min-width="140"/><el-table-column label="默认" width="60"><template #default="{r}"><el-tag :type="r.dfltflg==='Y'?'success':'info'" size="small">{{ r.dfltflg==='Y'?'是':'否' }}</el-tag></template></el-table-column><el-table-column prop="delivercycle" label="配送周期" width="80"/><el-table-column prop="servicecycle" label="服务周期" width="80"/><el-table-column prop="guaranteeperiod" label="质保期" width="80"/></el-table></template></el-dialog></div></template>
<script setup lang="ts">import {ref,onMounted} from 'vue';import {ElMessage} from 'element-plus';import {useCustClass} from '@/composables/useCustClass';import request from '@/api/request'
interface Supp{ supp_cd:string;supp_nm:string;class_cd:string;contactor:string;phoneno:string;address:string;[key:string]:unknown }
const items=ref<Supp[]>([]);const loading=ref(false);const{className}=useCustClass()
const drawer=ref(false);const detail=ref<Supp|null>(null)
const detailItems=ref<Record<string,unknown>[]>([]);const detailLoading=ref(false)
async function load(){loading.value=true;try{const res=await request.get<never,{data:Supp[]}>('/suppliers');items.value=res.data||[]}catch{ElMessage.error('加载失败')}finally{loading.value=false}}
async function open(row:Supp){detail.value=row;drawer.value=true;/* TODO: 需要后端新增 GET /suppliers/<custcd>/items 端点 */detailItems.value=[]}
onMounted(()=>load())</script>
<style scoped>.page{padding:0}.page-header{display:flex;justify-content:space-between;margin-bottom:16px}.page-header h2{font-size:18px;font-weight:600;margin:0}</style>
