SELECT  0 choose, --计划单关系业务单
		B.OPBILLID,
         B.SLBILLID,
         B.CUSTCD CLASSCD,
         B.IMPDATE,
         B.TRAINDATE,
         B.BUSITYP,
         B.SLTYP,
         B.ITEMCD,
         B.OPERCD,
         B.BACKUP,
         B.GENDATE,
         B.USEFLG,
         DECODE(B.SLTYP,'XZ',KT.CURRENT_STATUS,'GX',FX.CURRENT_STATUS,'BG',BG.CURRENT_STATUS,'BQ',BG.CURRENT_STATUS,'CK',BG.CURRENT_STATUS,'GH',GH.CURRENT_STATUS) BIZUSEFLG,
         B.AUDITFLG,
         B.AUDITMAN,
         B.AUDITDATE  ,
       DECODE(B.SLTYP,'XZ',A.CUSTCARD,'GX',A.CUSTCARD,'BG',BG.NEW_STORE_CARD,'BQ',BG.NEW_STORE_CARD,'CK',BG.NEW_STORE_CARD,'GH',A.CUSTCARD) CUSTCARD,
       DECODE(B.SLTYP,'XZ',A.CUSTCD,'GX',A.CUSTCD,'BG',BG.NEW_STORE_ID,'BQ',BG.STORE_ID,'CK',BG.STORE_ID,'GH',GH.STORE_ID) CUSTCD,
       DECODE(B.SLTYP,'XZ',KT.CLOSE_TIME,'GX',FX.CLOSE_TIME,'BG',BG.CLOSE_TIME,'BQ',BG.CLOSE_TIME,'CK',BG.CLOSE_TIME,'GH',GH.CLOSE_TIME) OPENDATE,
       DECODE(B.SLTYP,'XZ',KT.NEW_OPENING_ID,'GX',FX.RENEW_ID,'BG',BG.DEVICE_CHANGE_ID,'BQ',BG.DEVICE_CHANGE_ID,'CK',BG.DEVICE_CHANGE_ID,'GH',GH.RENEW_ID) BIZID,
       (SELECT max(D2D_DESCRIPITON) FROM TIT23_MAINTENANCE_D2D
         WHERE USEFLG = '1' AND d2d_type = '2' AND
               MAINTENANCE_ID IN(DECODE(B.SLTYP,'XZ',KT.NEW_OPENING_ID,'GX',FX.RENEW_ID,'BG',BG.DEVICE_CHANGE_ID,'BQ',BG.DEVICE_CHANGE_ID,'CK',BG.DEVICE_CHANGE_ID,'GH',GH.RENEW_ID))) D2D_DESCRIPITON
 FROM tsl02_extenddt A
 LEFT JOIN TSL01_EXTEND  B ON A.OPBILLID = B.OPBILLID
 LEFT JOIN tmm22_customers CUST ON A.CUSTCD = CUST.CUSTCD
 LEFT JOIN TIT13_MAINTENANCE_OPEN KT ON A.CUSTCD = KT.STORE_ID AND A.OPBILLID = KT.REQUSET_PAPER_ID
 LEFT JOIN TIT15_MAINTENANCE_RENOVATE FX ON A.CUSTCD = FX.STORE_ID AND A.OPBILLID = FX.REQUSET_PAPER_ID
 LEFT JOIN TIT16_DEVICE_CHANGE BG ON A.CUSTCD = BG.STORE_ID AND A.OPBILLID = BG.REQUSET_PAPER_ID
 LEFT JOIN TIT28_FREE_REPLACE GH ON A.CUSTCD = GH.STORE_ID AND A.OPBILLID = GH.REQUSET_PAPER_ID
WHERE 1=1
ORDER BY A.OPBILLID

