SELECT A.MAINTENANCE_ID,   --统计客户最后维护情况
A.STORE_ID,
A.SHORT_DESCRIPTION,
A.DETAIL_DESCRIPTION,
A.REQUEST_TIME ,
A.DEVICE_ID,
B.D2D_ENGINEER,
B.D2D_DESCRIPITON,
B.JJBZ
FROM TIT10_MAINTENANCEDAY A
LEFT JOIN TIT23_MAINTENANCE_D2D B ON B.MAINTENANCE_ID = A.MAINTENANCE_ID AND B.D2D_TYPE = '2' AND B.USEFLG = '1' AND B.JJBZ = '5'
WHERE A.MAINTENANCE_ID IN(SELECT max(MAINTENANCE_ID) FROM TIT10_MAINTENANCEDAY WHERE CURRENT_STATUS <> '9' GROUP BY STORE_ID)

