SELECT MAX(U.AREAID) AS AREA,
       W.MAINTENANCE_ID AS MASTER_ID,
       NVL(TRIM(W.FIRSTOR),'无名氏') AS FIRSTOR,
       W.IS_SUCCESS,
       C.BUSITYP,
       C.CLASSCD,
       C.AREA,
       MIN(W.CREATE_TIME) AS CREATE_TIME,
       COUNT(*) AS SUMCOUNT,
       (SELECT COUNT(*) FROM TIT21_MAINTENANCE_DISPATCH D WHERE D.MAINTENANCE_ID = W.MAINTENANCE_ID ) PDCS,
       W.CURRENT_STATUS,
       W.FAULT_TYPE,
       W.VIEW_TYPE ,
       C.location
FROM TIT10_MAINTENANCEDAY W,TMM22_CUSTOMERS  C,TIT06_USERAREA U
WHERE W.STORE_ID = C.CUSTCD
AND   W.FIRSTOR = U.USERCD(+)
AND CURRENT_STATUS <>'9'
GROUP BY W.MAINTENANCE_ID,W.FIRSTOR,C.BUSITYP,W.IS_SUCCESS,C.CLASSCD,C.AREA, W.CURRENT_STATUS, W.FAULT_TYPE,W.VIEW_TYPE,C.location
ORDER BY W.FIRSTOR

