SELECT C.AREA,C.CUSTCD,0,0,0,1,0,M.CLOSE_TIME
FROM TIT17_MAINTENANCE M,TMM22_CUSTOMERS C
WHERE M.CURRENT_STATUS = '3'
AND M.STORE_ID = C.CUSTCD
union all
SELECT   AREA,'',COUNT(*),0,0,0,0,NULL
 FROM TMM22_CUSTOMERS C
 WHERE  C.BUSITYP <> 'YX'
 GROUP BY C.AREA
union all
SELECT AREA,'',0,COUNT(*),0,0,0,NULL
 FROM TMM22_CUSTOMERS C
 WHERE C.USEFLG = '1'
 AND C.BUSITYP <> 'YX'
 GROUP BY C.AREA
union all
SELECT AREA,'',0,0,COUNT(*),0,0,NULL
 FROM TMM22_CUSTOMERS C
 WHERE C.USEFLG = '0'
 AND C.BUSITYP <> 'YX'
 GROUP BY C.AREA

