SELECT '1000' seqid, --OP_BIZ_ACCOUNT_seqno.Nextval, --门店开通单关系业务流水账
      a.NEW_OPENING_ID AS BIZBILL,
      'XZ' BIZTYPE,
      a.CREATE_TIME AS BIZDATE,
     a.REQUSET_PAPER_ID PLAN_NO,
     S.SLTYP,
     C.ITEMCD ITEMTYP ,
     a.DEVICE_ID EID,
     C.PRDDATE PRDDATE,
     C.MANUF_SEQ MANUF_SEQ,
     '1' ETYP,
     '1' SFLG,
     c.QCFLG QCFLG,
     '' WHCD,
      (SELECT MAX(D2D_ENGINEER) FROM TIT23_MAINTENANCE_D2D WHERE MAINTENANCE_ID = A.NEW_OPENING_ID)D2D_ENGINEER,
     B.CUSTCARD CUSTCARD,
     A.STORE_ID CUSTCD,
     B.CUSTNM CUSTNM,
     b.CLASSCD,
     b.USEFLG,
     b.S_STATUS,
     b.POS_N,
     '' mark
 FROM TIT13_MAINTENANCE_OPEN a
 LEFT JOIN TMM22_CUSTOMERS B ON a.STORE_ID = B.CUSTCD
 LEFT JOIN TMM43_EID C ON  a.DEVICE_ID = C.EID
 LEFT JOIN TSL01_EXTEND S ON a.REQUSET_PAPER_ID = S.OPBILLID
 WHERE  a.CURRENT_STATUS = '3'

 union all
--旧机翻新单关系业务流水账
SELECT '2000' seqid, --OP_BIZ_ACCOUNT_seqno.Nextval,
      a.RENEW_ID AS BIZBILL,
      'GX' BIZTYPE,
      a.CREATE_TIME AS BIZDATE,
      a.REQUSET_PAPER_ID PLAN_NO,
      S.SLTYP,
     C.ITEMCD ITEMTYP ,
     a.NEW_DEVICE_ID EID,
     C.PRDDATE PRDDATE,
     C.MANUF_SEQ MANUF_SEQ,
     '1' ETYP,
     '1' SFLG,
     c.QCFLG QCFLG,
     '' WHCD,
      (SELECT MAX(D2D_ENGINEER) FROM TIT23_MAINTENANCE_D2D WHERE MAINTENANCE_ID = A.RENEW_ID)D2D_ENGINEER,
     B.CUSTCARD CUSTCARD,
     A.STORE_ID CUSTCD,
     B.CUSTNM CUSTNM,
     b.CLASSCD,
     b.USEFLG,
     b.S_STATUS,
     b.POS_N,
     '' mark
 FROM TIT15_MAINTENANCE_RENOVATE a
 LEFT JOIN TMM22_CUSTOMERS B ON a.STORE_ID = B.CUSTCD
 LEFT JOIN TMM43_EID C ON  a.NEW_DEVICE_ID = C.EID
  LEFT JOIN TSL01_EXTEND S ON a.REQUSET_PAPER_ID = S.OPBILLID
 WHERE  a.CURRENT_STATUS = '3'

UNION ALL
 SELECT '2001' seqid, --OP_BIZ_ACCOUNT_seqno.Nextval,
      a.RENEW_ID AS BIZBILL,
      'BF' BIZTYPE,
      a.CREATE_TIME AS BIZDATE,
      a.REQUSET_PAPER_ID PLAN_NO,
      S.SLTYP,
     C.ITEMCD ITEMTYP ,
     a.OLD_DEVICE_ID EID,
     C.PRDDATE PRDDATE,
     C.MANUF_SEQ MANUF_SEQ,
     '1' ETYP,
     c.SFLG SFLG,
     c.QCFLG QCFLG,
     c.WHCD WHCD,
      (SELECT MAX(D2D_ENGINEER) FROM TIT23_MAINTENANCE_D2D WHERE MAINTENANCE_ID = A.RENEW_ID)D2D_ENGINEER,
     B.CUSTCARD CUSTCARD,
     A.STORE_ID CUSTCD,
     B.CUSTNM CUSTNM,
     b.CLASSCD,
     b.USEFLG,
     b.S_STATUS,
     b.POS_N,
     '' mark
 FROM TIT15_MAINTENANCE_RENOVATE a
 LEFT JOIN TMM22_CUSTOMERS B ON a.STORE_ID = B.CUSTCD
 LEFT JOIN TMM43_EID C ON  a.OLD_DEVICE_ID = C.EID
  LEFT JOIN TSL01_EXTEND S ON a.REQUSET_PAPER_ID = S.OPBILLID
 WHERE  a.CURRENT_STATUS = '3'
UNION ALL

--免费更换单关系业务流水账
SELECT '2000' seqid, --OP_BIZ_ACCOUNT_seqno.Nextval,
      a.RENEW_ID AS BIZBILL,
      'GH' BIZTYPE,
      a.CREATE_TIME AS BIZDATE,
      a.REQUSET_PAPER_ID PLAN_NO,
      S.SLTYP,
     C.ITEMCD ITEMTYP ,
     a.NEW_DEVICE_ID EID,
     C.PRDDATE PRDDATE,
     C.MANUF_SEQ MANUF_SEQ,
     '1' ETYP,
     '1' SFLG,
     c.QCFLG QCFLG,
     '' WHCD,
      (SELECT MAX(D2D_ENGINEER) FROM TIT23_MAINTENANCE_D2D WHERE MAINTENANCE_ID = A.RENEW_ID)D2D_ENGINEER,
     B.CUSTCARD CUSTCARD,
     A.STORE_ID CUSTCD,
     B.CUSTNM CUSTNM,
     b.CLASSCD,
     b.USEFLG,
     b.S_STATUS,
     b.POS_N,
     '旧设备号：'||OLD_DEVICE_ID||'送货单号：'||DELIVER_NO mark
 FROM TIT28_FREE_REPLACE a
 LEFT JOIN TMM22_CUSTOMERS B ON a.STORE_ID = B.CUSTCD
 LEFT JOIN TMM43_EID C ON  a.NEW_DEVICE_ID = C.EID
  LEFT JOIN TSL01_EXTEND S ON a.REQUSET_PAPER_ID = S.OPBILLID
 WHERE  a.CURRENT_STATUS = '3'

UNION ALL

SELECT '2001' seqid, --OP_BIZ_ACCOUNT_seqno.Nextval,
      a.RENEW_ID AS BIZBILL,
      'BH' BIZTYPE,
      a.CREATE_TIME AS BIZDATE,
      a.REQUSET_PAPER_ID PLAN_NO,
      S.SLTYP,
     C.ITEMCD ITEMTYP ,
     a.OLD_DEVICE_ID EID,
     C.PRDDATE PRDDATE,
     C.MANUF_SEQ MANUF_SEQ,
     '1' ETYP,
     c.SFLG SFLG,
    c.QCFLG QCFLG,
     c.WHCD WHCD,
      (SELECT MAX(D2D_ENGINEER) FROM TIT23_MAINTENANCE_D2D WHERE MAINTENANCE_ID = A.RENEW_ID)D2D_ENGINEER,
     B.CUSTCARD CUSTCARD,
     A.STORE_ID CUSTCD,
     B.CUSTNM CUSTNM,
     b.CLASSCD,
     b.USEFLG,
     b.S_STATUS,
     b.POS_N,
     '新设备号：'||NEW_DEVICE_ID||'送货单号：'||DELIVER_NO mark
 FROM TIT28_FREE_REPLACE a
 LEFT JOIN TMM22_CUSTOMERS B ON a.STORE_ID = B.CUSTCD
 LEFT JOIN TMM43_EID C ON  a.OLD_DEVICE_ID = C.EID
  LEFT JOIN TSL01_EXTEND S ON a.REQUSET_PAPER_ID = S.OPBILLID
 WHERE  a.CURRENT_STATUS = '3'


UNION ALL
--门店关闭单关系业务流水账


--门店搬迁单关系业务流水账
SELECT '2001' seqid, --OP_BIZ_ACCOUNT_seqno.Nextval,
      a.DEVICE_CHANGE_ID AS BIZBILL,
      'BQ' BIZTYPE,
      a.CREATE_TIME AS BIZDATE,
      a.REQUSET_PAPER_ID PLAN_NO,
      S.SLTYP,
     C.ITEMCD ITEMTYP ,
     d.EID EID,
     C.PRDDATE PRDDATE,
     C.MANUF_SEQ MANUF_SEQ,
     '1' ETYP,
     '1' SFLG,
     'GA' QCFLG,
     '' WHCD,
     (SELECT MAX(D2D_ENGINEER) FROM TIT23_MAINTENANCE_D2D WHERE MAINTENANCE_ID = A.DEVICE_CHANGE_ID)D2D_ENGINEER,
     B.CUSTCARD CUSTCARD,
     A.STORE_ID CUSTCD,
     B.CUSTNM CUSTNM,
     b.CLASSCD,
     b.USEFLG,
     b.S_STATUS,
     b.POS_N,
     DETAIL_DESCRIPTION mark
 FROM TIT16_DEVICE_CHANGE a
 LEFT JOIN TSL02_EXTENDDT d ON a.REQUSET_PAPER_ID = d.OPBILLID
  LEFT JOIN TSL01_EXTEND S ON a.REQUSET_PAPER_ID = S.OPBILLID
 LEFT JOIN TMM22_CUSTOMERS B ON a.STORE_ID  = b.CUSTCD
 LEFT JOIN TMM43_EID C ON  d.EID = C.EID
 WHERE  a.CURRENT_STATUS = '3'  AND a.CHANGE_TYPE = 'BQ'
UNION ALL
--磁卡号变更单关系业务流水账
SELECT '2001' seqid, --OP_BIZ_ACCOUNT_seqno.Nextval,
      a.DEVICE_CHANGE_ID AS BIZBILL,
      'CK' BIZTYPE,
      a.CREATE_TIME AS BIZDATE,
      a.REQUSET_PAPER_ID PLAN_NO,
      S.SLTYP,
     C.ITEMCD ITEMTYP ,
     d.EID EID,
     C.PRDDATE PRDDATE,
     C.MANUF_SEQ MANUF_SEQ,
     '1' ETYP,
     '1' SFLG,
     'GA' QCFLG,
     '' WHCD,
     (SELECT MAX(D2D_ENGINEER) FROM TIT23_MAINTENANCE_D2D WHERE MAINTENANCE_ID = A.DEVICE_CHANGE_ID)D2D_ENGINEER,
     B.CUSTCARD CUSTCARD,
     A.STORE_ID CUSTCD,
     B.CUSTNM CUSTNM,
     b.CLASSCD,
     b.USEFLG,
     b.S_STATUS,
     b.POS_N,
     '' mark
 FROM TIT16_DEVICE_CHANGE a
 LEFT JOIN TSL02_EXTENDDT d ON a.REQUSET_PAPER_ID = d.OPBILLID
  LEFT JOIN TSL01_EXTEND S ON a.REQUSET_PAPER_ID = S.OPBILLID
 LEFT JOIN TMM22_CUSTOMERS B ON d.NEWCUSTCD = B.CUSTCD
 LEFT JOIN TMM43_EID C ON  d.EID = C.EID
 WHERE  a.CURRENT_STATUS = '3'  AND a.CHANGE_TYPE = 'CK'
UNION ALL
--设备变更单关系业务流水账+
SELECT '2001' seqid, --OP_BIZ_ACCOUNT_seqno.Nextval,
      a.DEVICE_CHANGE_ID AS BIZBILL,
      'BG' BIZTYPE,
      a.CREATE_TIME AS BIZDATE,
      a.REQUSET_PAPER_ID PLAN_NO,
      S.SLTYP,
     C.ITEMCD ITEMTYP ,
     d.EID EID,
     C.PRDDATE PRDDATE,
     C.MANUF_SEQ MANUF_SEQ,
     '1' ETYP,
     '1' SFLG,
     'GA' QCFLG,
     '' WHCD,
     (SELECT MAX(D2D_ENGINEER) FROM TIT23_MAINTENANCE_D2D WHERE MAINTENANCE_ID = A.DEVICE_CHANGE_ID)D2D_ENGINEER,
     B.CUSTCARD CUSTCARD,
     A.STORE_ID CUSTCD,
     B.CUSTNM CUSTNM,
     b.CLASSCD,
     b.USEFLG,
     b.S_STATUS,
     b.POS_N,
     '原代码/磁卡号：'||d.CUSTCD||'/'||d.CUSTCARD||DETAIL_DESCRIPTION mark
 FROM TIT16_DEVICE_CHANGE a
 LEFT JOIN TSL02_EXTENDDT d ON a.REQUSET_PAPER_ID = d.OPBILLID
  LEFT JOIN TSL01_EXTEND S ON a.REQUSET_PAPER_ID = S.OPBILLID
 LEFT JOIN TMM22_CUSTOMERS B ON d.NEWCUSTCD = B.CUSTCD
 LEFT JOIN TMM43_EID C ON  d.EID = C.EID
 WHERE  a.CURRENT_STATUS = '3' AND a.CHANGE_TYPE = 'BG'
--质检结果单关系业务流水账 生产

/*--计划任务单关系业务流水账
SELECT '0000', --OP_BIZ_ACCOUNT_seqno.Nextval,
        a.OPBILLID AS BIZBILL,
        b.GENDATE AS BIZDATE,

   a.EID,
   a.CUSTCARD,
   a.CUSTCD,
   '' CUSTNM,
b.*
 FROM tsl02_extenddt a
LEFT JOIN TSL01_EXTEND  B ON A.OPBILLID = B.OPBILLID*/


--维护取回单关系业务流水账

