<template><div class="page"><div class="page-header"><h2>通知模板</h2><el-button type="primary" size="small" @click="openCreate">新建模板</el-button></div><el-card shadow="never"><el-table :data="items" v-loading="loading" stripe size="small" highlight-current-row @row-click="open"><el-table-column prop="template_id" label="模板ID" width="120"/><el-table-column prop="template_name" label="模板名称" min-width="140"/><el-table-column label="渠道" width="80"><template #default="{row}"><el-tag size="small">{{ row.channel }}</el-tag></template></el-table-column><el-table-column prop="subject" label="标题" min-width="150" show-overflow-tooltip/><el-table-column label="有效" width="60"><template #default="{row}"><el-tag :type="row.useflg==='1'?'success':'info'" size="small">{{ row.useflg==='1'?'是':'否' }}</el-tag></template></el-table-column><el-table-column prop="gendate" label="创建日期" width="100"/><el-table-column label="操作" width="80" fixed="right"><template #default="{row}"><el-button type="primary" link size="small" @click.stop="openEdit(row)">编辑</el-button></template></el-table-column></el-table><AppPagination v-model:current-page="page" v-model:page-size="perPage" :total="total" style="margin-top:12px;justify-content:flex-end"/></el-card><el-dialog :title="editTitle" v-model="editDrawer" width="900px" @close="onCloseEdit"><div class="tpl-editor"><div class="tpl-form"><el-form :model="form" label-width="90px" size="small"><el-form-item label="模板ID"><el-input v-model="form.template_id" :disabled="!isCreate" placeholder="如 DISPATCH"/></el-form-item><el-form-item label="模板名称"><el-input v-model="form.template_name"/></el-form-item><el-form-item label="渠道"><el-select v-model="form.channel" style="width:100%"><el-option v-for="c in channels" :key="c.channel" :label="c.label" :value="c.channel"/></el-select></el-form-item><el-form-item label="有效"><el-switch v-model="form.useflg" active-value="1" inactive-value="0"/></el-form-item><el-form-item label="标题模板"><el-input v-model="form.subject" type="textarea" :rows="2" @input="schedulePreview"/></el-form-item><el-form-item label="正文模板"><el-input v-model="form.body" type="textarea" :rows="8" @input="schedulePreview"/></el-form-item><el-form-item label="变量插入"><div class="var-buttons"><el-button v-for="v in variables" :key="v" size="small" @click="insertVar(v)">{{ v }}</el-button></div></el-form-item></el-form></div><div class="tpl-preview"><h4>实时预览</h4><div class="preview-block"><strong>标题:</strong><div class="preview-content">{{ preview.subject || '-' }}</div></div><div class="preview-block"><strong>正文:</strong><pre class="preview-content">{{ preview.body || '-' }}</pre></div><div v-if="preview.error" class="preview-error">渲染错误: {{ preview.error }}</div></div></div><template #footer><el-button @click="editDrawer=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></div></template>
<script setup lang="ts">import {ref,reactive,onMounted} from 'vue';import {ElMessage} from 'element-plus';import AppPagination from '@/components/common/AppPagination.vue';import {useListPage} from '@/composables/useListPage';import {fetchNotifTemplates,createNotifTemplate,updateNotifTemplate,previewNotifTemplate,fetchChannels} from '@/api/notification';import type {NotifRecord,ChannelInfo} from '@/api/notification'
const{items,loading,page,perPage,total,onSearch}=useListPage<NotifRecord>(fetchNotifTemplates)
const channels=ref<ChannelInfo[]>([])
const editDrawer=ref(false);const isCreate=ref(false)
onMounted(async()=>{try{const res=await fetchChannels();channels.value=res.data.channels.filter(c=>c.enabled)}catch{channels.value=[{channel:'internal',label:'站内通知',require_config:'否',enabled:true,implemented:true}]}})
const form=reactive<{template_id:string;template_name:string;channel:string;subject:string;body:string;useflg:string}>({template_id:'',template_name:'',channel:'internal',subject:'',body:'',useflg:'1'})
const preview=reactive<{subject:string;body:string;error?:string}>({subject:'',body:''})
const variables=['maintenance_id','store_id','cust_card','cust_nm','address','phone_no','accpectder','accpectder_nm','accpectd_group','fault_type']
let previewTimer:ReturnType<typeof setTimeout>|null=null
const editTitle=ref('编辑模板')
function open(){/* row-click 不打开详情，改用编辑按钮 */}
function openCreate(){isCreate.value=true;editTitle.value='新建模板';Object.assign(form,{template_id:'',template_name:'',channel:'internal',subject:'',body:'',useflg:'1'});Object.assign(preview,{subject:'',body:''});editDrawer.value=true}
function openEdit(row:NotifRecord){isCreate.value=false;editTitle.value='编辑模板 - '+row.template_id;Object.assign(form,{template_id:String(row.template_id||''),template_name:String(row.template_name||''),channel:String(row.channel||'internal'),subject:String(row.subject||''),body:String(row.body||''),useflg:String(row.useflg||'1')});schedulePreview();editDrawer.value=true}
function insertVar(v:string){form.body=form.body+`{{ ${v} }}`;schedulePreview()}
function schedulePreview(){if(previewTimer)clearTimeout(previewTimer);previewTimer=setTimeout(doPreview,400)}
async function doPreview(){try{const res=await previewNotifTemplate({subject:form.subject,body:form.body});Object.assign(preview,{subject:res.data.subject,body:res.data.body,error:res.data.error})}catch(e){Object.assign(preview,{subject:'',body:'',error:String(e)})}}
async function save(){if(!form.template_id){ElMessage.warning('请输入模板ID');return}try{const payload={template_id:form.template_id,template_name:form.template_name,channel:form.channel,subject:form.subject,body:form.body,useflg:form.useflg};if(isCreate.value){await createNotifTemplate(payload);ElMessage.success('创建成功')}else{await updateNotifTemplate(form.template_id,payload);ElMessage.success('更新成功')}editDrawer.value=false;onSearch({})}catch{ElMessage.error('保存失败')}}
function onCloseEdit(){if(previewTimer)clearTimeout(previewTimer)}
</script>
<style scoped>.page{padding:0}.page-header{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}.page-header h2{font-size:18px;font-weight:600;margin:0}.tpl-editor{display:flex;gap:16px}.tpl-form{flex:1}.tpl-preview{flex:1;border-left:1px solid #ebeef5;padding-left:16px}.var-buttons{display:flex;flex-wrap:wrap;gap:4px}.preview-block{margin-bottom:12px}.preview-content{margin-top:4px;background:#f5f7fa;padding:8px;border-radius:4px;white-space:pre-wrap;font-size:13px;min-height:24px}.preview-error{color:#f56c6c;font-size:12px;margin-top:8px}</style>
