FUNCTION UF_UPDATE_BUSINESS(IN_BILLNO     IN VARCHAR2,
                                              IN_BUSINESSID IN NUMBER,
                                              IN_OPERATOR   IN CHAR,
                                              IN_DECRIPTION IN VARCHAR2,
                                              IN_FLAG       IN CHAR)

 RETURN NUMBER AS
  V_NUM  NUMBER;
BEGIN
  BEGIN
    SELECT BUSINESS_OPERATION_ID
      INTO V_NUM
      FROM TIT20_BUSINESS_OPERATION
     WHERE BUSINESS_OPERATION_ID = IN_BUSINESSID
       AND MAINTENANCE_ID = IN_BILLNO;
  EXCEPTION
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20010,IN_BILLNO || ' 业务流水: ' ||TO_CHAR(IN_BUSINESSID) || ' 不存在!');
      RETURN - 1;
  END;

  UPDATE TIT20_BUSINESS_OPERATION
     SET OPERATE_DECRIPTION = OPERATE_DECRIPTION || IN_DECRIPTION,
         UPDATE_TIME        = SYSDATE,
         UPDATOR            = IN_OPERATOR
   WHERE BUSINESS_OPERATION_ID = IN_BUSINESSID
     AND MAINTENANCE_ID = IN_BILLNO;
  IF SQL%ROWCOUNT <> 1 OR SQL%ROWCOUNT IS NULL THEN
      RAISE_APPLICATION_ERROR(-20010,IN_BILLNO || ' 业务流水: ' ||TO_CHAR(IN_BUSINESSID) || ' 更新失败!');
      RETURN - 1;
  END IF;
  IF IN_FLAG = 'Y' THEN
    COMMIT;
  END IF;

  RETURN 1;

END UF_UPDATE_BUSINESS;
