-- ============================================================
-- 数据库表结构变更脚本 - 完整版
-- 日期：2026-04-08
-- 作者：Cascade
-- 用途：客户生命周期管理 + 资产属性扩展 + 回收任务独立化
-- 执行方式：sqlplus CCGL_MIG/CcglMig_ChangeMe_2026@CCGL_MIG @2026-04-08_complete_migration.sql
-- 前置条件：确保有ALTER TABLE和CREATE TABLE权限
-- ============================================================

SET FEEDBACK ON
SET ECHO ON

-- ============================================================
-- 第1部分：扩展 TMM22_CUSTOMERS 表（客户生命周期管理）
-- ============================================================

-- 添加客户生命周期字段
ALTER TABLE TMM22_CUSTOMERS ADD (CUSTOMER_STATUS VARCHAR2(10) DEFAULT 'ACTIVE');
ALTER TABLE TMM22_CUSTOMERS ADD (SOURCE_TYPE VARCHAR2(20));
ALTER TABLE TMM22_CUSTOMERS ADD (PREPLAN_ID VARCHAR2(20));
ALTER TABLE TMM22_CUSTOMERS ADD (VERIFIED_AT DATE);

-- 添加英文注释（避免中文编码问题）
COMMENT ON COLUMN TMM22_CUSTOMERS.CUSTOMER_STATUS IS 'Customer lifecycle status: TEMP/PENDING/ACTIVE/INVALID/BLACKLIST';
COMMENT ON COLUMN TMM22_CUSTOMERS.SOURCE_TYPE IS 'Customer source: PREPLAN/MANUAL/IMPORT/API';
COMMENT ON COLUMN TMM22_CUSTOMERS.PREPLAN_ID IS 'Associated preplan order number';
COMMENT ON COLUMN TMM22_CUSTOMERS.VERIFIED_AT IS 'Date when customer became ACTIVE';

-- 创建索引
CREATE INDEX IDX_TMM22_CUST_STATUS ON TMM22_CUSTOMERS(CUSTOMER_STATUS);
CREATE INDEX IDX_TMM22_CUST_SOURCE ON TMM22_CUSTOMERS(SOURCE_TYPE);
CREATE INDEX IDX_TMM22_CUST_PREPLAN ON TMM22_CUSTOMERS(PREPLAN_ID);

-- 初始化存量数据
UPDATE TMM22_CUSTOMERS SET CUSTOMER_STATUS = 'ACTIVE', SOURCE_TYPE = 'MANUAL' WHERE CUSTOMER_STATUS IS NULL;
COMMIT;

-- ============================================================
-- 第2部分：扩展 TMM35_CUST_POS_RL 表（资产属性管理）
-- ============================================================

-- 添加资产属性字段
ALTER TABLE TMM35_CUST_POS_RL ADD (ASSET_TYPE VARCHAR2(10));
ALTER TABLE TMM35_CUST_POS_RL ADD (RECYCLABLE_FLAG CHAR(1) DEFAULT '0');
ALTER TABLE TMM35_CUST_POS_RL ADD (RECYCLE_STATUS VARCHAR2(10));
ALTER TABLE TMM35_CUST_POS_RL ADD (CREATED_FROM VARCHAR2(20));
ALTER TABLE TMM35_CUST_POS_RL ADD (SOURCE_ID VARCHAR2(20));
ALTER TABLE TMM35_CUST_POS_RL ADD (WARRANTY_EXPIRE DATE);
ALTER TABLE TMM35_CUST_POS_RL ADD (ASSET_STATUS VARCHAR2(10));

-- 添加英文注释
COMMENT ON COLUMN TMM35_CUST_POS_RL.ASSET_TYPE IS 'Asset type: NEW/OLD/RENOVATED/SCRAP';
COMMENT ON COLUMN TMM35_CUST_POS_RL.RECYCLABLE_FLAG IS 'Recyclable flag: 1-Yes/0-No';
COMMENT ON COLUMN TMM35_CUST_POS_RL.RECYCLE_STATUS IS 'Recycle status: NONE/PENDING/ASSIGNED/IN_PROGRESS/COMPLETED/CANCELLED';
COMMENT ON COLUMN TMM35_CUST_POS_RL.CREATED_FROM IS 'Source: PLAN_CUST/MAINTENANCE/MANUAL';
COMMENT ON COLUMN TMM35_CUST_POS_RL.SOURCE_ID IS 'Source order number';
COMMENT ON COLUMN TMM35_CUST_POS_RL.WARRANTY_EXPIRE IS 'Warranty expiration date';
COMMENT ON COLUMN TMM35_CUST_POS_RL.ASSET_STATUS IS 'Asset status: ACTIVE/RETURNED/SCRAPPED';

-- 创建索引
CREATE INDEX IDX_TMM35_ASSET_TYPE ON TMM35_CUST_POS_RL(ASSET_TYPE);
CREATE INDEX IDX_TMM35_RECYCLABLE ON TMM35_CUST_POS_RL(RECYCLABLE_FLAG);
CREATE INDEX IDX_TMM35_RECYCLE_STATUS ON TMM35_CUST_POS_RL(RECYCLE_STATUS);
CREATE INDEX IDX_TMM35_CREATED_FROM ON TMM35_CUST_POS_RL(CREATED_FROM);
CREATE INDEX IDX_TMM35_ASSET_STATUS ON TMM35_CUST_POS_RL(ASSET_STATUS);

-- 初始化存量数据
UPDATE TMM35_CUST_POS_RL
SET ASSET_TYPE = 'OLD',
    RECYCLE_STATUS = 'NONE',
    RECYCLABLE_FLAG = '0',
    ASSET_STATUS = CASE USEFLG WHEN '1' THEN 'ACTIVE' ELSE 'RETURNED' END,
    CREATED_FROM = 'MANUAL'
WHERE ASSET_TYPE IS NULL;
COMMIT;

-- ============================================================
-- 第3部分：创建回收任务表
-- ============================================================

-- 创建回收任务主表
CREATE TABLE TIT20_RECYCLE_TASK (
    RECYCLE_ID VARCHAR2(20) PRIMARY KEY,
    RECYCLE_TYPE VARCHAR2(2) NOT NULL,
    PLANNO VARCHAR2(20),
    CUSTCD CHAR(8) NOT NULL,
    TASK_STATUS VARCHAR2(2) DEFAULT '00',
    ASSET_COUNT NUMBER DEFAULT 0,
    ASSET_LIST VARCHAR2(2000),
    ACTUAL_COUNT NUMBER DEFAULT 0,
    RECYCLED_ASSETS VARCHAR2(2000),
    ASSIGNED_TO CHAR(6),
    ASSIGNED_DATE DATE,
    START_DATE DATE,
    COMPLETE_DATE DATE,
    DISPOSITION VARCHAR2(2),
    TARGET_WAREHOUSE VARCHAR2(10),
    CANCEL_REASON VARCHAR2(200),
    REMARK VARCHAR2(200),
    USEFLG CHAR(1) DEFAULT '1',
    GENDATE DATE DEFAULT SYSDATE,
    UPDDATE DATE,
    OPERCD CHAR(6)
);

-- 添加英文注释
COMMENT ON TABLE TIT20_RECYCLE_TASK IS 'Recycle task master table (optimization 4)';
COMMENT ON COLUMN TIT20_RECYCLE_TASK.RECYCLE_ID IS 'Recycle task ID (R+date+seq)';
COMMENT ON COLUMN TIT20_RECYCLE_TASK.RECYCLE_TYPE IS 'Recycle type: 01-Renovate/02-Close/03-Upgrade';
COMMENT ON COLUMN TIT20_RECYCLE_TASK.PLANNO IS 'Associated preplan order number';
COMMENT ON COLUMN TIT20_RECYCLE_TASK.CUSTCD IS 'Customer code';
COMMENT ON COLUMN TIT20_RECYCLE_TASK.TASK_STATUS IS 'Task status: 00-Pending/01-Assigned/02-InProgress/03-Completed/09-Cancelled';
COMMENT ON COLUMN TIT20_RECYCLE_TASK.ASSET_COUNT IS 'Estimated asset count to recycle';
COMMENT ON COLUMN TIT20_RECYCLE_TASK.ASSET_LIST IS 'Estimated asset list (EID comma separated)';
COMMENT ON COLUMN TIT20_RECYCLE_TASK.ACTUAL_COUNT IS 'Actual recycled asset count';
COMMENT ON COLUMN TIT20_RECYCLE_TASK.RECYCLED_ASSETS IS 'Actual recycled asset list';
COMMENT ON COLUMN TIT20_RECYCLE_TASK.ASSIGNED_TO IS 'Assigned to user';
COMMENT ON COLUMN TIT20_RECYCLE_TASK.DISPOSITION IS 'Disposition: 01-Renovate/02-Scrap/03-Transfer';
COMMENT ON COLUMN TIT20_RECYCLE_TASK.TARGET_WAREHOUSE IS 'Target warehouse code';

-- 创建索引
CREATE INDEX IDX_TIT20_CUSTCD ON TIT20_RECYCLE_TASK(CUSTCD);
CREATE INDEX IDX_TIT20_PLANNO ON TIT20_RECYCLE_TASK(PLANNO);
CREATE INDEX IDX_TIT20_STATUS ON TIT20_RECYCLE_TASK(TASK_STATUS);
CREATE INDEX IDX_TIT20_TYPE ON TIT20_RECYCLE_TASK(RECYCLE_TYPE);
CREATE INDEX IDX_TIT20_ASSIGNED ON TIT20_RECYCLE_TASK(ASSIGNED_TO);

-- 创建回收任务明细表
CREATE TABLE TIT20_RECYCLE_TASK_DTL (
    RECYCLE_ID VARCHAR2(20) NOT NULL,
    ASSET_ID VARCHAR2(13) NOT NULL,
    ASSET_TYPE VARCHAR2(10),
    EXPECTED_STATUS VARCHAR2(10) DEFAULT 'NONE',
    ACTUAL_STATUS VARCHAR2(10) DEFAULT 'NONE',
    RECOVERED_DATE DATE,
    WAREHOUSE_CD VARCHAR2(10),
    REMARK VARCHAR2(200),
    PRIMARY KEY (RECYCLE_ID, ASSET_ID)
);

-- 添加英文注释
COMMENT ON TABLE TIT20_RECYCLE_TASK_DTL IS 'Recycle task detail table';
COMMENT ON COLUMN TIT20_RECYCLE_TASK_DTL.RECYCLE_ID IS 'Recycle task ID';
COMMENT ON COLUMN TIT20_RECYCLE_TASK_DTL.ASSET_ID IS 'Asset ID (EID)';
COMMENT ON COLUMN TIT20_RECYCLE_TASK_DTL.ASSET_TYPE IS 'Asset type';
COMMENT ON COLUMN TIT20_RECYCLE_TASK_DTL.EXPECTED_STATUS IS 'Expected status';
COMMENT ON COLUMN TIT20_RECYCLE_TASK_DTL.ACTUAL_STATUS IS 'Actual status: NONE/ASSIGNED/IN_PROGRESS/COMPLETED/CANCELLED';
COMMENT ON COLUMN TIT20_RECYCLE_TASK_DTL.RECOVERED_DATE IS 'Recovery completion date';
COMMENT ON COLUMN TIT20_RECYCLE_TASK_DTL.WAREHOUSE_CD IS 'Warehouse code';

-- 创建索引
CREATE INDEX IDX_TIT20DTL_ASSET ON TIT20_RECYCLE_TASK_DTL(ASSET_ID);
CREATE INDEX IDX_TIT20DTL_STATUS ON TIT20_RECYCLE_TASK_DTL(ACTUAL_STATUS);

-- ============================================================
-- 第4部分：重新编译失效触发器（重要）
-- ============================================================

ALTER TRIGGER T_TMM22_CUSTOMERS COMPILE;

-- 验证触发器状态
SELECT TRIGGER_NAME, STATUS 
FROM USER_TRIGGERS 
WHERE TABLE_NAME = 'TMM22_CUSTOMERS';

-- ============================================================
-- 完成验证
-- ============================================================

COMMIT;

-- 显示最终验证结果
SELECT 'Migration completed successfully!' AS RESULT FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') AS COMPLETION_TIME FROM DUAL;
