<template><div class="page"><div class="page-header"><h2>资产盘点</h2></div><el-card shadow="never" style="margin-bottom:16px"><div class="search-bar"><div class="field"><label>盘点单号</label><el-input v-model="s.bill" placeholder="单号" size="small" style="width:140px" clearable @keyup.enter="doSearch"/></div><div class="field"><label>客户</label><el-input v-model="s.cust" placeholder="客户编码" size="small" style="width:130px" clearable @keyup.enter="doSearch"/></div><div class="field"><label>审批状态</label><el-select v-model="s.audit" size="small" style="width:110px" clearable><el-option label="待审批" value="0"/><el-option label="审批中" value="1"/><el-option label="已审批" value="2"/></el-select></div><el-button type="primary" size="small" @click="doSearch" style="margin-left:auto">查询</el-button></div></el-card><el-card shadow="never"><el-table :data="items" v-loading="loading" stripe size="small" highlight-current-row @row-click="openDrawer"><el-table-column prop="opbillid" label="盘点单号" width="120"/><el-table-column prop="custcd" label="客户" width="90"/><el-table-column prop="itemcd" label="物料" width="90"/><el-table-column prop="slbillid" label="销售单号" width="110"/><el-table-column label="销售类型" width="80"><template #default="{row}">{{ row.sltyp || '-' }}</template></el-table-column><el-table-column label="业务类型" width="80"><template #default="{row}">{{ row.busityp || '-' }}</template></el-table-column><el-table-column label="盘点日期" width="100"><template #default="{row}">{{ row.gendate || '-' }}</template></el-table-column><el-table-column label="审批" width="70"><template #default="{row}"><el-tag :type="row.auditflg==='2'?'success':row.auditflg==='1'?'warning':'info'" size="small">{{ row.auditflg==='2'?'已审':row.auditflg==='1'?'审批中':'待审' }}</el-tag></template></el-table-column><el-table-column prop="opercd" label="操作员" width="80"/></el-table><AppPagination v-model:current-page="page" v-model:page-size="perPage" :total="total" style="margin-top:12px;justify-content:flex-end"/></el-card>
    <el-drawer v-model="drawer" title="盘点单详情" size="550px"><template v-if="detail"><el-descriptions :column="2" border size="small"><el-descriptions-item label="盘点单号">{{ detail.opbillid }}</el-descriptions-item><el-descriptions-item label="客户">{{ detail.custcd }}</el-descriptions-item><el-descriptions-item label="物料">{{ detail.itemcd }}</el-descriptions-item><el-descriptions-item label="销售单号">{{ detail.slbillid||'-' }}</el-descriptions-item><el-descriptions-item label="销售类型">{{ detail.sltyp||'-' }}</el-descriptions-item><el-descriptions-item label="业务类型">{{ detail.busityp||'-' }}</el-descriptions-item><el-descriptions-item label="盘点日期">{{ detail.gendate }}</el-descriptions-item><el-descriptions-item label="导入日期">{{ detail.impdate||'-' }}</el-descriptions-item><el-descriptions-item label="培训日期">{{ detail.traindate||'-' }}</el-descriptions-item><el-descriptions-item label="操作员">{{ detail.opercd }}</el-descriptions-item><el-descriptions-item label="审批状态"><el-tag :type="detail.auditflg==='2'?'success':'warning'" size="small">{{ detail.auditflg==='2'?'已审批':detail.auditflg==='1'?'审批中':'待审批' }}</el-tag></el-descriptions-item><el-descriptions-item label="备注" :span="2">{{ detail.backup || detail.memo || '-' }}</el-descriptions-item></el-descriptions></template></el-drawer>
  </div></template>
<script setup lang="ts">import {ref,reactive} from 'vue';import AppPagination from '@/components/common/AppPagination.vue';import {useListPage} from '@/composables/useListPage';import request from '@/api/request'
interface AssetCheck{opbillid:string;custcd:string;itemcd:string;slbillid:string;sltyp:string;busityp:string;gendate:string;impdate:string;traindate:string;auditflg:string;opercd:string;backup:string;memo:string;[key:string]:unknown}
const{items,loading,page,perPage,total,onSearch}=useListPage<AssetCheck>((p)=>request.get('/warehouse/asset-check',{params:p}))
const s=reactive({bill:'',cust:'',audit:''});const drawer=ref(false);const detail=ref<AssetCheck|null>(null)
function doSearch(){const p:Record<string,string>={};if(s.bill)p.opbillid=s.bill;if(s.cust)p.custcd=s.cust;if(s.audit)p.auditflg=s.audit;onSearch(p)}
function openDrawer(row:AssetCheck){drawer.value=true;detail.value=row}</script>
<style scoped>.page{padding:0}.page-header{display:flex;justify-content:space-between;margin-bottom:16px}.page-header h2{font-size:18px;font-weight:600;margin:0}.search-bar{display:flex;gap:12px;align-items:center}.field{display:flex;align-items:center;gap:6px}.field label{font-size:13px;color:#606266}</style>