<template><div class="page"><div class="page-header"><h2>库存查询</h2></div><el-card shadow="never" style="margin-bottom:16px"><div class="search-bar"><div class="field"><label>物料</label><el-input v-model="search.item" placeholder="编码或名称" size="small" style="width:160px" clearable/></div><div class="field"><label>仓库</label><el-select v-model="search.whcd" size="small" style="width:150px" clearable><el-option v-for="w in whOptions" :key="w.whcd" :label="w.whnm" :value="w.whcd"/></el-select></div><el-checkbox v-model="alertOnly" size="small" style="margin-left:8px;height:32px">仅看预警</el-checkbox><el-button type="primary" size="small" @click="doSearch" style="margin-left:auto">查询</el-button></div></el-card><el-card shadow="never"><el-table :data="filteredItems" v-loading="loading" stripe size="small" :row-class-name="rowClassName"><el-table-column prop="itemcd" label="物料编码" width="100"/><el-table-column prop="item_nm" label="物料名称" min-width="140" show-overflow-tooltip/><el-table-column label="仓库" width="120"><template #default="{row}">{{ row.whnm || row.whcd }}</template></el-table-column><el-table-column label="库存数量" width="100" align="right"><template #default="{row}"><span :style="{color: isLow(row) ? '#f56c6c' : '', fontWeight: isLow(row) ? 'bold' : ''}">{{ row.itemqty }}</span></template></el-table-column><el-table-column label="库存上限" width="90" align="right"><template #default="{row}">{{ row.upperlimit ?? '-' }}</template></el-table-column><el-table-column label="库存下限" width="90" align="right"><template #default="{row}">{{ row.lowerlimit ?? '-' }}</template></el-table-column><el-table-column label="状态" width="80" align="center"><template #default="{row}"><el-tag v-if="isLow(row)" type="danger" size="small">低于下限</el-tag><el-tag v-else-if="isHigh(row)" type="warning" size="small">超上限</el-tag><el-tag v-else type="success" size="small">正常</el-tag></template></el-table-column></el-table><AppPagination v-model:current-page="page" v-model:page-size="perPage" :total="total" style="margin-top:12px;justify-content:flex-end"/></el-card></div></template>
<script setup lang="ts">import {ref,reactive,computed,onMounted} from 'vue';import AppPagination from '@/components/common/AppPagination.vue';import {useListPage} from '@/composables/useListPage';import {fetchStock,fetchWarehouses,type StockItem} from '@/api/warehouse'
const{items,loading,page,perPage,total,onSearch}=useListPage<StockItem>(fetchStock)
const search=reactive({item:'',whcd:''});const alertOnly=ref(false);const whOptions=ref<{whcd:string;whnm:string}[]>([])
onMounted(async()=>{try{const r=await fetchWarehouses();whOptions.value=r.data||[]}catch{}})
function isLow(row:any){return row.lowerlimit!=null&&(row.itemqty||0)<row.lowerlimit}
function isHigh(row:any){return row.upperlimit!=null&&(row.itemqty||0)>row.upperlimit}
function rowClassName({row}:any){return isLow(row)?'row-low':isHigh(row)?'row-high':''}
const filteredItems=computed(()=>alertOnly.value?items.value.filter((row:any)=>isLow(row)):items.value)
function doSearch(){const p:Record<string,string>={};if(search.item)p.search=search.item;if(search.whcd)p.whcd=search.whcd;onSearch(p)}</script>
<style scoped>.page{padding:0}.page-header{display:flex;justify-content:space-between;margin-bottom:16px}.page-header h2{font-size:18px;font-weight:600;margin:0}.search-bar{display:flex;gap:12px;align-items:center}.field{display:flex;align-items:center;gap:6px}.field label{font-size:13px;color:#606266}:global(.row-low){background-color:#fef0f0!important}:global(.row-high){background-color:#fdf6ec!important}</style>
