"""B3: add itemcd/fault_cd to tit25_accessories_update

Revision ID: 00d946c2e6b2
Revises: b3c4d5e6f7a8
Create Date: 2026-07-22 10:52:45.842264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '00d946c2e6b2'
down_revision = 'b3c4d5e6f7a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tit10_maintenanceday_bak_requst_typ')
    with op.batch_alter_table('plan_cust', schema=None) as batch_op:
        batch_op.alter_column('plantyp',
               existing_type=sa.VARCHAR(length=2),
               comment='计划类型（00新机开通/10磁卡号变更/20旧机翻新/30取机回收/40门店关闭）',
               existing_comment='计划类型（00新机开通/10设备变更/20旧机翻新/30设备取回/40门店关闭）',
               existing_nullable=True)
        batch_op.alter_column('is_outflag',
               existing_type=sa.VARCHAR(length=4),
               comment='出库标志三态（N/A=非商用仓库不适用/0=待出库/1=OV=1出库单已审核）',
               existing_comment='出库标志（1=已生成OV=1出库单）',
               existing_nullable=True)
        batch_op.alter_column('serve_ercd',
               existing_type=sa.VARCHAR(length=6),
               comment='分配呼出人/服务工程师（对齐 PB d_serve_list）',
               existing_comment='服务工程师',
               existing_nullable=True)

    with op.batch_alter_table('tit21_maintenance_dispatch', schema=None) as batch_op:
        batch_op.alter_column('maintenance_type',
               existing_type=sa.VARCHAR(length=2),
               comment='维护类型（PB未使用，重构已废弃，保留历史兼容）',
               existing_comment='维护类型',
               existing_nullable=True)

    with op.batch_alter_table('tit23_maintenance_d2d', schema=None) as batch_op:
        batch_op.alter_column('jjbz',
               existing_type=sa.VARCHAR(length=1),
               comment='解决标志（已废弃，保留 PB 数据迁移兼容，新数据用 d2d_result）',
               existing_comment='解决标志',
               existing_nullable=True)
        batch_op.alter_column('d2d_descripiton',
               existing_type=sa.VARCHAR(length=200),
               comment='处理过程描述（保留 PB 兼容，离店保存时由后端自动拼句双写）',
               existing_comment='处理过程描述',
               existing_nullable=True)
        batch_op.alter_column('closure_reason',
               existing_type=sa.VARCHAR(length=1),
               comment='关闭原因（仅 d2d_result=3 时填，CLO_REASON 字典）',
               existing_comment='关闭原因（仅 d2d_result=3 时填，CLOSURE_REASON 字典）',
               existing_nullable=True)

    with op.batch_alter_table('tit25_accessories_update', schema=None) as batch_op:
        batch_op.add_column(sa.Column('itemcd', sa.String(length=13), nullable=True, comment='配件物料编码（B3：关联故障代码用）'))
        batch_op.add_column(sa.Column('fault_cd', sa.String(length=8), nullable=True, comment='故障代码（B3：配件更换时自动关联）'))
        batch_op.alter_column('c_type',
               existing_type=sa.VARCHAR(length=1),
               comment='操作类型（C_TYPE 字典：1维修/2购买/3纯服务费/4整机更换/5耗材线材）',
               existing_comment='操作类型（1维修/2购买）',
               existing_nullable=True)
        batch_op.alter_column('paytype',
               existing_type=sa.VARCHAR(length=20),
               comment='收费类型（c_type=3 用 PAY_SVC 字典，c_type=5 用 PAY_CONS 字典）',
               existing_comment='收费类型（c_type=3 用 PAY_SVC 字典，c_type=5 用 PAYTYPE_CONSUMABLE 字典）',
               existing_nullable=True)

    with op.batch_alter_table('tit30_dispatch_rule', schema=None) as batch_op:
        batch_op.alter_column('fault_type',
               existing_type=sa.VARCHAR(length=2),
               comment='故障类型（GZ字典，空=全匹配）',
               existing_comment='故障类型',
               existing_nullable=True)
        batch_op.alter_column('store_id',
               existing_type=sa.VARCHAR(length=8),
               comment='门店编码（可选，定向派单）',
               existing_comment='门店编码',
               existing_nullable=True)
        batch_op.alter_column('target_type',
               existing_type=sa.VARCHAR(length=20),
               comment='派单目标: area_manager/group_leader/load_balance/manual',
               existing_comment='派单目标: area_manager/group_leader/manual',
               existing_nullable=True)
        batch_op.alter_column('target_value',
               existing_type=sa.VARCHAR(length=20),
               comment='目标值（group_leader/load_balance 时=组编码）',
               existing_comment='目标值',
               existing_nullable=True)
        batch_op.alter_column('auto_dispatch',
               existing_type=sa.VARCHAR(length=1),
               comment='自动派单开关: 1=启用/0=禁用',
               existing_nullable=True,
               existing_server_default=sa.text("'1'::character varying"))
        batch_op.alter_column('notify_channel',
               existing_type=sa.VARCHAR(length=10),
               comment='自动派工通知渠道: internal/email/sms/dingtalk/wecom/feishu/ntfy',
               existing_nullable=True,
               existing_server_default=sa.text("'internal'::character varying"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_table_comment(
        existing_comment='派单规则表'
    )

    with op.batch_alter_table('tmc12_groups', schema=None) as batch_op:
        batch_op.alter_column('leader_cd',
               existing_type=sa.VARCHAR(length=6),
               comment='组长用户编码（tmc13_users.user_cd）',
               existing_comment='组长用户编码',
               existing_nullable=True)

    with op.batch_alter_table('tmm02_country', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='老系统自定义国家码表（保留不动，新业务使用geo_*系列表）'
    )

    with op.batch_alter_table('tmm03_province', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='老系统自定义省份码表（含港澳台34条，新业务使用geo_province）'
    )

    with op.batch_alter_table('tmm04_city', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='老系统自定义区级码表（实为区级非地级市，含已撤销区划，新业务使用geo_area）'
    )

    with op.batch_alter_table('tmm05_town', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='老系统区县码表（迁移后tmm22_customers.town_cd全为空，实际未使用，新业务使用geo_street）'
    )

    with op.batch_alter_table('tmm22_customers', schema=None) as batch_op:
        batch_op.alter_column('country_cd',
               existing_type=sa.VARCHAR(length=3),
               comment='【废弃】国家代码（老系统自定义短码，如191=中国），由geo_prvn_cd等替代，待删除',
               existing_comment='【废弃】老系统自定义国家码（191=中国），由geo_prvn_cd等替代，待删除',
               existing_nullable=True)
        batch_op.alter_column('prvn_cd',
               existing_type=sa.VARCHAR(length=2),
               comment='【废弃】省份代码（老系统自定义短码，如09=上海），由geo_prvn_cd替代，待删除',
               existing_comment='【废弃】老系统自定义省份码（09=上海），由geo_prvn_cd替代，待删除',
               existing_nullable=True)
        batch_op.alter_column('city_cd',
               existing_type=sa.VARCHAR(length=4),
               comment='【废弃】城市/区代码（老系统自定义短码，如0121=浦东新区），由geo_city_cd/geo_area_cd替代，待删除',
               existing_comment='【废弃】老系统自定义区级码（如0121=浦东新区），已回填至geo_area_cd，待删除',
               existing_nullable=True)
        batch_op.alter_column('town_cd',
               existing_type=sa.VARCHAR(length=4),
               comment='【废弃】区县代码（老系统自定义短码，迁移后全为空），由geo_area_cd替代，待删除',
               existing_comment='【废弃】老系统区县码，迁移后全为空，由geo_area_cd替代，待删除',
               existing_nullable=True)
        batch_op.alter_column('geo_prvn_cd',
               existing_type=sa.VARCHAR(length=6),
               comment='国标省级代码（关联geo_province.code，如31=上海市）',
               existing_comment='国标省级代码（关联geo_province.code，如31=上海市，已回填11020条）',
               existing_nullable=True)
        batch_op.alter_column('geo_city_cd',
               existing_type=sa.VARCHAR(length=6),
               comment='国标地级市代码（关联geo_city.code，如3101=上海市辖区）',
               existing_comment='国标地级市代码（关联geo_city.code，如3101=上海市辖区，已回填11020条）',
               existing_nullable=True)
        batch_op.alter_column('geo_area_cd',
               existing_type=sa.VARCHAR(length=6),
               comment='国标区县代码（关联geo_area.code，如310101=黄浦区）',
               existing_comment='国标区县代码（关联geo_area.code，如310101=黄浦区，已回填11020条）',
               existing_nullable=True)
        batch_op.alter_column('geo_street_cd',
               existing_type=sa.VARCHAR(length=12),
               comment='国标街道代码（关联geo_street.code，如310101002=南京东路街道）',
               existing_comment='国标街道代码（关联geo_street.code，如310101002=南京东路街道，新录入时通过前端四级联动填入）',
               existing_nullable=True)

    with op.batch_alter_table('tntf01_template', schema=None) as batch_op:
        batch_op.alter_column('ref_type',
               existing_type=sa.VARCHAR(length=20),
               comment='业务类型: dispatch(派工通知)/maintenance(工单通知)',
               existing_nullable=True)
        batch_op.alter_column('is_default',
               existing_type=sa.VARCHAR(length=1),
               comment='是否该 ref_type 下默认: 1=是/0=否',
               existing_nullable=True,
               existing_server_default=sa.text("'0'::character varying"))
        batch_op.alter_column('sort_no',
               existing_type=sa.INTEGER(),
               comment='排序号（小优先）',
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('tntf02_notification', schema=None) as batch_op:
        batch_op.alter_column('ref_id',
               existing_type=sa.VARCHAR(length=20),
               comment='关联业务ID（维护单号等）',
               existing_comment='关联业务ID',
               existing_nullable=True)
        batch_op.alter_column('dispatch_id',
               existing_type=sa.INTEGER(),
               comment='关联派工记录ID（tit21_maintenance_dispatch.id，区分同一工单多次派工）',
               existing_nullable=True)
        batch_op.alter_column('read_status',
               existing_type=sa.VARCHAR(length=10),
               comment='已读状态: unread/read（站内通知专用）',
               existing_nullable=True,
               existing_server_default=sa.text("'unread'::character varying"))
        batch_op.alter_column('read_time',
               existing_type=postgresql.TIMESTAMP(),
               comment='已读时间（站内通知专用）',
               existing_nullable=True)

    with op.batch_alter_table('twh16_outdteid', schema=None) as batch_op:
        batch_op.alter_column('ref_planno',
               existing_type=sa.VARCHAR(length=12),
               comment='来源预计划号（批量出库方案B：明细行记来源预计划）',
               existing_comment='来源预计划号（批量出库方案B）',
               existing_nullable=True)

    with op.batch_alter_table('twh16_outdtprd', schema=None) as batch_op:
        batch_op.alter_column('ref_planno',
               existing_type=sa.VARCHAR(length=12),
               comment='来源预计划号（批量出库方案B：明细行记来源预计划）',
               existing_comment='来源预计划号（批量出库方案B）',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('twh16_outdtprd', schema=None) as batch_op:
        batch_op.alter_column('ref_planno',
               existing_type=sa.VARCHAR(length=12),
               comment='来源预计划号（批量出库方案B）',
               existing_comment='来源预计划号（批量出库方案B：明细行记来源预计划）',
               existing_nullable=True)

    with op.batch_alter_table('twh16_outdteid', schema=None) as batch_op:
        batch_op.alter_column('ref_planno',
               existing_type=sa.VARCHAR(length=12),
               comment='来源预计划号（批量出库方案B）',
               existing_comment='来源预计划号（批量出库方案B：明细行记来源预计划）',
               existing_nullable=True)

    with op.batch_alter_table('tntf02_notification', schema=None) as batch_op:
        batch_op.alter_column('read_time',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='已读时间（站内通知专用）',
               existing_nullable=True)
        batch_op.alter_column('read_status',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='已读状态: unread/read（站内通知专用）',
               existing_nullable=True,
               existing_server_default=sa.text("'unread'::character varying"))
        batch_op.alter_column('dispatch_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='关联派工记录ID（tit21_maintenance_dispatch.id，区分同一工单多次派工）',
               existing_nullable=True)
        batch_op.alter_column('ref_id',
               existing_type=sa.VARCHAR(length=20),
               comment='关联业务ID',
               existing_comment='关联业务ID（维护单号等）',
               existing_nullable=True)

    with op.batch_alter_table('tntf01_template', schema=None) as batch_op:
        batch_op.alter_column('sort_no',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='排序号（小优先）',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_default',
               existing_type=sa.VARCHAR(length=1),
               comment=None,
               existing_comment='是否该 ref_type 下默认: 1=是/0=否',
               existing_nullable=True,
               existing_server_default=sa.text("'0'::character varying"))
        batch_op.alter_column('ref_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='业务类型: dispatch(派工通知)/maintenance(工单通知)',
               existing_nullable=True)

    with op.batch_alter_table('tmm22_customers', schema=None) as batch_op:
        batch_op.alter_column('geo_street_cd',
               existing_type=sa.VARCHAR(length=12),
               comment='国标街道代码（关联geo_street.code，如310101002=南京东路街道，新录入时通过前端四级联动填入）',
               existing_comment='国标街道代码（关联geo_street.code，如310101002=南京东路街道）',
               existing_nullable=True)
        batch_op.alter_column('geo_area_cd',
               existing_type=sa.VARCHAR(length=6),
               comment='国标区县代码（关联geo_area.code，如310101=黄浦区，已回填11020条）',
               existing_comment='国标区县代码（关联geo_area.code，如310101=黄浦区）',
               existing_nullable=True)
        batch_op.alter_column('geo_city_cd',
               existing_type=sa.VARCHAR(length=6),
               comment='国标地级市代码（关联geo_city.code，如3101=上海市辖区，已回填11020条）',
               existing_comment='国标地级市代码（关联geo_city.code，如3101=上海市辖区）',
               existing_nullable=True)
        batch_op.alter_column('geo_prvn_cd',
               existing_type=sa.VARCHAR(length=6),
               comment='国标省级代码（关联geo_province.code，如31=上海市，已回填11020条）',
               existing_comment='国标省级代码（关联geo_province.code，如31=上海市）',
               existing_nullable=True)
        batch_op.alter_column('town_cd',
               existing_type=sa.VARCHAR(length=4),
               comment='【废弃】老系统区县码，迁移后全为空，由geo_area_cd替代，待删除',
               existing_comment='【废弃】区县代码（老系统自定义短码，迁移后全为空），由geo_area_cd替代，待删除',
               existing_nullable=True)
        batch_op.alter_column('city_cd',
               existing_type=sa.VARCHAR(length=4),
               comment='【废弃】老系统自定义区级码（如0121=浦东新区），已回填至geo_area_cd，待删除',
               existing_comment='【废弃】城市/区代码（老系统自定义短码，如0121=浦东新区），由geo_city_cd/geo_area_cd替代，待删除',
               existing_nullable=True)
        batch_op.alter_column('prvn_cd',
               existing_type=sa.VARCHAR(length=2),
               comment='【废弃】老系统自定义省份码（09=上海），由geo_prvn_cd替代，待删除',
               existing_comment='【废弃】省份代码（老系统自定义短码，如09=上海），由geo_prvn_cd替代，待删除',
               existing_nullable=True)
        batch_op.alter_column('country_cd',
               existing_type=sa.VARCHAR(length=3),
               comment='【废弃】老系统自定义国家码（191=中国），由geo_prvn_cd等替代，待删除',
               existing_comment='【废弃】国家代码（老系统自定义短码，如191=中国），由geo_prvn_cd等替代，待删除',
               existing_nullable=True)

    with op.batch_alter_table('tmm05_town', schema=None) as batch_op:
        batch_op.create_table_comment(
        '老系统区县码表（迁移后tmm22_customers.town_cd全为空，实际未使用，新业务使用geo_street）',
        existing_comment=None
    )

    with op.batch_alter_table('tmm04_city', schema=None) as batch_op:
        batch_op.create_table_comment(
        '老系统自定义区级码表（实为区级非地级市，含已撤销区划，新业务使用geo_area）',
        existing_comment=None
    )

    with op.batch_alter_table('tmm03_province', schema=None) as batch_op:
        batch_op.create_table_comment(
        '老系统自定义省份码表（含港澳台34条，新业务使用geo_province）',
        existing_comment=None
    )

    with op.batch_alter_table('tmm02_country', schema=None) as batch_op:
        batch_op.create_table_comment(
        '老系统自定义国家码表（保留不动，新业务使用geo_*系列表）',
        existing_comment=None
    )

    with op.batch_alter_table('tmc12_groups', schema=None) as batch_op:
        batch_op.alter_column('leader_cd',
               existing_type=sa.VARCHAR(length=6),
               comment='组长用户编码',
               existing_comment='组长用户编码（tmc13_users.user_cd）',
               existing_nullable=True)

    with op.batch_alter_table('tit30_dispatch_rule', schema=None) as batch_op:
        batch_op.create_table_comment(
        '派单规则表',
        existing_comment=None
    )
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('notify_channel',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='自动派工通知渠道: internal/email/sms/dingtalk/wecom/feishu/ntfy',
               existing_nullable=True,
               existing_server_default=sa.text("'internal'::character varying"))
        batch_op.alter_column('auto_dispatch',
               existing_type=sa.VARCHAR(length=1),
               comment=None,
               existing_comment='自动派单开关: 1=启用/0=禁用',
               existing_nullable=True,
               existing_server_default=sa.text("'1'::character varying"))
        batch_op.alter_column('target_value',
               existing_type=sa.VARCHAR(length=20),
               comment='目标值',
               existing_comment='目标值（group_leader/load_balance 时=组编码）',
               existing_nullable=True)
        batch_op.alter_column('target_type',
               existing_type=sa.VARCHAR(length=20),
               comment='派单目标: area_manager/group_leader/manual',
               existing_comment='派单目标: area_manager/group_leader/load_balance/manual',
               existing_nullable=True)
        batch_op.alter_column('store_id',
               existing_type=sa.VARCHAR(length=8),
               comment='门店编码',
               existing_comment='门店编码（可选，定向派单）',
               existing_nullable=True)
        batch_op.alter_column('fault_type',
               existing_type=sa.VARCHAR(length=2),
               comment='故障类型',
               existing_comment='故障类型（GZ字典，空=全匹配）',
               existing_nullable=True)

    with op.batch_alter_table('tit25_accessories_update', schema=None) as batch_op:
        batch_op.alter_column('paytype',
               existing_type=sa.VARCHAR(length=20),
               comment='收费类型（c_type=3 用 PAY_SVC 字典，c_type=5 用 PAYTYPE_CONSUMABLE 字典）',
               existing_comment='收费类型（c_type=3 用 PAY_SVC 字典，c_type=5 用 PAY_CONS 字典）',
               existing_nullable=True)
        batch_op.alter_column('c_type',
               existing_type=sa.VARCHAR(length=1),
               comment='操作类型（1维修/2购买）',
               existing_comment='操作类型（C_TYPE 字典：1维修/2购买/3纯服务费/4整机更换/5耗材线材）',
               existing_nullable=True)
        batch_op.drop_column('fault_cd')
        batch_op.drop_column('itemcd')

    with op.batch_alter_table('tit23_maintenance_d2d', schema=None) as batch_op:
        batch_op.alter_column('closure_reason',
               existing_type=sa.VARCHAR(length=1),
               comment='关闭原因（仅 d2d_result=3 时填，CLOSURE_REASON 字典）',
               existing_comment='关闭原因（仅 d2d_result=3 时填，CLO_REASON 字典）',
               existing_nullable=True)
        batch_op.alter_column('d2d_descripiton',
               existing_type=sa.VARCHAR(length=200),
               comment='处理过程描述',
               existing_comment='处理过程描述（保留 PB 兼容，离店保存时由后端自动拼句双写）',
               existing_nullable=True)
        batch_op.alter_column('jjbz',
               existing_type=sa.VARCHAR(length=1),
               comment='解决标志',
               existing_comment='解决标志（已废弃，保留 PB 数据迁移兼容，新数据用 d2d_result）',
               existing_nullable=True)

    with op.batch_alter_table('tit21_maintenance_dispatch', schema=None) as batch_op:
        batch_op.alter_column('maintenance_type',
               existing_type=sa.VARCHAR(length=2),
               comment='维护类型',
               existing_comment='维护类型（PB未使用，重构已废弃，保留历史兼容）',
               existing_nullable=True)

    with op.batch_alter_table('plan_cust', schema=None) as batch_op:
        batch_op.alter_column('serve_ercd',
               existing_type=sa.VARCHAR(length=6),
               comment='服务工程师',
               existing_comment='分配呼出人/服务工程师（对齐 PB d_serve_list）',
               existing_nullable=True)
        batch_op.alter_column('is_outflag',
               existing_type=sa.VARCHAR(length=4),
               comment='出库标志（1=已生成OV=1出库单）',
               existing_comment='出库标志三态（N/A=非商用仓库不适用/0=待出库/1=OV=1出库单已审核）',
               existing_nullable=True)
        batch_op.alter_column('plantyp',
               existing_type=sa.VARCHAR(length=2),
               comment='计划类型（00新机开通/10设备变更/20旧机翻新/30设备取回/40门店关闭）',
               existing_comment='计划类型（00新机开通/10磁卡号变更/20旧机翻新/30取机回收/40门店关闭）',
               existing_nullable=True)

    op.create_table('tit10_maintenanceday_bak_requst_typ',
    sa.Column('maintenance_id', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('requst_typ', sa.VARCHAR(length=10), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
