"""add item_cd to deposit_posmodel

Revision ID: 283de401b181
Revises: 10cc9a90342b
Create Date: 2026-06-28 10:32:51.055364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '283de401b181'
down_revision = '10cc9a90342b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_cust', schema=None) as batch_op:
        batch_op.alter_column('pos_item',
               existing_type=sa.VARCHAR(length=6),
               comment='机型编码（00新开店=目标机型；20/30/40=旧设备机型，随旧设备ID自动带出）',
               existing_comment='目标机型（新开店要安装的整机型号）',
               existing_nullable=True)
        batch_op.alter_column('posid',
               existing_type=sa.VARCHAR(length=13),
               comment='设备EID（00新开店=目标设备EID；20/30/40=旧设备EID，关联计划门店名下有效成品资产）',
               existing_comment='目标设备EID',
               existing_nullable=True)
        batch_op.alter_column('solve_type',
               existing_type=sa.VARCHAR(length=2),
               comment='旧机处理方式（PB字典：20翻新/30取回/40关门场景使用）',
               existing_comment='旧机处理方式（翻新场景）',
               existing_nullable=True)
        batch_op.alter_column('cust_useflg',
               existing_type=sa.VARCHAR(length=2),
               comment='客户无效化（00(01/02)移机/20(01-04)翻新/30取回/40关门时勾选，使源门店或计划门店useflg=0）',
               existing_comment='源门店无效化（移机/取机时勾选使源门店useflg=0）',
               existing_nullable=True)

    with op.batch_alter_table('tit16_device_change', schema=None) as batch_op:
        batch_op.alter_column('change_type',
               existing_type=sa.VARCHAR(length=8),
               comment='变更类型（CK=仅磁卡号/BQ=信息变更/BG=磁卡号+设备）',
               existing_comment='变更类型（CK/BQ/BG）',
               existing_nullable=True)

    with op.batch_alter_table('tmm61_deposit_posmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_cd', sa.String(length=20), nullable=True, comment='关联成品物料编码(tmm12_items.item_cd),用于 BOM 展开与库存查询'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tmm61_deposit_posmodel', schema=None) as batch_op:
        batch_op.drop_column('item_cd')

    with op.batch_alter_table('tit16_device_change', schema=None) as batch_op:
        batch_op.alter_column('change_type',
               existing_type=sa.VARCHAR(length=8),
               comment='变更类型（CK/BQ/BG）',
               existing_comment='变更类型（CK=仅磁卡号/BQ=信息变更/BG=磁卡号+设备）',
               existing_nullable=True)

    with op.batch_alter_table('plan_cust', schema=None) as batch_op:
        batch_op.alter_column('cust_useflg',
               existing_type=sa.VARCHAR(length=2),
               comment='源门店无效化（移机/取机时勾选使源门店useflg=0）',
               existing_comment='客户无效化（00(01/02)移机/20(01-04)翻新/30取回/40关门时勾选，使源门店或计划门店useflg=0）',
               existing_nullable=True)
        batch_op.alter_column('solve_type',
               existing_type=sa.VARCHAR(length=2),
               comment='旧机处理方式（翻新场景）',
               existing_comment='旧机处理方式（PB字典：20翻新/30取回/40关门场景使用）',
               existing_nullable=True)
        batch_op.alter_column('posid',
               existing_type=sa.VARCHAR(length=13),
               comment='目标设备EID',
               existing_comment='设备EID（00新开店=目标设备EID；20/30/40=旧设备EID，关联计划门店名下有效成品资产）',
               existing_nullable=True)
        batch_op.alter_column('pos_item',
               existing_type=sa.VARCHAR(length=6),
               comment='目标机型（新开店要安装的整机型号）',
               existing_comment='机型编码（00新开店=目标机型；20/30/40=旧设备机型，随旧设备ID自动带出）',
               existing_nullable=True)

    # ### end Alembic commands ###
