"""add batch_no fields to replace_record

Revision ID: 3a45f7e78bab
Revises: 20260612_tms05
Create Date: 2026-06-13 11:45:48.746332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a45f7e78bab'
down_revision = '20260612_tms05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twh15_out_backup_20260602')
    op.drop_table('twh13_in_backup_20260602')
    op.drop_table('backup_tpc20_20260523')
    with op.batch_alter_table('tip02_supplier_price', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_supplier_price_item'), type_='foreignkey')

    with op.batch_alter_table('tmm24_custitems', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_custitems_item'), type_='foreignkey')

    with op.batch_alter_table('tmm35_cust_pos_rl', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_cust_pos_rl_eid_useflg'))

    with op.batch_alter_table('tmm40_label', schema=None) as batch_op:
        batch_op.alter_column('labelid',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=13),
               comment='标签号（即激活后的EID）',
               existing_comment='标签ID',
               existing_nullable=False)
        batch_op.alter_column('classcd',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=6),
               nullable=False,
               comment='物料中类编码',
               existing_comment='分类编码')
        batch_op.alter_column('useflg',
               existing_type=sa.VARCHAR(length=1),
               comment='有效标志：1=未激活，0=已激活',
               existing_comment='有效标志',
               existing_nullable=True,
               existing_server_default=sa.text("'1'::character varying"))

    with op.batch_alter_table('tmm41_bom', schema=None) as batch_op:
        batch_op.alter_column('bomcd',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=6),
               existing_comment='BOM编码',
               existing_nullable=False)

    with op.batch_alter_table('tmm42_bomdt', schema=None) as batch_op:
        batch_op.alter_column('bomcd',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=6),
               existing_comment='BOM编码',
               existing_nullable=False)

    with op.batch_alter_table('tmm43_eid', schema=None) as batch_op:
        batch_op.alter_column('ref_eid',
               existing_type=sa.VARCHAR(length=13),
               comment='溯源旧EID（翻新时记录来源）',
               existing_comment='来源EID（翻新溯源链）',
               existing_nullable=True)

    with op.batch_alter_table('tmm43_eid_track', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_eid_track_eid_itemcd'))
        batch_op.drop_index(batch_op.f('idx_eid_track_type_eid'))

    with op.batch_alter_table('tmm44_pos_r_eid', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_pos_r_eid_eid'))
        batch_op.drop_index(batch_op.f('idx_pos_r_eid_useflg'))

    with op.batch_alter_table('tms01_work_order', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态（DRAFT/RELEASED/PICKING/IN_PROGRESS/QC_PENDING/COMPLETED/CANCELLED）',
               existing_comment='状态（DRAFT/RELEASED/IN_PROGRESS/COMPLETED/CANCELLED）',
               existing_nullable=True)
        batch_op.alter_column('wo_type',
               existing_type=sa.VARCHAR(length=10),
               comment='工单类型: PRODUCTION=生产 RENOVATION=翻新',
               existing_nullable=True,
               existing_server_default=sa.text("'PRODUCTION'::character varying"))
        batch_op.alter_column('warehouse_cd',
               existing_type=sa.VARCHAR(length=20),
               comment='成品入库仓库',
               existing_comment='目标仓库',
               existing_nullable=True)
        batch_op.alter_column('pick_whcd',
               existing_type=sa.VARCHAR(length=20),
               comment='领料出库仓库',
               existing_nullable=True)

    with op.batch_alter_table('tms05_replace_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_batch_no', sa.String(length=20), nullable=True, comment='旧批次号（批次物料使用）'))
        batch_op.add_column(sa.Column('new_batch_no', sa.String(length=20), nullable=True, comment='新批次号（批次物料使用）'))
        batch_op.alter_column('old_eid',
               existing_type=sa.VARCHAR(length=20),
               comment='旧物料序列号（批次物料可为空）',
               existing_comment='旧物料序列号',
               existing_nullable=True)
        batch_op.alter_column('new_eid',
               existing_type=sa.VARCHAR(length=20),
               comment='新物料序列号（批次物料可为空，FQC合格后生成）',
               existing_comment='新物料序列号',
               existing_nullable=True)
        batch_op.alter_column('itemcd',
               existing_type=sa.VARCHAR(length=12),
               nullable=False,
               existing_comment='物料编码')
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_tms05_wo'))

    with op.batch_alter_table('tpc02_pcplandt', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_pcplandt_item'), type_='foreignkey')

    with op.batch_alter_table('tpc03_pcplanstatus', schema=None) as batch_op:
        batch_op.alter_column('refbillid',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=8),
               existing_comment='关联单号',
               existing_nullable=True)

    with op.batch_alter_table('tpc13_registerdt', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_tpc13_registerdt_bill_line'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_registerdt_item'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('tpc13_registerdt_rgstbillid_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tpc12_register', ['rgstbillid'], ['rgstbillid'])

    with op.batch_alter_table('tpc14_pcbill', schema=None) as batch_op:
        batch_op.alter_column('pcbillid',
               existing_type=sa.VARCHAR(length=8),
               comment='结算单号',
               existing_comment='采购单号',
               existing_nullable=False)
        batch_op.alter_column('ref_rgstbillid',
               existing_type=sa.VARCHAR(length=8),
               comment='来源采购订单（月结置空）',
               existing_nullable=True)
        batch_op.alter_column('suppliercd',
               existing_type=sa.VARCHAR(length=8),
               comment='供应商编码',
               existing_comment='客户编码',
               existing_nullable=True)
        batch_op.alter_column('pay_type',
               existing_type=sa.VARCHAR(length=3),
               comment='付款方式',
               existing_nullable=True,
               existing_server_default=sa.text("'COD'::character varying"))
        batch_op.alter_column('invoice_no',
               existing_type=sa.VARCHAR(length=50),
               comment='发票号码',
               existing_nullable=True)
        batch_op.alter_column('invoice_date',
               existing_type=sa.DATE(),
               comment='发票日期',
               existing_nullable=True)
        batch_op.alter_column('pcdate',
               existing_type=postgresql.TIMESTAMP(),
               comment='结算日期',
               existing_comment='采购日期',
               existing_nullable=True)
        batch_op.alter_column('total_settle_amt',
               existing_type=sa.NUMERIC(precision=16, scale=4),
               comment='结算总额',
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
        batch_op.alter_column('whcd',
               existing_type=sa.VARCHAR(length=50),
               comment='入库仓库（多选逗号分隔）',
               existing_comment='入库仓库',
               existing_nullable=True)
        batch_op.alter_column('auditflg',
               existing_type=sa.VARCHAR(length=1),
               comment='审核标志',
               existing_nullable=True,
               existing_server_default=sa.text("'0'::character varying"))
        batch_op.alter_column('auditman',
               existing_type=sa.VARCHAR(length=6),
               comment='审核人',
               existing_nullable=True)
        batch_op.alter_column('auditdate',
               existing_type=postgresql.TIMESTAMP(),
               comment='审核日期',
               existing_nullable=True)

    with op.batch_alter_table('tpc14_pcbilldt', schema=None) as batch_op:
        batch_op.alter_column('pcbillid',
               existing_type=sa.VARCHAR(length=8),
               comment='结算单号',
               existing_nullable=False)
        batch_op.alter_column('lineno',
               existing_type=sa.INTEGER(),
               comment='行号',
               existing_nullable=False)
        batch_op.alter_column('ref_rgstbillid',
               existing_type=sa.VARCHAR(length=8),
               comment='来源采购订单号',
               existing_nullable=False)
        batch_op.alter_column('ref_rgstlineno',
               existing_type=sa.INTEGER(),
               comment='来源订单行号',
               existing_nullable=False)
        batch_op.alter_column('itemcd',
               existing_type=sa.VARCHAR(length=6),
               comment='物料编码',
               existing_nullable=False)
        batch_op.alter_column('order_qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='订购数量(快照)',
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
        batch_op.alter_column('received_qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='已入库数量(快照)',
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
        batch_op.alter_column('already_settled',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='该行已结算累计(不含本次)',
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
        batch_op.alter_column('settle_qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='本次结算数量',
               existing_nullable=False)
        batch_op.alter_column('settle_price',
               existing_type=sa.NUMERIC(precision=16, scale=4),
               comment='结算单价',
               existing_nullable=False)
        batch_op.alter_column('settle_amt',
               existing_type=sa.NUMERIC(precision=16, scale=4),
               comment='结算金额',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('ix_tpc14_pcbilldt_itemcd'))
        batch_op.drop_index(batch_op.f('ix_tpc14_pcbilldt_pcbillid'))
        batch_op.drop_index(batch_op.f('ix_tpc14_pcbilldt_ref_reg'))
        batch_op.drop_constraint(batch_op.f('tpc14_pcbilldt_pcbillid_lineno_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_tpc14_pcbilldt_ref_registerdt'), type_='foreignkey')

    with op.batch_alter_table('tpc16_rpcbill', schema=None) as batch_op:
        batch_op.alter_column('suppliercd',
               existing_type=sa.VARCHAR(length=8),
               comment='供应商编码',
               existing_comment='客户编码',
               existing_nullable=True)
        batch_op.alter_column('return_reason',
               existing_type=sa.VARCHAR(length=20),
               comment='退货原因',
               existing_nullable=True)

    with op.batch_alter_table('tpc17_rpcbilldt', schema=None) as batch_op:
        batch_op.alter_column('return_price',
               existing_type=sa.NUMERIC(precision=16, scale=4),
               comment='退货单价',
               existing_nullable=True)
        batch_op.alter_column('return_amt',
               existing_type=sa.NUMERIC(precision=16, scale=4),
               comment='退货金额',
               existing_nullable=True)
        batch_op.alter_column('line_reason',
               existing_type=sa.VARCHAR(length=100),
               comment='行级退货原因说明',
               existing_nullable=True)

    with op.batch_alter_table('tpc20_requisition_order_link', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tpc20_register'), type_='foreignkey')

    with op.batch_alter_table('tqc10_result', schema=None) as batch_op:
        batch_op.alter_column('memo',
               existing_type=sa.VARCHAR(length=200),
               comment='备注',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_qc_batch_id'))

    with op.batch_alter_table('tqc11_resultdt', schema=None) as batch_op:
        batch_op.alter_column('ref_rgstbillid',
               existing_type=sa.VARCHAR(length=30),
               comment='来源入库单号',
               existing_nullable=True)

    with op.batch_alter_table('tqc11_resulteid', schema=None) as batch_op:
        batch_op.alter_column('ref_rgstbillid',
               existing_type=sa.VARCHAR(length=30),
               comment='来源入库单号',
               existing_nullable=True)

    with op.batch_alter_table('twh18_overlostdt', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'twh17_overlost', ['olbillid'], ['olbillid'])

    with op.batch_alter_table('twh18_overlosteid', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'twh17_overlost', ['olbillid'], ['olbillid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('twh18_overlosteid', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('twh18_overlostdt', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('tqc11_resulteid', schema=None) as batch_op:
        batch_op.alter_column('ref_rgstbillid',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='来源入库单号',
               existing_nullable=True)

    with op.batch_alter_table('tqc11_resultdt', schema=None) as batch_op:
        batch_op.alter_column('ref_rgstbillid',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='来源入库单号',
               existing_nullable=True)

    with op.batch_alter_table('tqc10_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_qc_batch_id'), ['batch_id'], unique=False)
        batch_op.alter_column('memo',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='备注',
               existing_nullable=True)

    with op.batch_alter_table('tpc20_requisition_order_link', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_tpc20_register'), 'tpc12_register', ['rgstbillid'], ['rgstbillid'], ondelete='CASCADE')

    with op.batch_alter_table('tpc17_rpcbilldt', schema=None) as batch_op:
        batch_op.alter_column('line_reason',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='行级退货原因说明',
               existing_nullable=True)
        batch_op.alter_column('return_amt',
               existing_type=sa.NUMERIC(precision=16, scale=4),
               comment=None,
               existing_comment='退货金额',
               existing_nullable=True)
        batch_op.alter_column('return_price',
               existing_type=sa.NUMERIC(precision=16, scale=4),
               comment=None,
               existing_comment='退货单价',
               existing_nullable=True)

    with op.batch_alter_table('tpc16_rpcbill', schema=None) as batch_op:
        batch_op.alter_column('return_reason',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='退货原因',
               existing_nullable=True)
        batch_op.alter_column('suppliercd',
               existing_type=sa.VARCHAR(length=8),
               comment='客户编码',
               existing_comment='供应商编码',
               existing_nullable=True)

    with op.batch_alter_table('tpc14_pcbilldt', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_tpc14_pcbilldt_ref_registerdt'), 'tpc13_registerdt', ['ref_rgstbillid', 'ref_rgstlineno'], ['rgstbillid', 'lineno'], ondelete='RESTRICT')
        batch_op.create_unique_constraint(batch_op.f('tpc14_pcbilldt_pcbillid_lineno_key'), ['pcbillid', 'lineno'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('ix_tpc14_pcbilldt_ref_reg'), ['ref_rgstbillid', 'ref_rgstlineno'], unique=False)
        batch_op.create_index(batch_op.f('ix_tpc14_pcbilldt_pcbillid'), ['pcbillid'], unique=False)
        batch_op.create_index(batch_op.f('ix_tpc14_pcbilldt_itemcd'), ['itemcd'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('settle_amt',
               existing_type=sa.NUMERIC(precision=16, scale=4),
               comment=None,
               existing_comment='结算金额',
               existing_nullable=False)
        batch_op.alter_column('settle_price',
               existing_type=sa.NUMERIC(precision=16, scale=4),
               comment=None,
               existing_comment='结算单价',
               existing_nullable=False)
        batch_op.alter_column('settle_qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='本次结算数量',
               existing_nullable=False)
        batch_op.alter_column('already_settled',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='该行已结算累计(不含本次)',
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
        batch_op.alter_column('received_qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='已入库数量(快照)',
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
        batch_op.alter_column('order_qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='订购数量(快照)',
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
        batch_op.alter_column('itemcd',
               existing_type=sa.VARCHAR(length=6),
               comment=None,
               existing_comment='物料编码',
               existing_nullable=False)
        batch_op.alter_column('ref_rgstlineno',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='来源订单行号',
               existing_nullable=False)
        batch_op.alter_column('ref_rgstbillid',
               existing_type=sa.VARCHAR(length=8),
               comment=None,
               existing_comment='来源采购订单号',
               existing_nullable=False)
        batch_op.alter_column('lineno',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='行号',
               existing_nullable=False)
        batch_op.alter_column('pcbillid',
               existing_type=sa.VARCHAR(length=8),
               comment=None,
               existing_comment='结算单号',
               existing_nullable=False)

    with op.batch_alter_table('tpc14_pcbill', schema=None) as batch_op:
        batch_op.alter_column('auditdate',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='审核日期',
               existing_nullable=True)
        batch_op.alter_column('auditman',
               existing_type=sa.VARCHAR(length=6),
               comment=None,
               existing_comment='审核人',
               existing_nullable=True)
        batch_op.alter_column('auditflg',
               existing_type=sa.VARCHAR(length=1),
               comment=None,
               existing_comment='审核标志',
               existing_nullable=True,
               existing_server_default=sa.text("'0'::character varying"))
        batch_op.alter_column('whcd',
               existing_type=sa.VARCHAR(length=50),
               comment='入库仓库',
               existing_comment='入库仓库（多选逗号分隔）',
               existing_nullable=True)
        batch_op.alter_column('total_settle_amt',
               existing_type=sa.NUMERIC(precision=16, scale=4),
               comment=None,
               existing_comment='结算总额',
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
        batch_op.alter_column('pcdate',
               existing_type=postgresql.TIMESTAMP(),
               comment='采购日期',
               existing_comment='结算日期',
               existing_nullable=True)
        batch_op.alter_column('invoice_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='发票日期',
               existing_nullable=True)
        batch_op.alter_column('invoice_no',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='发票号码',
               existing_nullable=True)
        batch_op.alter_column('pay_type',
               existing_type=sa.VARCHAR(length=3),
               comment=None,
               existing_comment='付款方式',
               existing_nullable=True,
               existing_server_default=sa.text("'COD'::character varying"))
        batch_op.alter_column('suppliercd',
               existing_type=sa.VARCHAR(length=8),
               comment='客户编码',
               existing_comment='供应商编码',
               existing_nullable=True)
        batch_op.alter_column('ref_rgstbillid',
               existing_type=sa.VARCHAR(length=8),
               comment=None,
               existing_comment='来源采购订单（月结置空）',
               existing_nullable=True)
        batch_op.alter_column('pcbillid',
               existing_type=sa.VARCHAR(length=8),
               comment='采购单号',
               existing_comment='结算单号',
               existing_nullable=False)

    with op.batch_alter_table('tpc13_registerdt', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tpc13_registerdt_rgstbillid_fkey'), 'tpc12_register', ['rgstbillid'], ['rgstbillid'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_registerdt_item'), 'tmm12_items', ['itemcd'], ['item_cd'], onupdate='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('uq_tpc13_registerdt_bill_line'), ['rgstbillid', 'lineno'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('tpc03_pcplanstatus', schema=None) as batch_op:
        batch_op.alter_column('refbillid',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=30),
               existing_comment='关联单号',
               existing_nullable=True)

    with op.batch_alter_table('tpc02_pcplandt', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_pcplandt_item'), 'tmm12_items', ['itemcd'], ['item_cd'], onupdate='CASCADE')

    with op.batch_alter_table('tms05_replace_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_tms05_wo'), ['wo_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('itemcd',
               existing_type=sa.VARCHAR(length=12),
               nullable=True,
               existing_comment='物料编码')
        batch_op.alter_column('new_eid',
               existing_type=sa.VARCHAR(length=20),
               comment='新物料序列号',
               existing_comment='新物料序列号（批次物料可为空，FQC合格后生成）',
               existing_nullable=True)
        batch_op.alter_column('old_eid',
               existing_type=sa.VARCHAR(length=20),
               comment='旧物料序列号',
               existing_comment='旧物料序列号（批次物料可为空）',
               existing_nullable=True)
        batch_op.drop_column('new_batch_no')
        batch_op.drop_column('old_batch_no')

    with op.batch_alter_table('tms01_work_order', schema=None) as batch_op:
        batch_op.alter_column('pick_whcd',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='领料出库仓库',
               existing_nullable=True)
        batch_op.alter_column('warehouse_cd',
               existing_type=sa.VARCHAR(length=20),
               comment='目标仓库',
               existing_comment='成品入库仓库',
               existing_nullable=True)
        batch_op.alter_column('wo_type',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='工单类型: PRODUCTION=生产 RENOVATION=翻新',
               existing_nullable=True,
               existing_server_default=sa.text("'PRODUCTION'::character varying"))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态（DRAFT/RELEASED/IN_PROGRESS/COMPLETED/CANCELLED）',
               existing_comment='状态（DRAFT/RELEASED/PICKING/IN_PROGRESS/QC_PENDING/COMPLETED/CANCELLED）',
               existing_nullable=True)

    with op.batch_alter_table('tmm44_pos_r_eid', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_pos_r_eid_useflg'), ['useflg', 'eid'], unique=False)
        batch_op.create_index(batch_op.f('idx_pos_r_eid_eid'), ['eid'], unique=False)

    with op.batch_alter_table('tmm43_eid_track', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_eid_track_type_eid'), ['type', 'eid'], unique=False)
        batch_op.create_index(batch_op.f('idx_eid_track_eid_itemcd'), ['eid', 'itemcd'], unique=False)

    with op.batch_alter_table('tmm43_eid', schema=None) as batch_op:
        batch_op.alter_column('ref_eid',
               existing_type=sa.VARCHAR(length=13),
               comment='来源EID（翻新溯源链）',
               existing_comment='溯源旧EID（翻新时记录来源）',
               existing_nullable=True)

    with op.batch_alter_table('tmm42_bomdt', schema=None) as batch_op:
        batch_op.alter_column('bomcd',
               existing_type=sa.String(length=6),
               type_=sa.VARCHAR(length=20),
               existing_comment='BOM编码',
               existing_nullable=False)

    with op.batch_alter_table('tmm41_bom', schema=None) as batch_op:
        batch_op.alter_column('bomcd',
               existing_type=sa.String(length=6),
               type_=sa.VARCHAR(length=20),
               existing_comment='BOM编码',
               existing_nullable=False)

    with op.batch_alter_table('tmm40_label', schema=None) as batch_op:
        batch_op.alter_column('useflg',
               existing_type=sa.VARCHAR(length=1),
               comment='有效标志',
               existing_comment='有效标志：1=未激活，0=已激活',
               existing_nullable=True,
               existing_server_default=sa.text("'1'::character varying"))
        batch_op.alter_column('classcd',
               existing_type=sa.String(length=6),
               type_=sa.VARCHAR(length=10),
               nullable=True,
               comment='分类编码',
               existing_comment='物料中类编码')
        batch_op.alter_column('labelid',
               existing_type=sa.String(length=13),
               type_=sa.VARCHAR(length=20),
               comment='标签ID',
               existing_comment='标签号（即激活后的EID）',
               existing_nullable=False)

    with op.batch_alter_table('tmm35_cust_pos_rl', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_cust_pos_rl_eid_useflg'), ['eid', 'useflg'], unique=False)

    with op.batch_alter_table('tmm24_custitems', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_custitems_item'), 'tmm12_items', ['itemcd'], ['item_cd'], onupdate='CASCADE')

    with op.batch_alter_table('tip02_supplier_price', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_supplier_price_item'), 'tmm12_items', ['itemcd'], ['item_cd'], onupdate='CASCADE')

    op.create_table('backup_tpc20_20260523',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pcplanid', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('pclineno', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rgstbillid', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('rgstlineno', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('linkqty', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('linkstatus', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('gendate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('upddate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('opercd', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.create_table('twh13_in_backup_20260602',
    sa.Column('inbillid', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('whcd', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('indate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('invtyp', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('refbillid', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('ptimes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('memo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('opercd', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('gendate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('auditflg', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('auditman', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('auditdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('useflg', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('optyp', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('suppcd', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.create_table('twh15_out_backup_20260602',
    sa.Column('outbillid', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('whcd', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('outdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('invtyp', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('ptimes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('memo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('opercd', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('gendate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('auditflg', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('auditman', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('auditdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('optyp', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('useflg', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('targetwhcd', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('suppcd', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('refbillid', sa.VARCHAR(length=8), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
