"""TPC16/TPC17退货表补全审核字段+来源订单关联

Revision ID: 5e2f0e99c995
Revises: 8c0f7c6f4e96
Create Date: 2026-05-23 15:40:17.354735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e2f0e99c995'
down_revision = '8c0f7c6f4e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tpc16_rpcbill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ref_rgstbillid', sa.String(length=8), nullable=True, comment='来源采购订单号'))
        batch_op.add_column(sa.Column('auditflg', sa.String(length=1), nullable=True, comment='审核标志'))
        batch_op.add_column(sa.Column('auditman', sa.String(length=6), nullable=True, comment='审核人'))
        batch_op.add_column(sa.Column('auditdate', sa.DateTime(), nullable=True, comment='审核日期'))

    with op.batch_alter_table('tpc17_rpcbilldt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ref_rgstlineno', sa.Integer(), nullable=True, comment='来源订单行号'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tpc17_rpcbilldt', schema=None) as batch_op:
        batch_op.drop_column('ref_rgstlineno')

    with op.batch_alter_table('tpc16_rpcbill', schema=None) as batch_op:
        batch_op.drop_column('auditdate')
        batch_op.drop_column('auditman')
        batch_op.drop_column('auditflg')
        batch_op.drop_column('ref_rgstbillid')

    # ### end Alembic commands ###
