"""新增国标地理表geo_province_city_area_street

Revision ID: 60776f4f1ab1
Revises: c1a2b3d4e5f6
Create Date: 2026-07-04 17:58:58.836407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60776f4f1ab1'
down_revision = 'c1a2b3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_province',
    sa.Column('code', sa.String(length=6), nullable=False, comment='国标省级代码（2位，如11=北京）'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='省级名称'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('geo_city',
    sa.Column('code', sa.String(length=6), nullable=False, comment='国标地级市代码（4位，如3101=上海市辖区）'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='地级市名称'),
    sa.Column('province_code', sa.String(length=6), nullable=True, comment='所属省级代码'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['province_code'], ['geo_province.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('geo_area',
    sa.Column('code', sa.String(length=6), nullable=False, comment='国标区县代码（6位，如310101=黄浦区）'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='区县名称'),
    sa.Column('city_code', sa.String(length=6), nullable=True, comment='所属地级市代码'),
    sa.Column('province_code', sa.String(length=6), nullable=True, comment='所属省级代码（冗余，便于查询）'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['city_code'], ['geo_city.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    with op.batch_alter_table('geo_area', schema=None) as batch_op:
        batch_op.create_index('idx_geo_area_city_code', ['city_code'], unique=False)
        batch_op.create_index('idx_geo_area_province_code', ['province_code'], unique=False)

    op.create_table('geo_street',
    sa.Column('code', sa.String(length=12), nullable=False, comment='国标街道代码（9位，如110101001=东华门街道）'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='街道/乡镇名称'),
    sa.Column('area_code', sa.String(length=6), nullable=True, comment='所属区县代码'),
    sa.Column('province_code', sa.String(length=6), nullable=True, comment='所属省级代码（冗余，便于查询）'),
    sa.Column('city_code', sa.String(length=6), nullable=True, comment='所属地级市代码（冗余，便于查询）'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_code'], ['geo_area.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    with op.batch_alter_table('geo_street', schema=None) as batch_op:
        batch_op.create_index('idx_geo_street_area_code', ['area_code'], unique=False)
        batch_op.create_index('idx_geo_street_city_code', ['city_code'], unique=False)

    with op.batch_alter_table('tmm22_customers', schema=None) as batch_op:
        batch_op.alter_column('area_cd',
               existing_type=sa.VARCHAR(length=20),
               comment='区域编码',
               existing_comment='区域编码（关联tmm46_area.area_cd，原Oracle TMM22.AREA整数已回填至此）',
               existing_nullable=True)
        batch_op.alter_column('store_cd',
               existing_type=sa.VARCHAR(length=30),
               comment='【废弃】门店编码，Oracle原表无此字段，数据全为空，与cust_cd功能重复，待删除',
               existing_comment='【废弃】Oracle原表无此字段，数据全为空，与cust_cd功能重复，待删除',
               existing_nullable=True)
        batch_op.alter_column('area',
               existing_type=sa.INTEGER(),
               comment='【废弃】Oracle原表AREA整数（关联TMM46_AREA.ID），迁移后由area_cd（VARCHAR）替代，数据已回填至area_cd，不再写入',
               existing_comment='【废弃】Oracle原表AREA整数（关联TMM46_AREA.ID），迁移后由area_cd替代，数据已回填至area_cd，不再写入，待删除',
               existing_nullable=True)

    with op.batch_alter_table('tmm46_area', schema=None) as batch_op:
        batch_op.alter_column('area_cd',
               existing_type=sa.VARCHAR(length=20),
               comment='区域编码（原Oracle TMM46_AREA.ID，迁移后字符串化为主键）',
               existing_comment='区域编码（原Oracle TMM46_AREA.ID，迁移后字符串化为主键，值为纯数字字符串）',
               existing_nullable=False)
        batch_op.alter_column('area_id',
               existing_type=sa.INTEGER(),
               comment='【废弃】Oracle原表ID的整数备份，已回填为area_cd::int，业务代码不再使用',
               existing_comment='【废弃】Oracle原表ID的整数备份，已回填为area_cd::int，业务代码不再使用，待删除',
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               comment='【废弃】Oracle原表NAME的备份，已迁移至area_nm，业务代码不再使用',
               existing_comment='【废弃】Oracle原表NAME的备份，已迁移至area_nm，业务代码不再使用，待删除',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tmm46_area', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               comment='【废弃】Oracle原表NAME的备份，已迁移至area_nm，业务代码不再使用，待删除',
               existing_comment='【废弃】Oracle原表NAME的备份，已迁移至area_nm，业务代码不再使用',
               existing_nullable=True)
        batch_op.alter_column('area_id',
               existing_type=sa.INTEGER(),
               comment='【废弃】Oracle原表ID的整数备份，已回填为area_cd::int，业务代码不再使用，待删除',
               existing_comment='【废弃】Oracle原表ID的整数备份，已回填为area_cd::int，业务代码不再使用',
               existing_nullable=True)
        batch_op.alter_column('area_cd',
               existing_type=sa.VARCHAR(length=20),
               comment='区域编码（原Oracle TMM46_AREA.ID，迁移后字符串化为主键，值为纯数字字符串）',
               existing_comment='区域编码（原Oracle TMM46_AREA.ID，迁移后字符串化为主键）',
               existing_nullable=False)

    with op.batch_alter_table('tmm22_customers', schema=None) as batch_op:
        batch_op.alter_column('area',
               existing_type=sa.INTEGER(),
               comment='【废弃】Oracle原表AREA整数（关联TMM46_AREA.ID），迁移后由area_cd替代，数据已回填至area_cd，不再写入，待删除',
               existing_comment='【废弃】Oracle原表AREA整数（关联TMM46_AREA.ID），迁移后由area_cd（VARCHAR）替代，数据已回填至area_cd，不再写入',
               existing_nullable=True)
        batch_op.alter_column('store_cd',
               existing_type=sa.VARCHAR(length=30),
               comment='【废弃】Oracle原表无此字段，数据全为空，与cust_cd功能重复，待删除',
               existing_comment='【废弃】门店编码，Oracle原表无此字段，数据全为空，与cust_cd功能重复，待删除',
               existing_nullable=True)
        batch_op.alter_column('area_cd',
               existing_type=sa.VARCHAR(length=20),
               comment='区域编码（关联tmm46_area.area_cd，原Oracle TMM22.AREA整数已回填至此）',
               existing_comment='区域编码',
               existing_nullable=True)

    with op.batch_alter_table('geo_street', schema=None) as batch_op:
        batch_op.drop_index('idx_geo_street_city_code')
        batch_op.drop_index('idx_geo_street_area_code')

    op.drop_table('geo_street')
    with op.batch_alter_table('geo_area', schema=None) as batch_op:
        batch_op.drop_index('idx_geo_area_province_code')
        batch_op.drop_index('idx_geo_area_city_code')

    op.drop_table('geo_area')
    op.drop_table('geo_city')
    op.drop_table('geo_province')
    # ### end Alembic commands ###
