"""新增TPC20需求订单关联表+TPC13冗余字段+执行视图

Revision ID: 8c0f7c6f4e96
Revises: ced3ead831dd
Create Date: 2026-05-23 15:32:22.429866

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c0f7c6f4e96'
down_revision = 'ced3ead831dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tpc20_requisition_order_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pcplanid', sa.String(length=20), nullable=False, comment='来源需求单号'),
    sa.Column('pclineno', sa.Integer(), nullable=False, comment='来源需求行号'),
    sa.Column('rgstbillid', sa.String(length=20), nullable=False, comment='采购订单号'),
    sa.Column('rgstlineno', sa.Integer(), nullable=False, comment='订单行号'),
    sa.Column('linkqty', sa.Numeric(precision=12, scale=2), nullable=True, comment='关联数量'),
    sa.Column('linkstatus', sa.String(length=20), nullable=True, comment='关联状态: ordered/partial_in/completed/cancelled'),
    sa.Column('gendate', sa.DateTime(), nullable=True, comment='创建日期'),
    sa.Column('upddate', sa.DateTime(), nullable=True, comment='更新日期'),
    sa.Column('opercd', sa.String(length=20), nullable=True, comment='操作员'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pcplanid', 'pclineno', 'rgstbillid', 'rgstlineno', name='uk_link_unique')
    )
    with op.batch_alter_table('tip01_price', schema=None) as batch_op:
        batch_op.alter_column('effective_date',
               existing_type=sa.DATE(),
               comment='生效日期',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
        batch_op.alter_column('expire_date',
               existing_type=sa.DATE(),
               comment='失效日期',
               existing_nullable=True)
        batch_op.alter_column('is_current',
               existing_type=sa.BOOLEAN(),
               comment='是否当前有效',
               existing_nullable=True,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('tip02_supplier_price', schema=None) as batch_op:
        batch_op.alter_column('itemcd',
               existing_type=sa.VARCHAR(length=6),
               comment='物料编码',
               existing_nullable=False)
        batch_op.alter_column('supp_cd',
               existing_type=sa.VARCHAR(length=8),
               comment='供应商编码',
               existing_nullable=False)
        batch_op.alter_column('min_qty',
               existing_type=sa.NUMERIC(),
               comment='起订量',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('itemprice',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='供应商报价',
               existing_nullable=False)
        batch_op.alter_column('effective_date',
               existing_type=sa.DATE(),
               comment='生效日期',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
        batch_op.alter_column('expire_date',
               existing_type=sa.DATE(),
               comment='失效日期',
               existing_nullable=True)
        batch_op.alter_column('is_current',
               existing_type=sa.BOOLEAN(),
               comment='是否当前有效',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('opercd',
               existing_type=sa.VARCHAR(length=6),
               comment='操作员',
               existing_nullable=True)
        batch_op.alter_column('gendate',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建日期',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('upddate',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新日期',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('useflg',
               existing_type=sa.VARCHAR(length=1),
               comment='有效标志',
               existing_nullable=True,
               existing_server_default=sa.text("'1'::character varying"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('tmm11_itemclass', schema=None) as batch_op:
        batch_op.alter_column('opercd',
               existing_type=sa.VARCHAR(length=6),
               comment='操作员',
               existing_nullable=True)
        batch_op.alter_column('gendate',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建日期',
               existing_nullable=True)
        batch_op.alter_column('upddate',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新日期',
               existing_nullable=True)

    with op.batch_alter_table('tmm40_label', schema=None) as batch_op:
        batch_op.alter_column('labelid',
               existing_type=sa.VARCHAR(length=20),
               comment='标签ID',
               existing_nullable=False)
        batch_op.alter_column('classcd',
               existing_type=sa.VARCHAR(length=10),
               comment='分类编码',
               existing_nullable=True)
        batch_op.alter_column('opercd',
               existing_type=sa.VARCHAR(length=6),
               comment='操作员',
               existing_nullable=True)
        batch_op.alter_column('gendate',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建日期',
               existing_nullable=True)
        batch_op.alter_column('upddate',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新日期',
               existing_nullable=True)
        batch_op.alter_column('useflg',
               existing_type=sa.VARCHAR(length=1),
               comment='有效标志',
               existing_nullable=True,
               existing_server_default=sa.text("'1'::character varying"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('tmm43_eid', schema=None) as batch_op:
        batch_op.alter_column('asset_type',
               existing_type=sa.VARCHAR(length=10),
               comment='资产类型（AT码表：01新机/02旧机/03翻新机/04报废）',
               existing_nullable=True)
        batch_op.alter_column('recyclable',
               existing_type=sa.BOOLEAN(),
               comment='可回收标志',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('recycle_status',
               existing_type=sa.VARCHAR(length=10),
               comment='回收状态（RS码表）',
               existing_nullable=True)
        batch_op.alter_column('asset_owner',
               existing_type=sa.VARCHAR(length=20),
               comment='资产所属方（AO码表）',
               existing_nullable=True,
               existing_server_default=sa.text("'CUSTOMER'::character varying"))
        batch_op.alter_column('install_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='安装日期',
               existing_nullable=True)

    with op.batch_alter_table('tmm43_eid_track', schema=None) as batch_op:
        batch_op.alter_column('install_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='安装日期',
               existing_nullable=True)
        batch_op.alter_column('n_install_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='新安装日期',
               existing_nullable=True)
        batch_op.alter_column('cust_cd',
               existing_type=sa.VARCHAR(length=20),
               comment='变更前客户',
               existing_nullable=True)
        batch_op.alter_column('n_cust_cd',
               existing_type=sa.VARCHAR(length=20),
               comment='变更后客户',
               existing_nullable=True)
        batch_op.alter_column('asset_type',
               existing_type=sa.VARCHAR(length=10),
               comment='资产类型',
               existing_nullable=True)
        batch_op.alter_column('n_asset_type',
               existing_type=sa.VARCHAR(length=10),
               comment='新资产类型',
               existing_nullable=True)
        batch_op.alter_column('recyclable',
               existing_type=sa.VARCHAR(length=1),
               comment='可回收标志',
               existing_nullable=True)
        batch_op.alter_column('n_recyclable',
               existing_type=sa.VARCHAR(length=1),
               comment='新可回收标志',
               existing_nullable=True)
        batch_op.alter_column('recycle_status',
               existing_type=sa.VARCHAR(length=10),
               comment='回收状态',
               existing_nullable=True)
        batch_op.alter_column('n_recycle_status',
               existing_type=sa.VARCHAR(length=10),
               comment='新回收状态',
               existing_nullable=True)
        batch_op.alter_column('asset_owner',
               existing_type=sa.VARCHAR(length=20),
               comment='资产所属方',
               existing_nullable=True)
        batch_op.alter_column('n_asset_owner',
               existing_type=sa.VARCHAR(length=20),
               comment='新资产所属方',
               existing_nullable=True)

    with op.batch_alter_table('tmm44_pos_r_eid', schema=None) as batch_op:
        batch_op.alter_column('posid',
               existing_type=sa.VARCHAR(length=50),
               comment='整机POS编码',
               existing_nullable=True)
        batch_op.alter_column('eid',
               existing_type=sa.VARCHAR(length=50),
               comment='配件EID',
               existing_nullable=True)
        batch_op.alter_column('itemcd',
               existing_type=sa.VARCHAR(length=10),
               comment='物料编码',
               existing_nullable=True)
        batch_op.alter_column('opercd',
               existing_type=sa.VARCHAR(length=6),
               comment='操作员',
               existing_nullable=True)
        batch_op.alter_column('gendate',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建日期',
               existing_nullable=True)
        batch_op.alter_column('upddate',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新日期',
               existing_nullable=True)

    with op.batch_alter_table('tmm52_posstatus', schema=None) as batch_op:
        batch_op.alter_column('codecd',
               existing_type=sa.VARCHAR(length=50),
               comment='状态编码',
               existing_nullable=True)
        batch_op.alter_column('codecd1',
               existing_type=sa.VARCHAR(length=50),
               comment='状态编码1',
               existing_nullable=True)
        batch_op.alter_column('memo',
               existing_type=sa.VARCHAR(length=200),
               comment='备注',
               existing_nullable=True)
        batch_op.alter_column('sysflg',
               existing_type=sa.VARCHAR(length=1),
               comment='系统标志',
               existing_nullable=True)
        batch_op.alter_column('opercd',
               existing_type=sa.VARCHAR(length=6),
               comment='操作员',
               existing_nullable=True)
        batch_op.alter_column('gendate',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建日期',
               existing_nullable=True)
        batch_op.alter_column('upddate',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新日期',
               existing_nullable=True)
        batch_op.alter_column('useflg',
               existing_type=sa.VARCHAR(length=1),
               comment='有效标志',
               existing_nullable=True,
               existing_server_default=sa.text("'1'::character varying"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('tmm61_deposit', schema=None) as batch_op:
        batch_op.alter_column('auditflg',
               existing_type=sa.VARCHAR(length=1),
               comment='审核标志(0未审/1已审)',
               existing_nullable=True,
               existing_server_default=sa.text("'0'::character varying"))
        batch_op.alter_column('auditman',
               existing_type=sa.VARCHAR(length=6),
               comment='审核人',
               existing_nullable=True)
        batch_op.alter_column('auditdate',
               existing_type=postgresql.TIMESTAMP(),
               comment='审核日期',
               existing_nullable=True)

    with op.batch_alter_table('tpc13_registerdt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ref_pcplanid', sa.String(length=20), nullable=True, comment='来源需求单号'))
        batch_op.add_column(sa.Column('ref_pclineno', sa.Integer(), nullable=True, comment='来源需求行号'))

    op.execute("""
        CREATE OR REPLACE VIEW v_requisition_execution AS
        SELECT
            p.pcplanid, p.plandate, p.auditflg, p.auditman, p.auditdate, p.useflg,
            dt.lineno, dt.itemcd, i.item_nm AS itemnm, i.spec, i.wunit,
            dt.rgstqty AS plan_qty,
            dt.auditqty AS audit_qty,
            COALESCE(link_stats.ordered_qty, 0) AS ordered_qty,
            COALESCE(link_stats.received_qty, 0) AS received_qty,
            dt.auditqty - COALESCE(link_stats.ordered_qty, 0) AS available_qty,
            CASE
                WHEN COALESCE(link_stats.ordered_qty, 0) = 0 THEN '未开始'
                WHEN COALESCE(link_stats.received_qty, 0) >= dt.rgstqty THEN '已完成'
                WHEN COALESCE(link_stats.received_qty, 0) > 0 THEN '执行中'
                ELSE '已下单'
            END AS execution_status,
            CASE WHEN dt.rgstqty > 0
                THEN ROUND(COALESCE(link_stats.received_qty, 0) / dt.rgstqty * 100, 2)
                ELSE 0
            END AS execution_rate
        FROM tpc01_pcplan p
        JOIN tpc02_pcplandt dt ON p.pcplanid = dt.pcplanid
        LEFT JOIN tmm12_items i ON dt.itemcd = i.item_cd
        LEFT JOIN (
            SELECT l.pcplanid, l.pclineno,
                SUM(l.linkqty) AS ordered_qty,
                SUM(CASE WHEN rd.inqty >= rd.rgsqty THEN l.linkqty ELSE 0 END) AS received_qty
            FROM tpc20_requisition_order_link l
            JOIN tpc13_registerdt rd ON l.rgstbillid = rd.rgstbillid AND l.rgstlineno = rd.lineno
            JOIN tpc12_register r ON rd.rgstbillid = r.rgstbillid
            WHERE r.useflg <> '9'
            GROUP BY l.pcplanid, l.pclineno
        ) link_stats ON dt.pcplanid = link_stats.pcplanid AND dt.lineno = link_stats.pclineno
        WHERE p.useflg = '1'
    """)

    op.execute("""
        CREATE OR REPLACE VIEW v_item_requisition_status AS
        SELECT
            dt.itemcd, i.item_nm AS itemnm, i.spec, i.wunit,
            SUM(dt.auditqty) AS total_audit_qty,
            SUM(dt.auditqty) - COALESCE(SUM(link_stats.ordered_qty), 0) AS available_for_order,
            json_agg(jsonb_build_object(
                'pcplanid', dt.pcplanid, 'pclineno', dt.lineno,
                'plandate', p.plandate, 'auditqty', dt.auditqty,
                'available_qty', dt.auditqty - COALESCE(link_stats.ordered_qty, 0)
            ) ORDER BY p.plandate) AS plan_details
        FROM tpc02_pcplandt dt
        JOIN tpc01_pcplan p ON dt.pcplanid = p.pcplanid AND p.useflg = '1' AND p.auditflg = '2'
        LEFT JOIN tmm12_items i ON dt.itemcd = i.item_cd
        LEFT JOIN (
            SELECT l.pcplanid, l.pclineno, SUM(l.linkqty) AS ordered_qty
            FROM tpc20_requisition_order_link l
            JOIN tpc12_register r ON l.rgstbillid = r.rgstbillid
            WHERE r.useflg <> '9'
            GROUP BY l.pcplanid, l.pclineno
        ) link_stats ON dt.pcplanid = link_stats.pcplanid AND dt.lineno = link_stats.pclineno
        WHERE dt.auditqty > 0
        GROUP BY dt.itemcd, i.item_nm, i.spec, i.wunit
        HAVING SUM(dt.auditqty) - COALESCE(SUM(link_stats.ordered_qty), 0) > 0
    """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS v_item_requisition_status")
    op.execute("DROP VIEW IF EXISTS v_requisition_execution")

    with op.batch_alter_table('tpc13_registerdt', schema=None) as batch_op:
        batch_op.drop_column('ref_pclineno')
        batch_op.drop_column('ref_pcplanid')

    with op.batch_alter_table('tmm61_deposit', schema=None) as batch_op:
        batch_op.alter_column('auditdate',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='审核日期',
               existing_nullable=True)
        batch_op.alter_column('auditman',
               existing_type=sa.VARCHAR(length=6),
               comment=None,
               existing_comment='审核人',
               existing_nullable=True)
        batch_op.alter_column('auditflg',
               existing_type=sa.VARCHAR(length=1),
               comment=None,
               existing_comment='审核标志(0未审/1已审)',
               existing_nullable=True,
               existing_server_default=sa.text("'0'::character varying"))

    with op.batch_alter_table('tmm52_posstatus', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('useflg',
               existing_type=sa.VARCHAR(length=1),
               comment=None,
               existing_comment='有效标志',
               existing_nullable=True,
               existing_server_default=sa.text("'1'::character varying"))
        batch_op.alter_column('upddate',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新日期',
               existing_nullable=True)
        batch_op.alter_column('gendate',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建日期',
               existing_nullable=True)
        batch_op.alter_column('opercd',
               existing_type=sa.VARCHAR(length=6),
               comment=None,
               existing_comment='操作员',
               existing_nullable=True)
        batch_op.alter_column('sysflg',
               existing_type=sa.VARCHAR(length=1),
               comment=None,
               existing_comment='系统标志',
               existing_nullable=True)
        batch_op.alter_column('memo',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='备注',
               existing_nullable=True)
        batch_op.alter_column('codecd1',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='状态编码1',
               existing_nullable=True)
        batch_op.alter_column('codecd',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='状态编码',
               existing_nullable=True)

    with op.batch_alter_table('tmm44_pos_r_eid', schema=None) as batch_op:
        batch_op.alter_column('upddate',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新日期',
               existing_nullable=True)
        batch_op.alter_column('gendate',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建日期',
               existing_nullable=True)
        batch_op.alter_column('opercd',
               existing_type=sa.VARCHAR(length=6),
               comment=None,
               existing_comment='操作员',
               existing_nullable=True)
        batch_op.alter_column('itemcd',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='物料编码',
               existing_nullable=True)
        batch_op.alter_column('eid',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='配件EID',
               existing_nullable=True)
        batch_op.alter_column('posid',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='整机POS编码',
               existing_nullable=True)

    with op.batch_alter_table('tmm43_eid_track', schema=None) as batch_op:
        batch_op.alter_column('n_asset_owner',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='新资产所属方',
               existing_nullable=True)
        batch_op.alter_column('asset_owner',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='资产所属方',
               existing_nullable=True)
        batch_op.alter_column('n_recycle_status',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='新回收状态',
               existing_nullable=True)
        batch_op.alter_column('recycle_status',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='回收状态',
               existing_nullable=True)
        batch_op.alter_column('n_recyclable',
               existing_type=sa.VARCHAR(length=1),
               comment=None,
               existing_comment='新可回收标志',
               existing_nullable=True)
        batch_op.alter_column('recyclable',
               existing_type=sa.VARCHAR(length=1),
               comment=None,
               existing_comment='可回收标志',
               existing_nullable=True)
        batch_op.alter_column('n_asset_type',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='新资产类型',
               existing_nullable=True)
        batch_op.alter_column('asset_type',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='资产类型',
               existing_nullable=True)
        batch_op.alter_column('n_cust_cd',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='变更后客户',
               existing_nullable=True)
        batch_op.alter_column('cust_cd',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='变更前客户',
               existing_nullable=True)
        batch_op.alter_column('n_install_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='新安装日期',
               existing_nullable=True)
        batch_op.alter_column('install_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='安装日期',
               existing_nullable=True)

    with op.batch_alter_table('tmm43_eid', schema=None) as batch_op:
        batch_op.alter_column('install_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='安装日期',
               existing_nullable=True)
        batch_op.alter_column('asset_owner',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='资产所属方（AO码表）',
               existing_nullable=True,
               existing_server_default=sa.text("'CUSTOMER'::character varying"))
        batch_op.alter_column('recycle_status',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='回收状态（RS码表）',
               existing_nullable=True)
        batch_op.alter_column('recyclable',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='可回收标志',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('asset_type',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='资产类型（AT码表：01新机/02旧机/03翻新机/04报废）',
               existing_nullable=True)

    with op.batch_alter_table('tmm40_label', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('useflg',
               existing_type=sa.VARCHAR(length=1),
               comment=None,
               existing_comment='有效标志',
               existing_nullable=True,
               existing_server_default=sa.text("'1'::character varying"))
        batch_op.alter_column('upddate',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新日期',
               existing_nullable=True)
        batch_op.alter_column('gendate',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建日期',
               existing_nullable=True)
        batch_op.alter_column('opercd',
               existing_type=sa.VARCHAR(length=6),
               comment=None,
               existing_comment='操作员',
               existing_nullable=True)
        batch_op.alter_column('classcd',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='分类编码',
               existing_nullable=True)
        batch_op.alter_column('labelid',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='标签ID',
               existing_nullable=False)

    with op.batch_alter_table('tmm11_itemclass', schema=None) as batch_op:
        batch_op.alter_column('upddate',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新日期',
               existing_nullable=True)
        batch_op.alter_column('gendate',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建日期',
               existing_nullable=True)
        batch_op.alter_column('opercd',
               existing_type=sa.VARCHAR(length=6),
               comment=None,
               existing_comment='操作员',
               existing_nullable=True)

    with op.batch_alter_table('tip02_supplier_price', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('useflg',
               existing_type=sa.VARCHAR(length=1),
               comment=None,
               existing_comment='有效标志',
               existing_nullable=True,
               existing_server_default=sa.text("'1'::character varying"))
        batch_op.alter_column('upddate',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新日期',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('gendate',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建日期',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('opercd',
               existing_type=sa.VARCHAR(length=6),
               comment=None,
               existing_comment='操作员',
               existing_nullable=True)
        batch_op.alter_column('is_current',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否当前有效',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('expire_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='失效日期',
               existing_nullable=True)
        batch_op.alter_column('effective_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='生效日期',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
        batch_op.alter_column('itemprice',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='供应商报价',
               existing_nullable=False)
        batch_op.alter_column('min_qty',
               existing_type=sa.NUMERIC(),
               comment=None,
               existing_comment='起订量',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('supp_cd',
               existing_type=sa.VARCHAR(length=8),
               comment=None,
               existing_comment='供应商编码',
               existing_nullable=False)
        batch_op.alter_column('itemcd',
               existing_type=sa.VARCHAR(length=6),
               comment=None,
               existing_comment='物料编码',
               existing_nullable=False)

    with op.batch_alter_table('tip01_price', schema=None) as batch_op:
        batch_op.alter_column('is_current',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否当前有效',
               existing_nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('expire_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='失效日期',
               existing_nullable=True)
        batch_op.alter_column('effective_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='生效日期',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))

    op.drop_table('tpc20_requisition_order_link')
    # ### end Alembic commands ###
