"""恢复155个缺失字段+10个优化字段

Revision ID: 9830fca8c37b
Revises: 4e0417eb815d
Create Date: 2026-05-06 04:22:46.058833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9830fca8c37b'
down_revision = '4e0417eb815d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tit04_archivecode', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uncheck', sa.String(length=1), nullable=True, comment='未审核标志'))

    with op.batch_alter_table('tit10_pos_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'))
        batch_op.add_column(sa.Column('creator', sa.String(length=6), nullable=True, comment='创建人'))

    with op.batch_alter_table('tit11_maintenance_attc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attc', sa.LargeBinary(), nullable=True, comment='附件内容'))

    with op.batch_alter_table('tit29_noclose_track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cause_mian', sa.String(length=20), nullable=True, comment='原因大类（Oracle原字段名）'))

    with op.batch_alter_table('tkq01_attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'))
        batch_op.add_column(sa.Column('updator', sa.String(length=10), nullable=True, comment='更新人'))

    with op.batch_alter_table('tkq02_attendancecount', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memo', sa.String(length=200), nullable=True, comment='备注'))
        batch_op.add_column(sa.Column('imp_num', sa.Integer(), nullable=True, comment='导入次数'))
        batch_op.add_column(sa.Column('imp_date', sa.DateTime(), nullable=True, comment='导入日期'))
        batch_op.add_column(sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'))
        batch_op.add_column(sa.Column('updator', sa.String(length=10), nullable=True, comment='更新人'))

    with op.batch_alter_table('tmc01_menus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('levelcd', sa.String(length=1), nullable=True, comment='菜单层级'))
        batch_op.add_column(sa.Column('parent', sa.String(length=6), nullable=True, comment='父级菜单（Oracle原字段）'))
        batch_op.add_column(sa.Column('picname', sa.String(length=30), nullable=True, comment='图标名称'))
        batch_op.add_column(sa.Column('ordno', sa.Integer(), nullable=True, comment='排序号（Oracle原字段）'))
        batch_op.add_column(sa.Column('openflg', sa.String(length=1), nullable=True, comment='开放标志'))
        batch_op.add_column(sa.Column('childflg', sa.String(length=1), nullable=True, comment='子节点标志'))
        batch_op.add_column(sa.Column('useflg', sa.String(length=1), nullable=True, comment='有效标志'))

    with op.batch_alter_table('tmc02_menusdt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('useflg', sa.String(length=1), nullable=True, comment='有效标志'))

    with op.batch_alter_table('tmc03_usermenus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ordno', sa.Integer(), nullable=True, comment='排序号'))
        batch_op.add_column(sa.Column('useflg', sa.String(length=1), nullable=True, comment='有效标志'))

    with op.batch_alter_table('tmc11_departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('levelcd', sa.String(length=1), nullable=True, comment='部门层级'))
        batch_op.add_column(sa.Column('parent', sa.String(length=6), nullable=True, comment='上级部门（Oracle原字段）'))
        batch_op.add_column(sa.Column('leader', sa.String(length=6), nullable=True, comment='部门领导'))
        batch_op.add_column(sa.Column('childflg', sa.String(length=1), nullable=True, comment='子节点标志'))
        batch_op.add_column(sa.Column('useflg', sa.String(length=1), nullable=True, comment='有效标志'))

    with op.batch_alter_table('tmc12_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('useflg', sa.String(length=1), nullable=True, comment='有效标志'))

    with op.batch_alter_table('tmc13_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passwd', sa.String(length=128), nullable=True, comment='原始密码（数据迁移用）'))
        batch_op.add_column(sa.Column('credamt', sa.Numeric(precision=12, scale=2), nullable=True, comment='信用额度'))
        batch_op.add_column(sa.Column('useflg', sa.String(length=1), nullable=True, comment='有效标志'))

    with op.batch_alter_table('tmc31_groupright', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scale', sa.String(length=1), nullable=True, comment='权限范围'))
        batch_op.add_column(sa.Column('useflg', sa.String(length=1), nullable=True, comment='有效标志'))

    with op.batch_alter_table('tmc41_acclog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('startdate', sa.DateTime(), nullable=True, comment='开始日期'))

    with op.batch_alter_table('tmc71_sysparm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pk', sa.String(length=50), nullable=True, comment='参数主键'))
        batch_op.add_column(sa.Column('costtype', sa.String(length=1), nullable=True, comment='成本类型'))
        batch_op.add_column(sa.Column('autobackpath', sa.String(length=200), nullable=True, comment='自动备份路径'))
        batch_op.add_column(sa.Column('invoicesharepath', sa.String(length=200), nullable=True, comment='发票共享路径'))
        batch_op.add_column(sa.Column('poinvaliddays', sa.Integer(), nullable=True, comment='采购失效天数'))
        batch_op.add_column(sa.Column('soinvaliddays', sa.Integer(), nullable=True, comment='销售失效天数'))
        batch_op.add_column(sa.Column('allowmultilogon', sa.String(length=1), nullable=True, comment='允许多点登录'))
        batch_op.add_column(sa.Column('shopbilltype', sa.String(length=1), nullable=True, comment='店铺单据类型'))
        batch_op.add_column(sa.Column('centralwarehouse', sa.String(length=4), nullable=True, comment='中心仓库编码'))

    with op.batch_alter_table('tmm01_company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leader', sa.String(length=10), nullable=True, comment='负责人'))
        batch_op.add_column(sa.Column('telex', sa.String(length=20), nullable=True, comment='电传号'))
        batch_op.add_column(sa.Column('faxno', sa.String(length=20), nullable=True, comment='传真'))
        batch_op.add_column(sa.Column('banknm', sa.String(length=30), nullable=True, comment='开户银行'))
        batch_op.add_column(sa.Column('bankaccno', sa.String(length=20), nullable=True, comment='银行账号'))
        batch_op.add_column(sa.Column('taxno', sa.String(length=18), nullable=True, comment='税号'))
        batch_op.add_column(sa.Column('opendate', sa.DateTime(), nullable=True, comment='开业日期'))
        batch_op.add_column(sa.Column('useflg', sa.String(length=1), nullable=True, comment='有效标志'))
        batch_op.add_column(sa.Column('mailcd', sa.String(length=6), nullable=True, comment='邮编'))
        batch_op.add_column(sa.Column('produce', sa.Integer(), nullable=True, comment='生产标志'))
        batch_op.add_column(sa.Column('maintenance', sa.Integer(), nullable=True, comment='维护标志'))

    with op.batch_alter_table('tmm11_itemclass', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classtyp', sa.String(length=1), nullable=True, comment='分类类型'))
        batch_op.add_column(sa.Column('childflg', sa.String(length=1), nullable=True, comment='子节点标志'))
        batch_op.add_column(sa.Column('useflg', sa.String(length=1), nullable=True, comment='有效标志'))

    with op.batch_alter_table('tmm12_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('itemanm', sa.String(length=40), nullable=True, comment='物料别名'))
        batch_op.add_column(sa.Column('itembrcd', sa.String(length=30), nullable=True, comment='物料条码'))
        batch_op.add_column(sa.Column('itemsize', sa.String(length=30), nullable=True, comment='规格尺寸'))
        batch_op.add_column(sa.Column('countrycd', sa.String(length=3), nullable=True, comment='产地国家'))
        batch_op.add_column(sa.Column('provincecd', sa.String(length=2), nullable=True, comment='省份'))
        batch_op.add_column(sa.Column('citycd', sa.String(length=4), nullable=True, comment='城市'))
        batch_op.add_column(sa.Column('wunit', sa.String(length=4), nullable=True, comment='计量单位'))
        batch_op.add_column(sa.Column('pcrep', sa.String(length=6), nullable=True, comment='采购负责人'))
        batch_op.add_column(sa.Column('keeper', sa.String(length=6), nullable=True, comment='库管员'))
        batch_op.add_column(sa.Column('upperlimit', sa.Integer(), nullable=True, comment='库存上限'))
        batch_op.add_column(sa.Column('lowerlimit', sa.Integer(), nullable=True, comment='库存下限'))
        batch_op.add_column(sa.Column('minorder', sa.Integer(), nullable=True, comment='最小订购量'))
        batch_op.add_column(sa.Column('newperiod', sa.Integer(), nullable=True, comment='新品周期(天)'))
        batch_op.add_column(sa.Column('oldperiod', sa.Integer(), nullable=True, comment='旧品周期(天)'))
        batch_op.add_column(sa.Column('backup', sa.String(length=200), nullable=True, comment='备注'))
        batch_op.add_column(sa.Column('typflg', sa.String(length=1), nullable=True, comment='物料类型标志'))
        batch_op.add_column(sa.Column('purchasetyp', sa.String(length=1), nullable=True, comment='采购类型'))
        batch_op.add_column(sa.Column('consume', sa.String(length=1), nullable=True, comment='消耗标志'))

    with op.batch_alter_table('tmm18_supplierclass', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classtyp', sa.String(length=1), nullable=True, comment='分类类型'))
        batch_op.add_column(sa.Column('parent', sa.String(length=20), nullable=True, comment='上级分类'))
        batch_op.add_column(sa.Column('childflg', sa.String(length=1), nullable=True, comment='子节点标志'))
        batch_op.add_column(sa.Column('useflg', sa.String(length=1), nullable=True, comment='有效标志'))

    with op.batch_alter_table('tmm19_suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custcd', sa.String(length=8), nullable=True, comment='关联客户编码'))
        batch_op.add_column(sa.Column('custnm', sa.String(length=60), nullable=True, comment='供应商全称'))
        batch_op.add_column(sa.Column('custanm', sa.String(length=20), nullable=True, comment='供应商别名'))
        batch_op.add_column(sa.Column('custbrcd', sa.String(length=20), nullable=True, comment='供应商条码'))
        batch_op.add_column(sa.Column('scale', sa.String(length=1), nullable=True, comment='规模等级'))
        batch_op.add_column(sa.Column('zipcd', sa.String(length=6), nullable=True, comment='邮编'))
        batch_op.add_column(sa.Column('phoneno', sa.String(length=20), nullable=True, comment='座机电话'))
        batch_op.add_column(sa.Column('faxno', sa.String(length=20), nullable=True, comment='传真'))
        batch_op.add_column(sa.Column('taxno', sa.String(length=18), nullable=True, comment='税号'))
        batch_op.add_column(sa.Column('banknm', sa.String(length=40), nullable=True, comment='开户银行'))
        batch_op.add_column(sa.Column('bankaccno', sa.String(length=50), nullable=True, comment='银行账号'))
        batch_op.add_column(sa.Column('pcrep', sa.String(length=6), nullable=True, comment='采购联系人'))
        batch_op.add_column(sa.Column('suppinfo', sa.String(length=1), nullable=True, comment='供应商状态'))
        batch_op.add_column(sa.Column('agreements', sa.String(length=1), nullable=True, comment='协议标志'))

    with op.batch_alter_table('tmm21_custclass', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classtyp', sa.String(length=1), nullable=True, comment='分类类型'))
        batch_op.add_column(sa.Column('childflg', sa.String(length=1), nullable=True, comment='子节点标志'))
        batch_op.add_column(sa.Column('useflg', sa.String(length=1), nullable=True, comment='有效标志'))

    with op.batch_alter_table('tmm22_customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cust_anm', sa.String(length=40), nullable=True, comment='客户别名'))
        batch_op.add_column(sa.Column('cust_brcd', sa.String(length=20), nullable=True, comment='客户条码'))
        batch_op.add_column(sa.Column('zipcd', sa.String(length=6), nullable=True, comment='邮编'))
        batch_op.add_column(sa.Column('faxno', sa.String(length=20), nullable=True, comment='传真'))
        batch_op.add_column(sa.Column('taxno', sa.String(length=18), nullable=True, comment='税号'))
        batch_op.add_column(sa.Column('banknm', sa.String(length=40), nullable=True, comment='开户银行'))
        batch_op.add_column(sa.Column('bankaccno', sa.String(length=50), nullable=True, comment='银行账号'))
        batch_op.add_column(sa.Column('parentcd', sa.String(length=8), nullable=True, comment='上级客户编码'))
        batch_op.add_column(sa.Column('backup', sa.String(length=200), nullable=True, comment='备注'))
        batch_op.add_column(sa.Column('location', sa.String(length=1), nullable=True, comment='位置标志'))
        batch_op.add_column(sa.Column('area', sa.Integer(), nullable=True, comment='区域编号'))
        batch_op.add_column(sa.Column('pos_n', sa.Integer(), nullable=True, comment='POS数量'))
        batch_op.add_column(sa.Column('opersystem', sa.String(length=128), nullable=True, comment='POS操作系统'))
        batch_op.add_column(sa.Column('data_base', sa.String(length=128), nullable=True, comment='POS数据库版本'))
        batch_op.add_column(sa.Column('soft_edition', sa.String(length=128), nullable=True, comment='POS软件版本'))
        batch_op.add_column(sa.Column('s_status', sa.String(length=1), nullable=True, comment='状态标志'))
        batch_op.add_column(sa.Column('ad_video', sa.String(length=1), nullable=True, comment='广告机标志'))
        batch_op.add_column(sa.Column('card3g', sa.String(length=30), nullable=True, comment='3G卡号'))
        batch_op.add_column(sa.Column('adr3g', sa.String(length=20), nullable=True, comment='3G地址'))
        batch_op.add_column(sa.Column('systemcode', sa.String(length=50), nullable=True, comment='内核版本'))
        batch_op.add_column(sa.Column('custrnm', sa.String(length=80), nullable=True, comment='客户全称'))
        batch_op.add_column(sa.Column('opendate', sa.DateTime(), nullable=True, comment='首次开通日期'))
        batch_op.add_column(sa.Column('replacedate', sa.DateTime(), nullable=True, comment='最近更换日期'))
        batch_op.add_column(sa.Column('levels', sa.String(length=2), nullable=True, comment='客户等级'))
        batch_op.add_column(sa.Column('ordertype', sa.String(length=10), nullable=True, comment='要货方式'))
        batch_op.add_column(sa.Column('jl_contactor', sa.String(length=10), nullable=True, comment='经理联系人'))
        batch_op.add_column(sa.Column('jl_phoneno', sa.String(length=60), nullable=True, comment='经理电话'))
        batch_op.add_column(sa.Column('posstatus', sa.String(length=2), nullable=True, comment='POS运行状态'))
        batch_op.add_column(sa.Column('posstatus1', sa.String(length=2), nullable=True, comment='POS状态1'))
        batch_op.add_column(sa.Column('is_contract', sa.String(length=2), nullable=True, comment='合同标志'))
        batch_op.add_column(sa.Column('yj_money', sa.Numeric(precision=12, scale=2), nullable=True, comment='押金金额'))
        batch_op.add_column(sa.Column('source_type', sa.String(length=20), nullable=True, comment='来源类型（PREPLAN/MANUAL/IMPORT/API）'))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True, comment='转正时间'))
        batch_op.add_column(sa.Column('preplan_id', sa.String(length=50), nullable=True, comment='关联预计划号'))
        batch_op.add_column(sa.Column('valid_until', sa.DateTime(), nullable=True, comment='临时客户有效期'))

    with op.batch_alter_table('tmm22_customers_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('change_reason', sa.String(length=200), nullable=True, comment='变更原因'))
        batch_op.add_column(sa.Column('device_change_id', sa.String(length=20), nullable=True, comment='关联变更单号'))

    with op.batch_alter_table('tmm31_syscodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sysflg', sa.String(length=1), nullable=True, comment='系统标志'))

    with op.batch_alter_table('tmm34_idmaster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idtyp', sa.String(length=2), nullable=True, comment='ID类型'))
        batch_op.add_column(sa.Column('idtypnm', sa.String(length=20), nullable=True, comment='类型名称'))
        batch_op.add_column(sa.Column('curbillid', sa.String(length=30), nullable=True, comment='当前流水号'))
        batch_op.add_column(sa.Column('maxbillid', sa.String(length=30), nullable=True, comment='最大流水号'))
        batch_op.add_column(sa.Column('loops', sa.String(length=1), nullable=True, comment='循环标志'))
        batch_op.add_column(sa.Column('useflg', sa.String(length=1), nullable=True, comment='有效标志'))

    with op.batch_alter_table('tmm35_cust_pos_rl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sysinfo', sa.String(length=30), nullable=True, comment='系统信息'))
        batch_op.add_column(sa.Column('softinfo', sa.String(length=30), nullable=True, comment='软件信息'))
        batch_op.add_column(sa.Column('posupddate', sa.DateTime(), nullable=True, comment='POS更新日期'))
        batch_op.add_column(sa.Column('posinfo', sa.String(length=30), nullable=True, comment='POS信息'))
        batch_op.add_column(sa.Column('pos_area', sa.String(length=2), nullable=True, comment='区域'))
        batch_op.add_column(sa.Column('status', sa.String(length=1), nullable=True, comment='设备状态'))
        batch_op.add_column(sa.Column('typflg', sa.String(length=2), nullable=True, comment='类型标志'))
        batch_op.add_column(sa.Column('maintenancedate', sa.DateTime(), nullable=True, comment='维护日期'))
        batch_op.add_column(sa.Column('maintenancetyp', sa.String(length=6), nullable=True, comment='维护类型'))
        batch_op.add_column(sa.Column('maintenanceno', sa.String(length=10), nullable=True, comment='维护单号'))
        batch_op.add_column(sa.Column('asset_status', sa.String(length=10), nullable=True, comment='资产状态（ACTIVE/RETURNED/SCRAPPED）'))
        batch_op.add_column(sa.Column('created_from', sa.String(length=20), nullable=True, comment='来源追溯'))
        batch_op.add_column(sa.Column('source_id', sa.String(length=20), nullable=True, comment='来源单号'))
        batch_op.add_column(sa.Column('warranty_expire', sa.DateTime(), nullable=True, comment='保修到期日'))

    with op.batch_alter_table('tmm46_area', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area_id', sa.Integer(), nullable=True, comment='区域ID'))
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True, comment='区域全称'))
        batch_op.add_column(sa.Column('usercd', sa.String(length=6), nullable=True, comment='负责人编码'))

    with op.batch_alter_table('tmm47_commode', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent', sa.String(length=20), nullable=True, comment='上级编码'))
        batch_op.add_column(sa.Column('childflg', sa.String(length=1), nullable=True, comment='子节点标志'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tmm47_commode', schema=None) as batch_op:
        batch_op.drop_column('childflg')
        batch_op.drop_column('parent')

    with op.batch_alter_table('tmm46_area', schema=None) as batch_op:
        batch_op.drop_column('usercd')
        batch_op.drop_column('name')
        batch_op.drop_column('area_id')

    with op.batch_alter_table('tmm35_cust_pos_rl', schema=None) as batch_op:
        batch_op.drop_column('warranty_expire')
        batch_op.drop_column('source_id')
        batch_op.drop_column('created_from')
        batch_op.drop_column('asset_status')
        batch_op.drop_column('maintenanceno')
        batch_op.drop_column('maintenancetyp')
        batch_op.drop_column('maintenancedate')
        batch_op.drop_column('typflg')
        batch_op.drop_column('status')
        batch_op.drop_column('pos_area')
        batch_op.drop_column('posinfo')
        batch_op.drop_column('posupddate')
        batch_op.drop_column('softinfo')
        batch_op.drop_column('sysinfo')

    with op.batch_alter_table('tmm34_idmaster', schema=None) as batch_op:
        batch_op.drop_column('useflg')
        batch_op.drop_column('loops')
        batch_op.drop_column('maxbillid')
        batch_op.drop_column('curbillid')
        batch_op.drop_column('idtypnm')
        batch_op.drop_column('idtyp')

    with op.batch_alter_table('tmm31_syscodes', schema=None) as batch_op:
        batch_op.drop_column('sysflg')

    with op.batch_alter_table('tmm22_customers_history', schema=None) as batch_op:
        batch_op.drop_column('device_change_id')
        batch_op.drop_column('change_reason')

    with op.batch_alter_table('tmm22_customers', schema=None) as batch_op:
        batch_op.drop_column('valid_until')
        batch_op.drop_column('preplan_id')
        batch_op.drop_column('verified_at')
        batch_op.drop_column('source_type')
        batch_op.drop_column('yj_money')
        batch_op.drop_column('is_contract')
        batch_op.drop_column('posstatus1')
        batch_op.drop_column('posstatus')
        batch_op.drop_column('jl_phoneno')
        batch_op.drop_column('jl_contactor')
        batch_op.drop_column('ordertype')
        batch_op.drop_column('levels')
        batch_op.drop_column('replacedate')
        batch_op.drop_column('opendate')
        batch_op.drop_column('custrnm')
        batch_op.drop_column('systemcode')
        batch_op.drop_column('adr3g')
        batch_op.drop_column('card3g')
        batch_op.drop_column('ad_video')
        batch_op.drop_column('s_status')
        batch_op.drop_column('soft_edition')
        batch_op.drop_column('data_base')
        batch_op.drop_column('opersystem')
        batch_op.drop_column('pos_n')
        batch_op.drop_column('area')
        batch_op.drop_column('location')
        batch_op.drop_column('backup')
        batch_op.drop_column('parentcd')
        batch_op.drop_column('bankaccno')
        batch_op.drop_column('banknm')
        batch_op.drop_column('taxno')
        batch_op.drop_column('faxno')
        batch_op.drop_column('zipcd')
        batch_op.drop_column('cust_brcd')
        batch_op.drop_column('cust_anm')

    with op.batch_alter_table('tmm21_custclass', schema=None) as batch_op:
        batch_op.drop_column('useflg')
        batch_op.drop_column('childflg')
        batch_op.drop_column('classtyp')

    with op.batch_alter_table('tmm19_suppliers', schema=None) as batch_op:
        batch_op.drop_column('agreements')
        batch_op.drop_column('suppinfo')
        batch_op.drop_column('pcrep')
        batch_op.drop_column('bankaccno')
        batch_op.drop_column('banknm')
        batch_op.drop_column('taxno')
        batch_op.drop_column('faxno')
        batch_op.drop_column('phoneno')
        batch_op.drop_column('zipcd')
        batch_op.drop_column('scale')
        batch_op.drop_column('custbrcd')
        batch_op.drop_column('custanm')
        batch_op.drop_column('custnm')
        batch_op.drop_column('custcd')

    with op.batch_alter_table('tmm18_supplierclass', schema=None) as batch_op:
        batch_op.drop_column('useflg')
        batch_op.drop_column('childflg')
        batch_op.drop_column('parent')
        batch_op.drop_column('classtyp')

    with op.batch_alter_table('tmm12_items', schema=None) as batch_op:
        batch_op.drop_column('consume')
        batch_op.drop_column('purchasetyp')
        batch_op.drop_column('typflg')
        batch_op.drop_column('backup')
        batch_op.drop_column('oldperiod')
        batch_op.drop_column('newperiod')
        batch_op.drop_column('minorder')
        batch_op.drop_column('lowerlimit')
        batch_op.drop_column('upperlimit')
        batch_op.drop_column('keeper')
        batch_op.drop_column('pcrep')
        batch_op.drop_column('wunit')
        batch_op.drop_column('citycd')
        batch_op.drop_column('provincecd')
        batch_op.drop_column('countrycd')
        batch_op.drop_column('itemsize')
        batch_op.drop_column('itembrcd')
        batch_op.drop_column('itemanm')

    with op.batch_alter_table('tmm11_itemclass', schema=None) as batch_op:
        batch_op.drop_column('useflg')
        batch_op.drop_column('childflg')
        batch_op.drop_column('classtyp')

    with op.batch_alter_table('tmm01_company', schema=None) as batch_op:
        batch_op.drop_column('maintenance')
        batch_op.drop_column('produce')
        batch_op.drop_column('mailcd')
        batch_op.drop_column('useflg')
        batch_op.drop_column('opendate')
        batch_op.drop_column('taxno')
        batch_op.drop_column('bankaccno')
        batch_op.drop_column('banknm')
        batch_op.drop_column('faxno')
        batch_op.drop_column('telex')
        batch_op.drop_column('leader')

    with op.batch_alter_table('tmc71_sysparm', schema=None) as batch_op:
        batch_op.drop_column('centralwarehouse')
        batch_op.drop_column('shopbilltype')
        batch_op.drop_column('allowmultilogon')
        batch_op.drop_column('soinvaliddays')
        batch_op.drop_column('poinvaliddays')
        batch_op.drop_column('invoicesharepath')
        batch_op.drop_column('autobackpath')
        batch_op.drop_column('costtype')
        batch_op.drop_column('pk')

    with op.batch_alter_table('tmc41_acclog', schema=None) as batch_op:
        batch_op.drop_column('startdate')

    with op.batch_alter_table('tmc31_groupright', schema=None) as batch_op:
        batch_op.drop_column('useflg')
        batch_op.drop_column('scale')

    with op.batch_alter_table('tmc13_users', schema=None) as batch_op:
        batch_op.drop_column('useflg')
        batch_op.drop_column('credamt')
        batch_op.drop_column('passwd')

    with op.batch_alter_table('tmc12_groups', schema=None) as batch_op:
        batch_op.drop_column('useflg')

    with op.batch_alter_table('tmc11_departments', schema=None) as batch_op:
        batch_op.drop_column('useflg')
        batch_op.drop_column('childflg')
        batch_op.drop_column('leader')
        batch_op.drop_column('parent')
        batch_op.drop_column('levelcd')

    with op.batch_alter_table('tmc03_usermenus', schema=None) as batch_op:
        batch_op.drop_column('useflg')
        batch_op.drop_column('ordno')

    with op.batch_alter_table('tmc02_menusdt', schema=None) as batch_op:
        batch_op.drop_column('useflg')

    with op.batch_alter_table('tmc01_menus', schema=None) as batch_op:
        batch_op.drop_column('useflg')
        batch_op.drop_column('childflg')
        batch_op.drop_column('openflg')
        batch_op.drop_column('ordno')
        batch_op.drop_column('picname')
        batch_op.drop_column('parent')
        batch_op.drop_column('levelcd')

    with op.batch_alter_table('tkq02_attendancecount', schema=None) as batch_op:
        batch_op.drop_column('updator')
        batch_op.drop_column('update_time')
        batch_op.drop_column('imp_date')
        batch_op.drop_column('imp_num')
        batch_op.drop_column('memo')

    with op.batch_alter_table('tkq01_attendance', schema=None) as batch_op:
        batch_op.drop_column('updator')
        batch_op.drop_column('update_time')

    with op.batch_alter_table('tit29_noclose_track', schema=None) as batch_op:
        batch_op.drop_column('cause_mian')

    with op.batch_alter_table('tit11_maintenance_attc', schema=None) as batch_op:
        batch_op.drop_column('attc')

    with op.batch_alter_table('tit10_pos_detail', schema=None) as batch_op:
        batch_op.drop_column('creator')
        batch_op.drop_column('create_time')

    with op.batch_alter_table('tit04_archivecode', schema=None) as batch_op:
        batch_op.drop_column('uncheck')

    # ### end Alembic commands ###
