"""eid_track_refid_extend_to_20

Revision ID: b181717d589f
Revises: 283de401b181
Create Date: 2026-07-01 15:18:25.114277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b181717d589f'
down_revision = '283de401b181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tmm43_eid_track', schema=None) as batch_op:
        batch_op.alter_column('refid',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=20),
               existing_comment='关联单号',
               existing_nullable=True)
        batch_op.alter_column('n_refid',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=20),
               existing_comment='新关联单号',
               existing_nullable=True)

    with op.batch_alter_table('tmm61_deposit_posmodel', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='⚠️已废弃。押金/售价→tip01_price(busityp=40/10)，在产/停产→tmm41_bom.useflg'
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tmm61_deposit_posmodel', schema=None) as batch_op:
        batch_op.create_table_comment(
        '⚠️已废弃。押金/售价→tip01_price(busityp=40/10)，在产/停产→tmm41_bom.useflg',
        existing_comment=None
    )

    with op.batch_alter_table('tmm43_eid_track', schema=None) as batch_op:
        batch_op.alter_column('n_refid',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=8),
               existing_comment='新关联单号',
               existing_nullable=True)
        batch_op.alter_column('refid',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=8),
               existing_comment='关联单号',
               existing_nullable=True)

    # ### end Alembic commands ###
