"""add_country_province_city_town_and_customer_region_cols

Revision ID: c08d02f7f9f6
Revises: eb79e751c8ce
Create Date: 2026-05-10 14:57:57.360524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c08d02f7f9f6'
down_revision = 'eb79e751c8ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tmm02_country',
    sa.Column('country_cd', sa.String(length=3), nullable=False, comment='国家代码'),
    sa.Column('country_nm', sa.String(length=50), nullable=False, comment='国家名称'),
    sa.Column('useflg', sa.String(length=1), nullable=True, comment='有效标志'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('country_cd')
    )
    op.create_table('tmm03_province',
    sa.Column('prvn_cd', sa.String(length=2), nullable=False, comment='省份代码'),
    sa.Column('prvn_nm', sa.String(length=50), nullable=False, comment='省份名称'),
    sa.Column('country_cd', sa.String(length=3), nullable=True, comment='国家代码'),
    sa.Column('useflg', sa.String(length=1), nullable=True, comment='有效标志'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['country_cd'], ['tmm02_country.country_cd'], ),
    sa.PrimaryKeyConstraint('prvn_cd')
    )
    op.create_table('tmm04_city',
    sa.Column('city_cd', sa.String(length=4), nullable=False, comment='城市代码'),
    sa.Column('city_nm', sa.String(length=50), nullable=False, comment='城市名称'),
    sa.Column('prvn_cd', sa.String(length=2), nullable=True, comment='省份代码'),
    sa.Column('useflg', sa.String(length=1), nullable=True, comment='有效标志'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prvn_cd'], ['tmm03_province.prvn_cd'], ),
    sa.PrimaryKeyConstraint('city_cd')
    )
    op.create_table('tmm05_town',
    sa.Column('town_cd', sa.String(length=4), nullable=False, comment='区县代码'),
    sa.Column('town_nm', sa.String(length=50), nullable=False, comment='区县名称'),
    sa.Column('city_cd', sa.String(length=4), nullable=True, comment='城市代码'),
    sa.Column('useflg', sa.String(length=1), nullable=True, comment='有效标志'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['city_cd'], ['tmm04_city.city_cd'], ),
    sa.PrimaryKeyConstraint('town_cd')
    )
    with op.batch_alter_table('tmm22_customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_cd', sa.String(length=3), nullable=True, comment='国家代码'))
        batch_op.add_column(sa.Column('prvn_cd', sa.String(length=2), nullable=True, comment='省份代码'))
        batch_op.add_column(sa.Column('city_cd', sa.String(length=4), nullable=True, comment='城市代码'))
        batch_op.add_column(sa.Column('town_cd', sa.String(length=4), nullable=True, comment='区县代码'))
        batch_op.alter_column('parentcd',
               existing_type=sa.VARCHAR(length=8),
               comment='上级客户编码',
               existing_comment='管理单位编码（关联 tmm21_custclass）',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tmm22_customers', schema=None) as batch_op:
        batch_op.alter_column('parentcd',
               existing_type=sa.VARCHAR(length=8),
               comment='管理单位编码（关联 tmm21_custclass）',
               existing_comment='上级客户编码',
               existing_nullable=True)
        batch_op.drop_column('town_cd')
        batch_op.drop_column('city_cd')
        batch_op.drop_column('prvn_cd')
        batch_op.drop_column('country_cd')

    op.drop_table('tmm05_town')
    op.drop_table('tmm04_city')
    op.drop_table('tmm03_province')
    op.drop_table('tmm02_country')
    # ### end Alembic commands ###
