"""tmm22_customers新增geo四级国标地理字段_废弃老地理字段

Revision ID: c7c7a3e701f2
Revises: 60776f4f1ab1
Create Date: 2026-07-04 18:07:29.696117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c7a3e701f2'
down_revision = '60776f4f1ab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tmm22_customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geo_prvn_cd', sa.String(length=6), nullable=True, comment='国标省级代码（关联geo_province.code，如31=上海市）'))
        batch_op.add_column(sa.Column('geo_city_cd', sa.String(length=6), nullable=True, comment='国标地级市代码（关联geo_city.code，如3101=上海市辖区）'))
        batch_op.add_column(sa.Column('geo_area_cd', sa.String(length=6), nullable=True, comment='国标区县代码（关联geo_area.code，如310101=黄浦区）'))
        batch_op.add_column(sa.Column('geo_street_cd', sa.String(length=12), nullable=True, comment='国标街道代码（关联geo_street.code，如310101002=南京东路街道）'))
        batch_op.alter_column('country_cd',
               existing_type=sa.VARCHAR(length=3),
               comment='【废弃】国家代码（老系统自定义短码，如191=中国），由geo_prvn_cd等替代，待删除',
               existing_comment='国家代码',
               existing_nullable=True)
        batch_op.alter_column('prvn_cd',
               existing_type=sa.VARCHAR(length=2),
               comment='【废弃】省份代码（老系统自定义短码，如09=上海），由geo_prvn_cd替代，待删除',
               existing_comment='省份代码',
               existing_nullable=True)
        batch_op.alter_column('city_cd',
               existing_type=sa.VARCHAR(length=4),
               comment='【废弃】城市/区代码（老系统自定义短码，如0121=浦东新区），由geo_city_cd/geo_area_cd替代，待删除',
               existing_comment='城市代码',
               existing_nullable=True)
        batch_op.alter_column('town_cd',
               existing_type=sa.VARCHAR(length=4),
               comment='【废弃】区县代码（老系统自定义短码，迁移后全为空），由geo_area_cd替代，待删除',
               existing_comment='区县代码',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tmm22_customers', schema=None) as batch_op:
        batch_op.alter_column('town_cd',
               existing_type=sa.VARCHAR(length=4),
               comment='区县代码',
               existing_comment='【废弃】区县代码（老系统自定义短码，迁移后全为空），由geo_area_cd替代，待删除',
               existing_nullable=True)
        batch_op.alter_column('city_cd',
               existing_type=sa.VARCHAR(length=4),
               comment='城市代码',
               existing_comment='【废弃】城市/区代码（老系统自定义短码，如0121=浦东新区），由geo_city_cd/geo_area_cd替代，待删除',
               existing_nullable=True)
        batch_op.alter_column('prvn_cd',
               existing_type=sa.VARCHAR(length=2),
               comment='省份代码',
               existing_comment='【废弃】省份代码（老系统自定义短码，如09=上海），由geo_prvn_cd替代，待删除',
               existing_nullable=True)
        batch_op.alter_column('country_cd',
               existing_type=sa.VARCHAR(length=3),
               comment='国家代码',
               existing_comment='【废弃】国家代码（老系统自定义短码，如191=中国），由geo_prvn_cd等替代，待删除',
               existing_nullable=True)
        batch_op.drop_column('geo_street_cd')
        batch_op.drop_column('geo_area_cd')
        batch_op.drop_column('geo_city_cd')
        batch_op.drop_column('geo_prvn_cd')

    # ### end Alembic commands ###
