"""add_jwt_log_upload_sysparm_cols

Revision ID: db6aef9f5043
Revises: c08d02f7f9f6
Create Date: 2026-05-11 15:09:51.514297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db6aef9f5043'
down_revision = 'c08d02f7f9f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tmc71_sysparm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jwt_expiration_seconds', sa.Integer(), nullable=True, comment='JWT超时(秒)'))
        batch_op.add_column(sa.Column('log_retention_days', sa.Integer(), nullable=True, comment='日志保留天数'))
        batch_op.add_column(sa.Column('max_upload_size_mb', sa.Integer(), nullable=True, comment='上传大小限制(MB)'))

    with op.batch_alter_table('tmm31_syscodes', schema=None) as batch_op:
        batch_op.alter_column('memo',
               existing_type=sa.VARCHAR(length=60),
               comment='说明',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tmm31_syscodes', schema=None) as batch_op:
        batch_op.alter_column('memo',
               existing_type=sa.VARCHAR(length=60),
               comment=None,
               existing_comment='说明',
               existing_nullable=True)

    with op.batch_alter_table('tmc71_sysparm', schema=None) as batch_op:
        batch_op.drop_column('max_upload_size_mb')
        batch_op.drop_column('log_retention_days')
        batch_op.drop_column('jwt_expiration_seconds')

    # ### end Alembic commands ###
