"""补全14张业务必须表（设备EID/BOM/质检/库存明细/调拨/采购验收）

Revision ID: eb79e751c8ce
Revises: 9830fca8c37b
Create Date: 2026-05-06 04:36:42.184767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb79e751c8ce'
down_revision = '9830fca8c37b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tiv11_detail',
    sa.Column('itemcd', sa.String(length=8), nullable=False, comment='物料编码'),
    sa.Column('whcd', sa.String(length=2), nullable=True, comment='仓库编码'),
    sa.Column('itemtyp', sa.String(length=2), nullable=True, comment='物料类型'),
    sa.Column('storeqty', sa.Numeric(precision=12, scale=0), nullable=True, comment='库存数量'),
    sa.Column('opercd', sa.String(length=6), nullable=True, comment='操作员'),
    sa.Column('gendate', sa.DateTime(), nullable=True, comment='创建日期'),
    sa.Column('useflg', sa.String(length=1), nullable=True, comment='有效标志'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('itemcd')
    )
    op.create_table('tmm24_custitems',
    sa.Column('itemcd', sa.String(length=6), nullable=False, comment='物料编码'),
    sa.Column('custcd', sa.String(length=8), nullable=False, comment='客户编码'),
    sa.Column('dfltflg', sa.String(length=1), nullable=True, comment='默认标志'),
    sa.Column('opercd', sa.String(length=6), nullable=True, comment='操作员'),
    sa.Column('gendate', sa.DateTime(), nullable=True, comment='创建日期'),
    sa.Column('upddate', sa.DateTime(), nullable=True, comment='更新日期'),
    sa.Column('useflg', sa.String(length=1), nullable=True, comment='有效标志'),
    sa.Column('delivercycle', sa.Numeric(), nullable=True, comment='配送周期'),
    sa.Column('servicecycle', sa.Numeric(), nullable=True, comment='服务周期'),
    sa.Column('guaranteeperiod', sa.Numeric(), nullable=True, comment='保修期'),
    sa.Column('backup', sa.String(length=200), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('itemcd', 'custcd')
    )
    op.create_table('tmm36_cust_ve_rl',
    sa.Column('custcd', sa.String(length=8), nullable=False, comment='客户编码'),
    sa.Column('eid', sa.String(length=13), nullable=False, comment='设备序列号'),
    sa.Column('itemcd', sa.String(length=6), nullable=False, comment='物料编码'),
    sa.Column('startdate', sa.DateTime(), nullable=True, comment='开始日期'),
    sa.Column('sysinfo', sa.String(length=30), nullable=True, comment='系统信息'),
    sa.Column('softinfo', sa.String(length=30), nullable=True, comment='软件信息'),
    sa.Column('posupddate', sa.DateTime(), nullable=True, comment='POS更新日期'),
    sa.Column('posinfo', sa.String(length=30), nullable=True, comment='POS信息'),
    sa.Column('area', sa.String(length=2), nullable=True, comment='区域'),
    sa.Column('status', sa.String(length=1), nullable=True, comment='状态'),
    sa.Column('typflg', sa.String(length=2), nullable=True, comment='类型标志'),
    sa.Column('maintenancedate', sa.String(length=6), nullable=True, comment='维护日期'),
    sa.Column('maintenancetyp', sa.DateTime(), nullable=True, comment='维护类型'),
    sa.Column('opercd', sa.String(length=6), nullable=True, comment='操作员'),
    sa.Column('gendate', sa.DateTime(), nullable=True, comment='创建日期'),
    sa.Column('upddate', sa.DateTime(), nullable=True, comment='更新日期'),
    sa.Column('useflg', sa.String(length=1), nullable=True, comment='有效标志'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('custcd', 'eid', 'itemcd')
    )
    op.create_table('tmm41_bom',
    sa.Column('bomcd', sa.String(length=6), nullable=False, comment='BOM编码'),
    sa.Column('bomnm', sa.String(length=50), nullable=True, comment='BOM名称'),
    sa.Column('opercd', sa.String(length=6), nullable=True, comment='操作员'),
    sa.Column('gendate', sa.DateTime(), nullable=True, comment='创建日期'),
    sa.Column('upddate', sa.DateTime(), nullable=True, comment='更新日期'),
    sa.Column('useflg', sa.String(length=1), nullable=True, comment='有效标志'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('bomcd')
    )
    op.create_table('tmm43_eid',
    sa.Column('itemcd', sa.String(length=6), nullable=False, comment='物料编码'),
    sa.Column('eid', sa.String(length=13), nullable=False, comment='设备序列号'),
    sa.Column('opercd', sa.String(length=6), nullable=True, comment='操作员'),
    sa.Column('gendate', sa.DateTime(), nullable=True, comment='创建日期'),
    sa.Column('useflg', sa.String(length=1), nullable=True, comment='有效标志'),
    sa.Column('etyp', sa.String(length=1), nullable=True, comment='设备类型'),
    sa.Column('sflg', sa.String(length=1), nullable=True, comment='状态标志'),
    sa.Column('refid', sa.String(length=8), nullable=True, comment='关联单号'),
    sa.Column('qcflg', sa.String(length=2), nullable=True, comment='质检标志'),
    sa.Column('whcd', sa.String(length=2), nullable=True, comment='仓库编码'),
    sa.Column('prddate', sa.DateTime(), nullable=True, comment='生产日期'),
    sa.Column('itemtyp', sa.String(length=2), nullable=True, comment='物料类型'),
    sa.Column('new_old', sa.String(length=1), nullable=True, comment='新旧标志'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='备注'),
    sa.Column('manuf_seq', sa.String(length=100), nullable=True, comment='制造序列号'),
    sa.Column('old_degree', sa.Numeric(), nullable=True, comment='旧化程度'),
    sa.Column('isunit', sa.String(length=1), nullable=True, comment='是否整机'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('itemcd', 'eid')
    )
    op.create_table('tmm43_eid_track',
    sa.Column('seqno', sa.Integer(), autoincrement=True, nullable=False, comment='序号'),
    sa.Column('type', sa.String(length=1), nullable=True, comment='变更类型'),
    sa.Column('change_date', sa.DateTime(), nullable=True, comment='变更日期'),
    sa.Column('itemcd', sa.String(length=6), nullable=True, comment='物料编码'),
    sa.Column('eid', sa.String(length=13), nullable=True, comment='设备序列号'),
    sa.Column('opercd', sa.String(length=6), nullable=True, comment='操作员'),
    sa.Column('gendate', sa.DateTime(), nullable=True, comment='创建日期'),
    sa.Column('useflg', sa.String(length=1), nullable=True, comment='有效标志'),
    sa.Column('etyp', sa.String(length=1), nullable=True, comment='设备类型'),
    sa.Column('sflg', sa.String(length=1), nullable=True, comment='状态标志'),
    sa.Column('refid', sa.String(length=8), nullable=True, comment='关联单号'),
    sa.Column('qcflg', sa.String(length=2), nullable=True, comment='质检标志'),
    sa.Column('whcd', sa.String(length=2), nullable=True, comment='仓库编码'),
    sa.Column('prddate', sa.DateTime(), nullable=True, comment='生产日期'),
    sa.Column('itemtyp', sa.String(length=2), nullable=True, comment='物料类型'),
    sa.Column('new_old', sa.String(length=1), nullable=True, comment='新旧标志'),
    sa.Column('n_sflg', sa.String(length=1), nullable=True, comment='新状态标志'),
    sa.Column('n_refid', sa.String(length=8), nullable=True, comment='新关联单号'),
    sa.Column('n_qcflg', sa.String(length=2), nullable=True, comment='新质检标志'),
    sa.Column('n_whcd', sa.String(length=2), nullable=True, comment='新仓库编码'),
    sa.Column('n_prddate', sa.DateTime(), nullable=True, comment='新生产日期'),
    sa.Column('n_itemtyp', sa.String(length=2), nullable=True, comment='新物料类型'),
    sa.Column('n_new_old', sa.String(length=1), nullable=True, comment='新新旧标志'),
    sa.Column('n_itemcd', sa.String(length=6), nullable=True, comment='新物料编码'),
    sa.Column('n_etyp', sa.String(length=1), nullable=True, comment='新设备类型'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='备注'),
    sa.Column('n_remark', sa.String(length=200), nullable=True, comment='新备注'),
    sa.Column('manuf_seq', sa.String(length=100), nullable=True, comment='制造序列号'),
    sa.Column('n_manf_seq', sa.String(length=100), nullable=True, comment='新制造序列号'),
    sa.Column('old_degree', sa.Numeric(), nullable=True, comment='旧化程度'),
    sa.Column('n_old_degree', sa.Numeric(), nullable=True, comment='新旧化程度'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('seqno')
    )
    op.create_table('tmm62_asset_attrib_list',
    sa.Column('itemcd', sa.String(length=10), nullable=False, comment='物料编码'),
    sa.Column('eid', sa.String(length=30), nullable=False, comment='设备序列号'),
    sa.Column('c_type', sa.String(length=10), nullable=True, comment='分类类型'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('c_address', sa.String(length=200), nullable=True, comment='地址'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='备注'),
    sa.Column('asset_type', sa.String(length=10), nullable=True, comment='资产类型'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('itemcd', 'eid')
    )
    op.create_table('tmp14_checkindt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('inbillid', sa.String(length=8), nullable=True, comment='入库单号'),
    sa.Column('whcd', sa.String(length=2), nullable=True, comment='仓库编码'),
    sa.Column('lineno', sa.Integer(), nullable=True, comment='行号'),
    sa.Column('itemtyp', sa.String(length=2), nullable=True, comment='物料类型'),
    sa.Column('itemcd', sa.String(length=6), nullable=True, comment='物料编码'),
    sa.Column('prddate', sa.DateTime(), nullable=True, comment='生产日期'),
    sa.Column('batchid', sa.String(length=50), nullable=True, comment='批次号'),
    sa.Column('inqty', sa.Numeric(precision=12, scale=0), nullable=True, comment='入库数量'),
    sa.Column('reflineno', sa.Integer(), nullable=True, comment='关联行号'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tqc10_result',
    sa.Column('qcbillid', sa.String(length=8), nullable=False, comment='质检单号'),
    sa.Column('optyp', sa.String(length=2), nullable=True, comment='操作类型'),
    sa.Column('refbillid', sa.String(length=8), nullable=True, comment='关联单号'),
    sa.Column('itemcd', sa.String(length=6), nullable=True, comment='物料编码'),
    sa.Column('eid', sa.String(length=13), nullable=True, comment='设备序列号'),
    sa.Column('opercd', sa.String(length=6), nullable=True, comment='操作员'),
    sa.Column('gendate', sa.DateTime(), nullable=True, comment='创建日期'),
    sa.Column('upddate', sa.DateTime(), nullable=True, comment='更新日期'),
    sa.Column('useflg', sa.String(length=1), nullable=True, comment='有效标志'),
    sa.Column('auditman', sa.String(length=6), nullable=True, comment='审核人'),
    sa.Column('auditflg', sa.String(length=1), nullable=True, comment='审核标志'),
    sa.Column('auditdate', sa.DateTime(), nullable=True, comment='审核日期'),
    sa.Column('qcstatus', sa.String(length=2), nullable=True, comment='质检状态'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('qcbillid')
    )
    op.create_table('ttx01_txkmg',
    sa.Column('txkno', sa.String(length=30), nullable=False, comment='调拨科目编号'),
    sa.Column('commmode', sa.String(length=10), nullable=True, comment='通讯方式'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.Column('by1', sa.String(length=10), nullable=True, comment='备用字段1'),
    sa.Column('by2', sa.String(length=10), nullable=True, comment='备用字段2'),
    sa.Column('opercd', sa.String(length=6), nullable=True, comment='操作员'),
    sa.Column('upddate', sa.DateTime(), nullable=True, comment='更新日期'),
    sa.Column('useflg', sa.String(length=1), nullable=True, comment='有效标志'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('txkno')
    )
    op.create_table('tiv12_detaildt',
    sa.Column('seqno', sa.Integer(), autoincrement=True, nullable=False, comment='流水号'),
    sa.Column('itemcd', sa.String(length=8), nullable=True, comment='物料编码'),
    sa.Column('whcd', sa.String(length=2), nullable=True, comment='仓库编码'),
    sa.Column('itemtyp', sa.String(length=2), nullable=True, comment='物料类型'),
    sa.Column('billid', sa.String(length=8), nullable=True, comment='单号'),
    sa.Column('invdate', sa.DateTime(), nullable=True, comment='库存日期'),
    sa.Column('invtyp', sa.String(length=1), nullable=True, comment='出入库类型'),
    sa.Column('itemqty', sa.Numeric(precision=12, scale=0), nullable=True, comment='本次数量'),
    sa.Column('storeqty', sa.Numeric(precision=12, scale=0), nullable=True, comment='库存数量'),
    sa.Column('opercd', sa.String(length=6), nullable=True, comment='操作员'),
    sa.Column('gendate', sa.DateTime(), nullable=True, comment='创建日期'),
    sa.Column('useflg', sa.String(length=1), nullable=True, comment='有效标志'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['itemcd'], ['tiv11_detail.itemcd'], ),
    sa.PrimaryKeyConstraint('seqno')
    )
    op.create_table('tmm42_bomdt',
    sa.Column('bomcd', sa.String(length=6), nullable=False, comment='BOM编码'),
    sa.Column('itemcd', sa.String(length=6), nullable=False, comment='物料编码'),
    sa.Column('bomqty', sa.Numeric(precision=12, scale=0), nullable=True, comment='BOM数量'),
    sa.Column('opercd', sa.String(length=6), nullable=True, comment='操作员'),
    sa.Column('gendate', sa.DateTime(), nullable=True, comment='创建日期'),
    sa.Column('upddate', sa.DateTime(), nullable=True, comment='更新日期'),
    sa.Column('itemtyp', sa.String(length=1), nullable=True, comment='物料类型'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bomcd'], ['tmm41_bom.bomcd'], ),
    sa.PrimaryKeyConstraint('bomcd', 'itemcd')
    )
    op.create_table('tqc11_resultdt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('qcbillid', sa.String(length=8), nullable=False, comment='质检单号'),
    sa.Column('itemcd', sa.String(length=6), nullable=False, comment='物料编码'),
    sa.Column('itemtyp', sa.String(length=2), nullable=True, comment='物料类型'),
    sa.Column('prddate', sa.DateTime(), nullable=True, comment='生产日期'),
    sa.Column('qcqty', sa.Numeric(precision=12, scale=0), nullable=True, comment='质检数量'),
    sa.Column('qcstatus', sa.String(length=2), nullable=True, comment='质检状态'),
    sa.Column('inqty', sa.Numeric(precision=12, scale=0), nullable=True, comment='入库数量'),
    sa.Column('opercd', sa.String(length=6), nullable=True, comment='操作员'),
    sa.Column('gendate', sa.DateTime(), nullable=True, comment='创建日期'),
    sa.Column('useflg', sa.String(length=1), nullable=True, comment='有效标志'),
    sa.Column('lineno', sa.Integer(), nullable=True, comment='行号'),
    sa.Column('fault_desc', sa.String(length=50), nullable=True, comment='故障描述'),
    sa.Column('maintain_desc', sa.String(length=50), nullable=True, comment='维修描述'),
    sa.Column('inspector', sa.String(length=8), nullable=True, comment='检验员'),
    sa.Column('qc_source', sa.String(length=1), nullable=True, comment='质检来源'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['qcbillid'], ['tqc10_result.qcbillid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tqc11_resulteid',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('qcbillid', sa.String(length=8), nullable=False, comment='质检单号'),
    sa.Column('itemcd', sa.String(length=6), nullable=True, comment='物料编码'),
    sa.Column('itemtyp', sa.String(length=2), nullable=True, comment='物料类型'),
    sa.Column('prddate', sa.DateTime(), nullable=True, comment='生产日期'),
    sa.Column('qcqty', sa.Numeric(precision=12, scale=0), nullable=True, comment='质检数量'),
    sa.Column('qcstatus', sa.String(length=2), nullable=True, comment='质检状态'),
    sa.Column('inqty', sa.Numeric(precision=12, scale=0), nullable=True, comment='入库数量'),
    sa.Column('eid', sa.String(length=13), nullable=False, comment='设备序列号'),
    sa.Column('gendate', sa.DateTime(), nullable=True, comment='创建日期'),
    sa.Column('upddate', sa.DateTime(), nullable=True, comment='更新日期'),
    sa.Column('opercd', sa.String(length=6), nullable=True, comment='操作员'),
    sa.Column('lineno', sa.Integer(), nullable=True, comment='行号'),
    sa.Column('fault_desc', sa.String(length=100), nullable=True, comment='故障描述'),
    sa.Column('maintain_desc', sa.String(length=100), nullable=True, comment='维修描述'),
    sa.Column('inspector', sa.String(length=8), nullable=True, comment='检验员'),
    sa.Column('qc_source', sa.String(length=1), nullable=True, comment='质检来源'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.Column('manuf_seq', sa.String(length=100), nullable=True, comment='制造序列号'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['qcbillid'], ['tqc10_result.qcbillid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tip03_adjprice', schema=None) as batch_op:
        batch_op.alter_column('useflg',
               existing_type=sa.VARCHAR(length=1),
               comment='有效标志（AdjustPrice）',
               existing_comment='有效标志',
               existing_nullable=True)

    with op.batch_alter_table('tmm34_idmaster', schema=None) as batch_op:
        batch_op.alter_column('useflg',
               existing_type=sa.VARCHAR(length=1),
               comment='有效标志（IdMaster）',
               existing_comment='有效标志',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tmm34_idmaster', schema=None) as batch_op:
        batch_op.alter_column('useflg',
               existing_type=sa.VARCHAR(length=1),
               comment='有效标志',
               existing_comment='有效标志（IdMaster）',
               existing_nullable=True)

    with op.batch_alter_table('tip03_adjprice', schema=None) as batch_op:
        batch_op.alter_column('useflg',
               existing_type=sa.VARCHAR(length=1),
               comment='有效标志',
               existing_comment='有效标志（AdjustPrice）',
               existing_nullable=True)

    op.drop_table('tqc11_resulteid')
    op.drop_table('tqc11_resultdt')
    op.drop_table('tmm42_bomdt')
    op.drop_table('tiv12_detaildt')
    op.drop_table('ttx01_txkmg')
    op.drop_table('tqc10_result')
    op.drop_table('tmp14_checkindt')
    op.drop_table('tmm62_asset_attrib_list')
    op.drop_table('tmm43_eid_track')
    op.drop_table('tmm43_eid')
    op.drop_table('tmm41_bom')
    op.drop_table('tmm36_cust_ve_rl')
    op.drop_table('tmm24_custitems')
    op.drop_table('tiv11_detail')
    # ### end Alembic commands ###
