"""1a: add business_mode/warranty_expire/service_responsibility fields

Revision ID: f1fd3e67c4a6
Revises: f3a4b5c6d7e9
Create Date: 2026-07-26 18:59:48.923589

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1fd3e67c4a6'
down_revision = 'f3a4b5c6d7e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 注：tmm43_eid_asset_owner_bak_20260726 备份表由人工删除，不在本迁移内
    with op.batch_alter_table('plan_cust', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_mode', sa.String(length=2), nullable=True, comment='业务模式（BM_S字典：01销售/02租赁/03借用/04代维/05寄售/06试用/07免费投放/08合作运营）'))

    with op.batch_alter_table('tit21_maintenance_dispatch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_responsibility', sa.String(length=2), nullable=True, comment='服务责任方（SR字典：01内部/02厂商/03代维）'))

    with op.batch_alter_table('tmm35_cust_pos_rl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_mode', sa.String(length=2), nullable=True, comment='业务模式（BM_S字典：01销售/02租赁/03借用/04代维/05寄售/06试用/07免费投放/08合作运营）'))

    with op.batch_alter_table('tmm43_eid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warranty_expire', sa.DateTime(), nullable=True, comment='保修到期日（install_date + 按 old_degree 取 newperiod/oldperiod，关单 L2 写入）'))
        batch_op.alter_column('asset_owner',
               existing_type=sa.VARCHAR(length=20),
               comment='资产所属方（OW码表：01商用电子/02通方信息/03门店资产/04海晟）',
               existing_comment='资产所属方（ZC码表：00通方资产/01门店资产/03自有资产）',
               existing_nullable=True,
               existing_server_default=sa.text("'CUSTOMER'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tmm43_eid', schema=None) as batch_op:
        batch_op.alter_column('asset_owner',
               existing_type=sa.VARCHAR(length=20),
               comment='资产所属方（ZC码表：00通方资产/01门店资产/03自有资产）',
               existing_comment='资产所属方（OW码表：01商用电子/02通方信息/03门店资产/04海晟）',
               existing_nullable=True,
               existing_server_default=sa.text("'CUSTOMER'::character varying"))
        batch_op.drop_column('warranty_expire')

    with op.batch_alter_table('tmm35_cust_pos_rl', schema=None) as batch_op:
        batch_op.drop_column('business_mode')

    with op.batch_alter_table('tit21_maintenance_dispatch', schema=None) as batch_op:
        batch_op.drop_column('service_responsibility')

    with op.batch_alter_table('plan_cust', schema=None) as batch_op:
        batch_op.drop_column('business_mode')

    # ### end Alembic commands ###
