
  CREATE UNIQUE INDEX "CCGL"."PK_TIT11_MAINTENANCE_ATTC" ON "CCGL"."TIT11_MAINTENANCE_ATTC" ("MAINTENANCE_ID", "BUSINESS_OPERATION_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "CCGL_DATA"

