
  CREATE UNIQUE INDEX "CCGL"."PK_TIT17_CUST_POS_DAILY" ON "CCGL"."TIT17_CUST_POS_DAILY" ("DAILY_MAINTENANCE_ID", "BUSINESS_OPERATION_ID", "TYPFLG")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 851968 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCGL_DATA"

