<template><div class="page"><div class="page-header"><h2>质检审核</h2><div><el-select v-model="s.auditflg" placeholder="审核状态" size="small" style="width:120px" clearable @change="load"><el-option label="草稿" value="0"/><el-option label="已审核" value="1"/><el-option label="已退回" value="8"/><el-option label="已作废" value="V"/></el-select></div></div><el-card shadow="never"><el-table :data="items" v-loading="loading" stripe size="small"><el-table-column prop="batch_id" label="批次号" width="110"/><el-table-column prop="refbillid" label="来源单据" width="120"/><el-table-column label="判定汇总" min-width="200"><template #default="{row}"><el-tag v-if="row.ga_count" type="success" size="small">GA:{{row.ga_count}}</el-tag><el-tag v-if="row.gb_count" type="success" size="small">GB:{{row.gb_count}}</el-tag><el-tag v-if="row.gc_count" type="success" size="small">GC:{{row.gc_count}}</el-tag><el-tag v-if="row.bf_count" type="danger" size="small">BF:{{row.bf_count}}</el-tag><el-tag v-if="row.bh_count" type="warning" size="small">BH:{{row.bh_count}}</el-tag><el-tag v-if="row.th_count" type="info" size="small">TH:{{row.th_count}}</el-tag></template></el-table-column><el-table-column prop="total_count" label="总数" width="60"/><el-table-column label="审核状态" width="80"><template #default="{row}"><el-tag v-if="row.auditflg==='1'" type="success" size="small">已审核</el-tag><el-tag v-else-if="row.auditflg==='8'" type="danger" size="small">已退回</el-tag><el-tag v-else-if="row.auditflg==='V'" type="info" size="small">已作废</el-tag><el-tag v-else type="warning" size="small">草稿</el-tag></template></el-table-column><el-table-column prop="gendate" label="日期" width="100"/><el-table-column label="操作" width="200"><template #default="{row}"><el-button v-if="row.auditflg!=='1'&&row.auditflg!=='V'" link type="primary" size="small" @click.stop="doAudit(row.batch_id)">审核通过</el-button><el-button v-if="row.auditflg!=='1'&&row.auditflg!=='V'" link type="danger" size="small" @click.stop="doReject(row.batch_id)">审核退回</el-button><el-button v-if="row.auditflg!=='1'&&row.auditflg!=='V'" link type="danger" size="small" @click.stop="handleVoid(row)">作废</el-button></template></el-table-column></el-table><AppPagination v-model:current-page="page" v-model:page-size="perPage" :total="total" style="margin-top:12px;justify-content:flex-end"/></el-card></div></template>

<script setup lang="ts">import {ref,reactive,onMounted,watch} from 'vue';import {ElMessage,ElMessageBox} from 'element-plus';import AppPagination from '@/components/common/AppPagination.vue';import {listQcBatches,auditQcBatch,voidQcBatch,type QcBatchItem} from '@/api/qc'
const items=ref<QcBatchItem[]>([])
const loading=ref(false);const page=ref(1);const perPage=ref(20);const total=ref(0)
const s=reactive({search:'',auditflg:''})
async function load(){loading.value=true;try{const params:Record<string,string>={page:String(page.value),per_page:String(perPage.value)};if(s.search)params.search=s.search;if(s.auditflg)params.auditflg=s.auditflg;const r=await listQcBatches(params);items.value=(r.data?.items||[]) as QcBatchItem[];total.value=r.data?.total||0}catch{items.value=[];total.value=0}finally{loading.value=false}}
async function doAudit(batchId:string){loading.value=true;try{await auditQcBatch(batchId,'1');ElMessage.success('批次审核通过');load()}catch(e:any){ElMessage.error(e?.response?.data?.message||'审核失败')}finally{loading.value=false}}
async function doReject(batchId:string){try{const{value:memo}=await ElMessageBox.prompt('请输入退回原因','审核退回',{confirmButtonText:'确认退回',cancelButtonText:'取消',type:'warning'});loading.value=true;await auditQcBatch(batchId,'8',memo||'');ElMessage.success('批次已退回');load()}catch{/*取消*/}finally{loading.value=false}}
async function handleVoid(row:QcBatchItem){try{await ElMessageBox.confirm(`确定作废批次 ${row.batch_id} 吗？`,'确认作废',{type:'warning'});loading.value=true;await voidQcBatch(row.batch_id);ElMessage.success('批次已作废');load()}catch{/*取消*/}finally{loading.value=false}}
async function doSearch(){page.value=1;load()}
watch([page,perPage],()=>{load()})
onMounted(load)
</script>
<style scoped>.page{padding:0}.page-header{display:flex;justify-content:space-between;margin-bottom:16px}.page-header h2{font-size:18px;font-weight:600;margin:0}</style>
