<template><div class="page"><div class="page-header"><h2>质检结果</h2><div style="display:flex;gap:8px"><el-button type="primary" size="small" @click="openCreate">录入质检</el-button></div></div><el-card shadow="never" style="margin-bottom:16px"><div class="search-bar"><div class="field"><label>搜索</label><el-input v-model="s.search" placeholder="单号/物料/SN" size="small" style="width:180px" clearable @keyup.enter="doSearch"/></div><el-button type="primary" size="small" @click="doSearch" style="margin-left:auto">查询</el-button></div></el-card><el-card shadow="never" style="margin-bottom:16px" v-if="stats.length"><div style="display:flex;gap:16px;flex-wrap:wrap"><div v-for="st in stats" :key="st.qcstatus" style="text-align:center;padding:8px 16px;background:#f5f7fa;border-radius:6px"><div style="font-size:20px;font-weight:600;color:#409eff">{{ st.cnt }}</div><div style="font-size:12px;color:#909399">{{ qcLabel(st.qcstatus) }}</div></div></div></el-card><el-card shadow="never"><el-table :data="items" v-loading="loading" stripe size="small" highlight-current-row @row-click="openDrawer"><el-table-column prop="qcbillid" label="质检单号" width="110"/><el-table-column prop="itemcd" label="物料" width="90"/><el-table-column prop="eid" label="设备SN" width="140"/><el-table-column label="质检状态" width="80"><template #default="{row}"><el-tag :type="qcTagType(row.qcstatus)" size="small">{{ qcLabel(row.qcstatus) }}</el-tag></template></el-table-column><el-table-column label="审核" width="70"><template #default="{row}"><el-tag :type="row.auditflg==='1'?'success':'info'" size="small">{{ row.auditflg==='1'?'已审':'待审' }}</el-tag></template></el-table-column><el-table-column prop="refbillid" label="关联单号" width="110"/><el-table-column prop="gendate" label="日期" width="100"/><el-table-column label="操作员" width="80"><template #default="{row}">{{ userName(row.opercd) }}</template></el-table-column></el-table><AppPagination v-model:current-page="page" v-model:page-size="perPage" :total="total" style="margin-top:12px;justify-content:flex-end"/></el-card>

    <el-dialog :title="'质检单 — '+(detail?.qcbillid||'')" v-model="drawer" width="550px"><template v-if="detail"><el-descriptions :column="2" border size="small"><el-descriptions-item label="单号">{{ detail.qcbillid }}</el-descriptions-item><el-descriptions-item label="物料">{{ detail.itemcd }}</el-descriptions-item><el-descriptions-item label="设备SN">{{ detail.eid||'-' }}</el-descriptions-item><el-descriptions-item label="状态">{{ qcLabel(detail.qcstatus) }}</el-descriptions-item><el-descriptions-item label="关联单号">{{ detail.refbillid||'-' }}</el-descriptions-item><el-descriptions-item label="操作员">{{ userName(detail.opercd) }}</el-descriptions-item><el-descriptions-item label="审核人">{{ detail.auditman||'-' }}</el-descriptions-item><el-descriptions-item label="审核日期">{{ detail.auditdate||'-' }}</el-descriptions-item><el-descriptions-item label="日期">{{ detail.gendate }}</el-descriptions-item><el-descriptions-item label="备注" :span="2">{{ detail.memo||'-' }}</el-descriptions-item></el-descriptions><div style="margin-top:12px;display:flex;gap:8px;justify-content:flex-end"><el-button v-if="detail.auditflg!=='1'" type="success" size="small" @click="doAudit(detail.qcbillid)">审核通过</el-button></div></template></el-dialog>

    <el-dialog title="录入质检结果" v-model="creating" width="450px" @closed="resetForm"><el-form :model="form" label-width="80px" size="small"><el-form-item label="物料编码" required><el-input v-model="form.itemcd" placeholder="输入物料编码"/></el-form-item><el-form-item label="设备SN"><el-input v-model="form.eid" placeholder="设备序列号（选填）"/></el-form-item><el-form-item label="关联单号"><el-input v-model="form.refbillid" placeholder="关联入库单/采购单"/></el-form-item><el-form-item label="质检状态"><el-select v-model="form.qcstatus" style="width:100%"><el-option label="合格" value="1"/><el-option label="不合格" value="0"/></el-select></el-form-item><el-form-item label="备注"><el-input v-model="form.memo" type="textarea" :rows="2"/></el-form-item></el-form><template #footer><el-button @click="creating=false">取消</el-button><el-button type="primary" @click="doCreate" :loading="saving">提交</el-button></template></el-dialog></div></template>
<script setup lang="ts">import {ref,reactive,onMounted} from 'vue';import {ElMessage} from 'element-plus';import AppPagination from '@/components/common/AppPagination.vue';import {useListPage} from '@/composables/useListPage';import {useDetailDrawer} from '@/composables/useDetailDrawer';import {useUserNames} from '@/composables/useUserNames';import {fetchQcResults,fetchQcDetail,fetchQcStats,createQcResult,auditQcResult,type QcRecord} from '@/api/qc';import {useDict} from '@/composables/useDict'
const{items,loading,page,perPage,total,onSearch}=useListPage<QcRecord>(fetchQcResults)
const{drawer,detail,open}=useDetailDrawer<QcRecord>();const{userName}=useUserNames()
const{dictLabel:qcLabel}=useDict('QC')
function qcTagType(s:string):string{const m:Record<string,string>={GA:'success',BF:'danger',DJ:'warning',GC:'info'};return m[s]||'info'}
const s=reactive({search:''})
const stats=ref<{qcstatus:string;cnt:number}[]>([])
function doSearch(){onSearch(s.search?{search:s.search}:{})}
onMounted(async()=>{try{const r=await fetchQcStats();stats.value=r.data||[]}catch{}})
async function openDrawer(row:QcRecord){drawer.value=true;try{const r=await fetchQcDetail(row.qcbillid);detail.value=r.data}catch{detail.value=row}}
const creating=ref(false);const saving=ref(false)
const form=reactive({itemcd:'',eid:'',refbillid:'',qcstatus:'1',memo:''})
function openCreate(){creating.value=true}
function resetForm(){form.itemcd='';form.eid='';form.refbillid='';form.qcstatus='1';form.memo=''}
async function doCreate(){if(!form.itemcd){ElMessage.warning('请输入物料编码');return};saving.value=true;try{await createQcResult({...form});ElMessage.success('录入成功');creating.value=false;load()}catch(e:any){ElMessage.error(e?.response?.data?.message||'录入失败')}finally{saving.value=false}}
async function doAudit(id:string){try{await auditQcResult(id);ElMessage.success('审核成功');load()}catch(e:any){ElMessage.error(e?.response?.data?.message||'审核失败')}}
</script>
<style scoped>.page{padding:0}.page-header{display:flex;justify-content:space-between;margin-bottom:16px}.page-header h2{font-size:18px;font-weight:600;margin:0}.search-bar{display:flex;gap:12px;align-items:center}.field{display:flex;align-items:center;gap:6px}.field label{font-size:13px;color:#606266}</style>
