PROCEDURE SP_REPORT_TEST(IN_BEGDATE DATE , IN_ENDDATE DATE,IN_AREA NUMBER ,O_BASE OUT PG_PUB_GETPINYINBYHANZI.OUT_BASE ) IS

V_NUM PBTEMP_NUM%ROWTYPE;
BEGIN
  --BAOBIAO
  DELETE PBTEMP_NUM;
------考核总量
 SELECT COUNT(1) ZL,
     SUM(DECODE(D.CLASSCD,'08',0,1)) POSSL,
     SUM(DECODE(D.CLASSCD,'08',1,0)) JQSL,

     SUM(DECODE(L.TYPE, '2', 0, 1)) HMQDB,
     SUM(CASE WHEN L.TYPE IS NULL AND D.CLASSCD <>'08'THEN 1 ELSE 0 END) POSDB,
     SUM(CASE WHEN L.TYPE IS NULL AND D.CLASSCD ='08'THEN 1 ELSE 0 END) JQDB,

     SUM(DECODE(L.TYPE, '2', 1, 0)) HMQWDB,
     SUM(CASE WHEN L.TYPE = '2' AND D.CLASSCD <>'08'THEN 1 ELSE 0 END) POSWDB,
     SUM(CASE WHEN L.TYPE = '2' AND D.CLASSCD ='08'THEN 1 ELSE 0 END) JQWDB,

     SUM(DECODE(L.TYPE, '2', 0, 1)) /DECODE(COUNT(1),0,1,COUNT(1)) QBFB  ,
     SUM(CASE WHEN L.TYPE IS NULL AND D.CLASSCD <>'08'THEN 1 ELSE 0 END)/DECODE(SUM(DECODE(D.CLASSCD,'08',0,1)),0,1,SUM(DECODE(D.CLASSCD,'08',0,1))) POSBFB,
     SUM(CASE WHEN L.TYPE IS NULL AND D.CLASSCD ='08'THEN 1 ELSE 0 END)/DECODE(SUM(DECODE(D.CLASSCD,'08',1,0)),0,1,SUM(DECODE(D.CLASSCD,'08',1,0))) JQBFB,

     SUM(CASE WHEN L.EXEMPTFLG = 'N'OR L.EXEMPTFLG IS NULL OR (L.EXEMPTFLG ='Y' AND L.IS_FINISH <> '3') THEN 1 ELSE 0 END ) HMHZL,
     SUM(CASE WHEN (L.EXEMPTFLG = 'N'OR L.EXEMPTFLG IS NULL OR (L.EXEMPTFLG ='Y' AND L.IS_FINISH <> '3')) AND D.CLASSCD <> '08' THEN 1 ELSE 0 END ) HMHPOS,
     SUM(CASE WHEN (L.EXEMPTFLG = 'N'OR L.EXEMPTFLG IS NULL OR (L.EXEMPTFLG ='Y' AND L.IS_FINISH <> '3')) AND D.CLASSCD = '08' THEN 1 ELSE 0 END ) HMHJQ,

     SUM(CASE WHEN L.EXEMPTFLG = 'N'OR (L.EXEMPTFLG ='Y' AND L.IS_FINISH <> '3') THEN 1 ELSE 0 END ) WHMSL,
     SUM(CASE WHEN (L.EXEMPTFLG = 'N'OR (L.EXEMPTFLG ='Y' AND L.IS_FINISH <> '3')) AND D.CLASSCD <> '08' THEN 1 ELSE 0 END ) WHMPOS,
     SUM(CASE WHEN (L.EXEMPTFLG = 'N'OR (L.EXEMPTFLG ='Y' AND L.IS_FINISH <> '3')) AND D.CLASSCD = '08' THEN 1 ELSE 0 END ) WHMJQ,


     SUM(DECODE(L.TYPE, '2', 0, 1))/DECODE(SUM(CASE WHEN L.EXEMPTFLG = 'N'OR L.EXEMPTFLG IS NULL OR (L.EXEMPTFLG ='Y' AND L.IS_FINISH <> '3') THEN 1 ELSE 0 END ),0,1,SUM(CASE WHEN L.EXEMPTFLG = 'N'OR L.EXEMPTFLG IS NULL OR (L.EXEMPTFLG ='Y' AND L.IS_FINISH <> '3') THEN 1 ELSE 0 END )) WHMBFB  ,
     SUM(CASE WHEN L.TYPE IS NULL AND D.CLASSCD <>'08'THEN 1 ELSE 0 END)/DECODE(SUM(CASE WHEN (L.EXEMPTFLG = 'N'OR L.EXEMPTFLG IS NULL OR (L.EXEMPTFLG ='Y' AND L.IS_FINISH <> '3')) AND D.CLASSCD <> '08' THEN 1 ELSE 0 END ),0,1,SUM(CASE WHEN (L.EXEMPTFLG = 'N'OR L.EXEMPTFLG IS NULL OR (L.EXEMPTFLG ='Y' AND L.IS_FINISH <> '3')) AND D.CLASSCD <> '08' THEN 1 ELSE 0 END )) WHMPOSBFB,
     SUM(CASE WHEN L.TYPE IS NULL AND D.CLASSCD ='08'THEN 1 ELSE 0 END)/DECODE(SUM(CASE WHEN (L.EXEMPTFLG = 'N'OR L.EXEMPTFLG IS NULL OR (L.EXEMPTFLG ='Y' AND L.IS_FINISH <> '3')) AND D.CLASSCD = '08' THEN 1 ELSE 0 END ),0,1,SUM(CASE WHEN (L.EXEMPTFLG = 'N'OR L.EXEMPTFLG IS NULL OR (L.EXEMPTFLG ='Y' AND L.IS_FINISH <> '3')) AND D.CLASSCD = '08' THEN 1 ELSE 0 END )) WHMJQBFB
    INTO
      V_NUM.N1  ,  --ZL
      V_NUM.N2  ,  --POSSL
      V_NUM.N3  ,  --JQSL
      V_NUM.N4  ,  --HMQDB
      V_NUM.N5  ,  --POSDB
      V_NUM.N6  ,  --JQDB
      V_NUM.N7  ,  --HMQWDB
      V_NUM.N8  ,  --POSWDB
      V_NUM.N9  ,  --JQWDB
      V_NUM.N10  ,  --QBFB
      V_NUM.N11  ,  --POSBFB
      V_NUM.N12  ,  --JQBFB
      V_NUM.N13  ,  --HMHZL
      V_NUM.N14  ,  --HMHPOS
      V_NUM.N15  ,  --HMHJQ
      V_NUM.N16  ,  --WHMSL
      V_NUM.N17  ,  --WHMPOS
      V_NUM.N18  ,  --WHMJQ
      V_NUM.N19  ,  --WHMBFB
      V_NUM.N20  ,  --WHMPOSBFB
      V_NUM.N21    --WHMJQBFB
  FROM V_ITSM_PAPER_AVERAGEL_DB D,
       (SELECT * FROM TIT10_MAINTENANCE_LIABILITY WHERE TYPE = '2' ) L
  WHERE 1 = 1 AND CREATE_TIME >= IN_BEGDATE
            AND CREATE_TIME < IN_ENDDATE + 1
            AND D.FAULT_TYPE = '1'
            AND (D.AREA = IN_AREA OR IN_AREA = 0)
   AND D.MASTER_ID  = L.MAINTENANCE_ID(+) ;

  -------开单数
  SELECT COUNT(*) ZDS,
    SUM(CASE WHEN BILLTYPE ='WHD' AND PDCS > 0 THEN 1 ELSE 0 END) BXD,
    SUM(DECODE(BILLTYPE,'KTD',1,0)) KTD,
    SUM(DECODE(BILLTYPE,'BYD',1,0)) BYD,
    SUM(CASE WHEN BILLTYPE ='WHD' AND PDCS = 0 THEN 1 ELSE 0 END) FWT -- FIRSTOR IS NULL AND IS_SUCCESS IS NOT NULL
  INTO
    V_NUM.N22	,  --ZDS	
    V_NUM.N23	,  --BXD
    V_NUM.N24	,  --KTD
    V_NUM.N25	,  --BYD
    V_NUM.N26	   --FWT
  FROM V_ITSM_BILLALL T
  WHERE 1 = 1 AND CREATE_TIME >= IN_BEGDATE
            AND CREATE_TIME < IN_ENDDATE + 1
            AND (T.AREA = IN_AREA OR IN_AREA = 0) ;

  SELECT COUNT(1) RWZL,
    SUM(DECODE(JJBZ,'5',1,0)) CGRW,
    SUM(case when BILLTYPE = 'WHD'and JJBZ <> '5' then 1 else 0 end ) SBRW,
    SUM(DECODE(JJBZ,'5',1,0)) /DECODE(COUNT(1),0,1,COUNT(1)) CGLBFB,
    SUM(DECODE(BILLTYPE ,'KTD',1,0)) KTRW,
    SUM(CASE WHEN BILLTYPE ='WHD' AND D2D_GROUP > 0 THEN 1 ELSE 0 END ) WHRW,
    SUM(DECODE(BILLTYPE ,'BYD',1,0)) BYRW,
    SUM(CASE WHEN BILLTYPE ='WHD' AND D2D_GROUP = 0 THEN 1 ELSE 0 END) FWT,
    SUM(CASE WHEN CLASSCD  <>'08' AND BUSITYP  = 'ZS' THEN 1 ELSE 0 END) ZSRW,
    SUM(CASE WHEN CLASSCD  <>'08' AND BUSITYP  = 'YS' THEN 1 ELSE 0 END) YSRW,
    SUM(CASE WHEN CLASSCD  ='08'  THEN 1 ELSE 0 END) JQRW ,

    SUM(CASE WHEN L.EXEMPTFLG ='Y' AND L.IS_FINISH = '3' THEN 1 ELSE 0 END) /*+ SUM(CASE WHEN JJBZ = '4'AND BILLTYPE <> 'WHD' THEN 1 ELSE 0 END)*/ MZRW,
    SUM(CASE WHEN L.EXEMPTFLG ='N'OR (L.EXEMPTFLG ='Y' AND L.IS_FINISH <> '3' ) THEN 1 ELSE 0 END) WMZRW,
    (COUNT(1) - SUM(CASE WHEN L.EXEMPTFLG ='N'OR (L.EXEMPTFLG ='Y' AND L.IS_FINISH <> '3' ) THEN 1 ELSE 0 END))/DECODE(COUNT(1),0,1,COUNT(1)) MZHCGLBFB,
    SUM(case when BILLTYPE <> 'WHD'and JJBZ <> '5' then 1 else 0 end ) SSDSBRW
  INTO
      V_NUM.N27	,  --RWZL	
      V_NUM.N28	,  --CGRW
      V_NUM.N29	,  --SBRW
      V_NUM.N30	,  --CGLBFB
      V_NUM.N31	,  --KTRW
      V_NUM.N32	,  --WHRW
      V_NUM.N33	,  --BYRW
      V_NUM.N34	,  --FWT
      V_NUM.N35	,  --ZSRW
      V_NUM.N36	,  --YSRW
      V_NUM.N37	,  --JQRW
      V_NUM.N38	,  --MZRW
      V_NUM.N39	,  --WMZRW
      V_NUM.N40	,   --CGLBFB(H)
      V_NUM.N59    --SSDSBRW
  FROM (
  SELECT T.*,D.D2D_GROUP,JJBZ
  FROM V_ITSM_BILLALL T,
  (SELECT ROW_NUMBER() OVER(PARTITION BY MAINTENANCE_ID ORDER BY JJBZ,UPDATE_TIME,BUSINESS_OPERATION_ID ) RNUM,
  C.* FROM TIT23_MAINTENANCE_D2D C
  WHERE C.D2D_TYPE = '2'
  AND C.D2D_GROUP = 1 ) D
  WHERE MASTER_ID = D.MAINTENANCE_ID
  AND T.CREATE_TIME >= IN_BEGDATE
  AND T.CREATE_TIME  < IN_ENDDATE + 1
  AND D.RNUM = 1
  AND (T.AREA = IN_AREA OR IN_AREA = 0)
  UNION ALL
  SELECT T.*,0,'5' FROM V_ITSM_BILLALL T
  WHERE T.CREATE_TIME >= IN_BEGDATE
  AND T.CREATE_TIME  < IN_ENDDATE + 1
  AND (T.AREA  = IN_AREA OR IN_AREA = 0)
  AND NOT EXISTS (SELECT D.MAINTENANCE_ID FROM TIT23_MAINTENANCE_D2D D
  WHERE D.MAINTENANCE_ID = T.MASTER_ID AND D.USEFLG<>'9' AND (D.D2D_TYPE ='1' OR D.D2D_TYPE ='2') )) A,
  (SELECT * FROM TIT10_MAINTENANCE_LIABILITY WHERE TYPE = '1' ) L
  WHERE A.MASTER_ID  = L.MAINTENANCE_ID(+);

  SELECT SUM(DECODE(CS,0,1,0)) SJS0,
    SUM(DECODE(CS,1,1,0)) SJS1,
    SUM(DECODE(CS,2,1,0)) SJS2,
    SUM(DECODE(CS,3,1,0)) SJS3,
    SUM(DECODE(CS,4,1,0)) SJS4,
    SUM(DECODE(CS,5,1,0)) SJS5,
    SUM(DECODE(CS,6,1,0)) SJS6,
    SUM(DECODE(CS,7,1,0)) SJS7,
    SUM(DECODE(CS,8,1,0)) SJS8,
    SUM(DECODE(CS,0,CS,0)) RWS0,
    SUM(DECODE(CS,1,CS,0)) RWS1,
    SUM(DECODE(CS,2,CS,0)) RWS2,
    SUM(DECODE(CS,3,CS,0)) RWS3,
    SUM(DECODE(CS,4,CS,0)) RWS4,
    SUM(DECODE(CS,5,CS,0)) RWS5,
    SUM(DECODE(CS,6,CS,0)) RWS6,
    SUM(DECODE(CS,7,CS,0)) RWS7,
    SUM(DECODE(CS,8,CS,0)) RWS8
  INTO
    V_NUM.N41	,  --SJS0	
    V_NUM.N42	,  --SJS1
    V_NUM.N43	,  --SJS2
    V_NUM.N44	,  --SJS3
    V_NUM.N45	,  --SJS4
    V_NUM.N46	,  --SJS5
    V_NUM.N47	,  --SJS6
    V_NUM.N48	,  --SJS7
    V_NUM.N49	,  --SJS8
    V_NUM.N50	,  --RWS0
    V_NUM.N51	,  --RWS1
    V_NUM.N52	,  --RWS2	
    V_NUM.N53	,  --RWS3	
    V_NUM.N54	,  --RWS4
    V_NUM.N55	,  --RWS5	
    V_NUM.N56	,  --RWS6	
    V_NUM.N57	,  --RWS7
    V_NUM.N58	   --RWS8	
  FROM(
  SELECT  MASTER_ID,SUM(DECODE(D2D_GROUP,0,0,1 )) CS
  FROM (
  SELECT T.*,D.D2D_GROUP
  FROM V_ITSM_BILLALL T,TIT23_MAINTENANCE_D2D D
  WHERE MASTER_ID = D.MAINTENANCE_ID
  AND (D.D2D_TYPE = '2'AND D.USEFLG = '1'
  AND T.CREATE_TIME >= IN_BEGDATE
  AND T.CREATE_TIME < IN_ENDDATE + 1
  AND (T.AREA = IN_AREA OR IN_AREA = 0))
  UNION ALL
  SELECT T.*,0 FROM V_ITSM_BILLALL T
  WHERE T.CREATE_TIME  >= IN_BEGDATE
  AND T.CREATE_TIME  < IN_ENDDATE + 1
  AND (T.AREA = IN_AREA OR IN_AREA = 0)
  AND NOT EXISTS (SELECT D.MAINTENANCE_ID FROM TIT23_MAINTENANCE_D2D D
  WHERE D.MAINTENANCE_ID = T.MASTER_ID AND D.USEFLG<>'9' AND (D.D2D_TYPE ='1' OR D.D2D_TYPE ='2')  ))
  GROUP BY MASTER_ID);

  INSERT INTO PBTEMP_NUM VALUES V_NUM;

  OPEN O_BASE FOR
  SELECT * FROM PBTEMP_NUM;

  --已使用到 N59 ,添加请从N60 开始

END;
