<template><div class="page"><div class="page-header"><h2>新机开通</h2></div><el-card shadow="never"><el-table :data="items" v-loading="loading" stripe size="small" highlight-current-row @row-click="open"><el-table-column prop="new_opening_id" label="开通单号" width="120"/><el-table-column label="公司" width="120"><template #default="{row}">{{ className(row.company_id as string) }}</template></el-table-column><el-table-column prop="store_id" label="门店" width="90"/><el-table-column prop="device_id" label="主设备EID" width="150" show-overflow-tooltip/><el-table-column label="状态" width="80"><template #default="{row}"><el-tag :type="statusTag(row.current_status as string)" size="small">{{ statusLabel(row.current_status as string) }}</el-tag></template></el-table-column><el-table-column label="负责人" width="80"><template #default="{row}">{{ userName(row.firstor as string) }}</template></el-table-column><el-table-column label="创建日期" width="100"><template #default="{row}">{{ row.create_time || '-' }}</template></el-table-column><el-table-column label="完成日期" width="100"><template #default="{row}">{{ row.close_time || '-' }}</template></el-table-column><el-table-column prop="count" label="数量" width="60" align="right"/></el-table><AppPagination v-model:current-page="page" v-model:page-size="perPage" :total="total" style="margin-top:12px;justify-content:flex-end"/></el-card>
    <el-dialog :title="'开通单 — '+(detail?.new_opening_id||'')" v-model="drawer" width="680px" @open="loadDetail"><template v-if="detail"><el-descriptions :column="2" border size="small"><el-descriptions-item label="单号">{{ detail.new_opening_id }}</el-descriptions-item><el-descriptions-item label="公司">{{ className(detail.company_id as string) }}</el-descriptions-item><el-descriptions-item label="门店">{{ detail.store_id || '-' }}</el-descriptions-item><el-descriptions-item label="状态"><el-tag :type="statusTag(detail.current_status as string)" size="small">{{ statusLabel(detail.current_status as string) }}</el-tag></el-descriptions-item><el-descriptions-item label="主设备EID" :span="2">{{ detail.device_id || '-' }}</el-descriptions-item><el-descriptions-item label="数量">{{ detail.count }}</el-descriptions-item><el-descriptions-item label="负责人">{{ userName(detail.firstor as string) }}</el-descriptions-item><el-descriptions-item label="创建">{{ detail.create_time }}</el-descriptions-item><el-descriptions-item label="完成">{{ detail.close_time||'-' }}</el-descriptions-item><el-descriptions-item label="详情" :span="2">{{ detail.detail_description||'-' }}</el-descriptions-item></el-descriptions>
      <el-divider content-position="left" style="margin:16px 0 8px">设备明细（TIT14_EQUIPMENT_OPEN）</el-divider>
      <el-table :data="detailEquipments" size="small" v-loading="detailLoading" empty-text="暂无设备明细">
        <el-table-column prop="device_id" label="设备 EID" width="160" show-overflow-tooltip/>
        <el-table-column prop="delivery_id" label="送货单号" width="100"/>
        <el-table-column label="是否完成" width="70"><template #default="{row}"><el-tag size="small" :type="row.is_finish==='Y'?'success':'info'">{{ row.is_finish==='Y'?'完成':'未完成' }}</el-tag></template></el-table-column>
        <el-table-column label="是否换机" width="70"><template #default="{row}"><el-tag size="small" :type="row.is_change==='Y'?'warning':'info'">{{ row.is_change==='Y'?'换机':'否' }}</el-tag></template></el-table-column>
        <el-table-column prop="change_eid" label="换机EID" width="150" show-overflow-tooltip/>
        <el-table-column prop="from_custcard" label="来源磁卡号" width="110"/>
        <el-table-column prop="from_posid" label="来源POS" width="120" show-overflow-tooltip/>
      </el-table>
      </template>
    </el-dialog>
  </div></template>
<script setup lang="ts">import AppPagination from '@/components/common/AppPagination.vue';import {useListPage} from '@/composables/useListPage';import {useDetailDrawer} from '@/composables/useDetailDrawer';import {useUserNames} from '@/composables/useUserNames';import {useCustClass} from '@/composables/useCustClass';import {fetchMaintenanceOpen, fetchMaintenanceOpenDetail} from '@/api/itsm';import type {MntRecord} from '@/api/itsm';import {ref} from 'vue'
const{items,loading,page,perPage,total}=useListPage<MntRecord>(fetchMaintenanceOpen);const{drawer,detail,open}=useDetailDrawer<MntRecord>();const{userName}=useUserNames();const{className}=useCustClass()
const detailEquipments = ref<Record<string,unknown>[]>([]);const detailLoading = ref(false)
async function loadDetail(){if(!detail.value?.new_opening_id)return;detailLoading.value=true;try{const r=await fetchMaintenanceOpenDetail(detail.value.new_opening_id as string);detailEquipments.value=((r as any)?.data?.equipments||[]) as any}catch{detailEquipments.value=[]}finally{detailLoading.value=false}}
function statusTag(s:string){const m:Record<string,string>={'1':'info','2':'primary','3':'success','4':'warning','5':'primary','9':'danger'};return m[s]||'info'}
function statusLabel(s:string){const m:Record<string,string>={'1':'新建','2':'分配','3':'关闭','4':'未解决','5':'已解决','9':'作废'};return m[s]||s}</script>
<style scoped>.page{padding:0}.page-header{display:flex;justify-content:space-between;margin-bottom:16px}.page-header h2{font-size:18px;font-weight:600;margin:0}</style>