<template><div class="page"><div class="page-header"><h2>工序定义</h2><el-button type="primary" size="small" @click="openCreate">新建工序</el-button></div><el-card shadow="never"><el-table :data="items" v-loading="loading" stripe size="small" highlight-current-row><el-table-column prop="process_cd" label="工序编码" width="100"/><el-table-column prop="process_nm" label="工序名称" min-width="150"/><el-table-column label="工序类型" width="100"><template #default="{row}">{{ row.process_type||'-' }}</template></el-table-column><el-table-column label="标准工时(h)" width="100"><template #default="{row}">{{ row.std_hours||'-' }}</template></el-table-column><el-table-column prop="sort_no" label="排序号" width="70"/><el-table-column label="有效" width="60"><template #default="{row}"><el-tag :type="row.useflg==='1'?'success':'info'" size="small">{{ row.useflg==='1'?'是':'否' }}</el-tag></template></el-table-column><el-table-column label="操作" width="100" fixed="right"><template #default="{row}"><el-button link type="primary" size="small" @click.stop="openEdit(row)">编辑</el-button></template></el-table-column></el-table><AppPagination v-model:current-page="page" v-model:page-size="perPage" :total="total" style="margin-top:12px;justify-content:flex-end"/></el-card>

<el-dialog :title="editing?'编辑工序':'新建工序'" v-model="dialogVisible" width="430px" @closed="resetForm"><el-form :model="form" label-width="90px" size="small"><el-form-item label="工序编码" required><el-input v-model="form.process_cd" :disabled="editing" placeholder="如 ASSEMBLY"/></el-form-item><el-form-item label="工序名称" required><el-input v-model="form.process_nm" placeholder="如 组装"/></el-form-item><el-form-item label="工序类型"><el-input v-model="form.process_type" placeholder="如 MANUAL"/></el-form-item><el-form-item label="标准工时(h)"><el-input-number v-model="form.std_hours" :min="0" :precision="1" style="width:100%"/></el-form-item><el-form-item label="排序号"><el-input-number v-model="form.sort_no" :min="0" style="width:100%"/></el-form-item><el-form-item label="有效"><el-switch v-model="form.useflg" active-value="1" inactive-value="0"/></el-form-item><el-form-item label="备注"><el-input v-model="form.remark" type="textarea" :rows="2"/></el-form-item></el-form><template #footer><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" @click="doSave" :loading="saving">保存</el-button></template></el-dialog></div></template>

<script setup lang="ts">import {ref,reactive} from 'vue';import {ElMessage} from 'element-plus';import AppPagination from '@/components/common/AppPagination.vue';import {useListPage} from '@/composables/useListPage';import {fetchProcessDefs,createProcessDef,updateProcessDef} from '@/api/mes';import type {MesRecord} from '@/api/mes'
const{items,loading,page,perPage,total,load}=useListPage<MesRecord>(fetchProcessDefs)
const dialogVisible=ref(false);const editing=ref(false);const saving=ref(false)
const form=reactive({process_cd:'',process_nm:'',process_type:'',std_hours:0,sort_no:0,useflg:'1',remark:''})

function openCreate(){editing.value=false;resetForm();dialogVisible.value=true}
function openEdit(row:MesRecord){editing.value=true;Object.assign(form,{process_cd:row.process_cd||'',process_nm:row.process_nm||'',process_type:row.process_type||'',std_hours:Number(row.std_hours)||0,sort_no:Number(row.sort_no)||0,useflg:row.useflg||'1',remark:row.remark||''});dialogVisible.value=true}
function resetForm(){Object.assign(form,{process_cd:'',process_nm:'',process_type:'',std_hours:0,sort_no:0,useflg:'1',remark:''})}

async function doSave(){if(!form.process_cd||!form.process_nm){ElMessage.warning('工序编码和名称必填');return};saving.value=true;try{if(editing.value){await updateProcessDef(form.process_cd,{process_nm:form.process_nm,process_type:form.process_type,std_hours:form.std_hours,sort_no:form.sort_no,useflg:form.useflg,remark:form.remark||undefined});ElMessage.success('已更新')}else{await createProcessDef({...form});ElMessage.success('已创建')};dialogVisible.value=false;load()}catch(e:any){ElMessage.error(e?.response?.data?.message||'保存失败')}finally{saving.value=false}}</script>
<style scoped>.page{padding:0}.page-header{display:flex;justify-content:space-between;margin-bottom:16px}.page-header h2{font-size:18px;font-weight:600;margin:0}</style>
